local UIMultiLanguage_EN = {
["01_01_LoadingLayerLoadingText_TT"] = { CsdId = "01_01_LoadingLayer", NodeId = "LoadingText_TT", Text = "Loading game...", TextValueArray = "" },
["01_01_LoadingLayerLoadingHintText_TT"] = { CsdId = "01_01_LoadingLayer", NodeId = "LoadingHintText_TT", Text = "Up the ante and bring on the heat!", TextValueArray = "" },
["01_01_LoadingLayer_0LoadingText_TT"] = { CsdId = "01_01_LoadingLayer_0", NodeId = "LoadingText_TT", Text = "Loading game...", TextValueArray = "" },
["01_01_LoadingLayer_0LoadingHintText_TT"] = { CsdId = "01_01_LoadingLayer_0", NodeId = "LoadingHintText_TT", Text = "Up the ante and bring on the heat!", TextValueArray = "" },
["01_01_LoadingTipPopUp_1TitleText_TT"] = { CsdId = "01_01_LoadingTipPopUp_1", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_01_LoadingTipPopUp_1ContentText_1_TT"] = { CsdId = "01_01_LoadingTipPopUp_1", NodeId = "ContentText_1_TT", Text = "You current version of the game needs to be updated. The size of this update is about {0}MB. Select 'Confirm' to download the update, or click 'Cancel' to exit the game.", TextValueArray = "" },
["01_01_LoadingTipPopUp_1ContentText_2_TT"] = { CsdId = "01_01_LoadingTipPopUp_1", NodeId = "ContentText_2_TT", Text = "You're currently using mobile data. We recommend connecting to Wifi to download the update.", TextValueArray = "" },
["01_01_LoadingTipPopUp_1ConfirmText_TT"] = { CsdId = "01_01_LoadingTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_01_LoadingTipPopUp_1CancelText_TT"] = { CsdId = "01_01_LoadingTipPopUp_1", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_01_LoadingTipPopUp_2TitleText_TT"] = { CsdId = "01_01_LoadingTipPopUp_2", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_01_LoadingTipPopUp_2ContenText_TT"] = { CsdId = "01_01_LoadingTipPopUp_2", NodeId = "ContenText_TT", Text = "Your game version is out of date. Please press 'Update' to install the latest update. If you run into an issue please contact the developer.", TextValueArray = "" },
["01_01_LoadingTipPopUp_2JumpText_TT"] = { CsdId = "01_01_LoadingTipPopUp_2", NodeId = "JumpText_TT", Text = "Update", TextValueArray = "" },
["01_01_LoadingTipPopUp_3TitleText_TT"] = { CsdId = "01_01_LoadingTipPopUp_3", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_01_LoadingTipPopUp_3ContenText_TT"] = { CsdId = "01_01_LoadingTipPopUp_3", NodeId = "ContenText_TT", Text = "Failed to connect to the server. Try again?", TextValueArray = "" },
["01_01_LoadingTipPopUp_3RetryText_TT"] = { CsdId = "01_01_LoadingTipPopUp_3", NodeId = "RetryText_TT", Text = "Retry", TextValueArray = "" },
["01_01_LoadingTipPopUp_3CancelText_TT"] = { CsdId = "01_01_LoadingTipPopUp_3", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_01_LoadingTipPopUp_4TitleText_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_01_LoadingTipPopUp_4ContentText_1_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "ContentText_1_TT", Text = "Update has encountered an error. Please check your connection.", TextValueArray = "" },
["01_01_LoadingTipPopUp_4ContentText_2_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "ContentText_2_TT", Text = "Once the update is complete, please restart the game.", TextValueArray = "" },
["01_01_LoadingTipPopUp_4ConfirmText_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_01_LoadingTipPopUp_4RetryText_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "RetryText_TT", Text = "Retry", TextValueArray = "" },
["01_01_LoadingTipPopUp_4CancelText_TT"] = { CsdId = "01_01_LoadingTipPopUp_4", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_01_LoginLayerPasswordErrorText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "PasswordErrorText_TT", Text = "Password has to contain 6-12 letters and numbers", TextValueArray = "" },
["01_01_LoginLayerTitleText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "TitleText_TT", Text = " ", TextValueArray = "" },
["01_01_LoginLayerUserNameErrorText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "UserNameErrorText_TT", Text = "Account name is not available", TextValueArray = "" },
["01_01_LoginLayerTouristButtonText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "TouristButtonText_TT", Text = "Continue as guest", TextValueArray = "" },
["01_01_LoginLayerRegisterButtonText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "RegisterButtonText_TT", Text = "Register", TextValueArray = "" },
["01_01_LoginLayerLoginButtonText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "LoginButtonText_TT", Text = "Log in", TextValueArray = "" },
["01_02_MainFriendListCell_1StateText_1_TT"] = { CsdId = "01_02_MainFriendListCell_1", NodeId = "StateText_1_TT", Text = "In game", TextValueArray = "" },
["01_02_MainFriendListCell_1StateText_2_TT"] = { CsdId = "01_02_MainFriendListCell_1", NodeId = "StateText_2_TT", Text = "Spectating", TextValueArray = "" },
["01_02_MainFriendListCell_1StateText_3_TT"] = { CsdId = "01_02_MainFriendListCell_1", NodeId = "StateText_3_TT", Text = "In queue", TextValueArray = "" },
["01_02_MainFriendListCell_1StateText_4_TT"] = { CsdId = "01_02_MainFriendListCell_1", NodeId = "StateText_4_TT", Text = "In lobby", TextValueArray = "" },
["01_02_MainFriendListCell_1StateText_5_TT"] = { CsdId = "01_02_MainFriendListCell_1", NodeId = "StateText_5_TT", Text = "Offline", TextValueArray = "" },
["01_01_LoginLayerSocialLoginText_TT"] = { CsdId = "01_01_LoginLayer", NodeId = "SocialLoginText_TT", Text = "Continue with", TextValueArray = "" },
["01_01_NoticeLayerKnowText_TT"] = { CsdId = "01_01_NoticeLayer", NodeId = "KnowText_TT", Text = "Accept", TextValueArray = "" },
["01_02_MainAddFriendsPopUpContentText_TT"] = { CsdId = "01_02_MainAddFriendsPopUp", NodeId = "ContentText_TT", Text = " sent a friend request", TextValueArray = "" },
["01_02_MainAddFriendsPopUpAgreeText_TT"] = { CsdId = "01_02_MainAddFriendsPopUp", NodeId = "AgreeText_TT", Text = "Accept", TextValueArray = "" },
["01_02_MainAddFriendsPopUpRefuseText_TT"] = { CsdId = "01_02_MainAddFriendsPopUp", NodeId = "RefuseText_TT", Text = "Decline", TextValueArray = "" },
["01_02_MainFriendListCell_2StateText_6_TT"] = { CsdId = "01_02_MainFriendListCell_2", NodeId = "StateText_6_TT", Text = "In game", TextValueArray = "" },
["01_02_MainFriendListCell_2StateText_7_TT"] = { CsdId = "01_02_MainFriendListCell_2", NodeId = "StateText_7_TT", Text = "Spectating", TextValueArray = "" },
["01_02_MainFriendListCell_2StateText_8_TT"] = { CsdId = "01_02_MainFriendListCell_2", NodeId = "StateText_8_TT", Text = "In queue", TextValueArray = "" },
["01_02_MainFriendListCell_2StateText_9_TT"] = { CsdId = "01_02_MainFriendListCell_2", NodeId = "StateText_9_TT", Text = "In lobby", TextValueArray = "" },
["01_02_MainFriendListCell_2StateText_10_TT"] = { CsdId = "01_02_MainFriendListCell_2", NodeId = "StateText_10_TT", Text = "Offline", TextValueArray = "" },
["01_02_MainFriendsListOnlineText_TT"] = { CsdId = "01_02_MainFriendsList", NodeId = "OnlineText_TT", Text = "Online: {0}", TextValueArray = "" },
["01_02_MainLayerFreeGoldTipText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "FreeGoldTipText_TT", Text = "Ltd offer", TextValueArray = "" },
["01_03_PropKnapsackDiceCupPopUpUseText_TT"] = { CsdId = "01_03_PropKnapsackDiceCupPopUp", NodeId = "UseText_TT", Text = "Equip", TextValueArray = "" },
["01_03_PropKnapsackDiceCupPopUpUsingText_TT"] = { CsdId = "01_03_PropKnapsackDiceCupPopUp", NodeId = "UsingText_TT", Text = "Equipped", TextValueArray = "" },
["01_03_PropKnapsackPopUpAllText_TT"] = { CsdId = "01_03_PropKnapsackPopUp", NodeId = "AllText_TT", Text = "Loot", TextValueArray = "" },
["01_03_PropKnapsackPopUpInterimText_TT"] = { CsdId = "01_03_PropKnapsackPopUp", NodeId = "InterimText_TT", Text = "Skins", TextValueArray = "" },
["01_03_PropKnapsackPopUpEmptyText_TT"] = { CsdId = "01_03_PropKnapsackPopUp", NodeId = "EmptyText_TT", Text = "No content", TextValueArray = "" },
["01_03_PropKnapsackTipPopUpPropText_TT"] = { CsdId = "01_03_PropKnapsackTipPopUp", NodeId = "PropText_TT", Text = "", TextValueArray = "" },
["01_04_TaskCellStartText_TT"] = { CsdId = "01_04_TaskCell", NodeId = "StartText_TT", Text = "Claim ", TextValueArray = "" },
["01_04_TaskCellReceiveText_TT"] = { CsdId = "01_04_TaskCell", NodeId = "ReceiveText_TT", Text = "Claim", TextValueArray = "" },
["01_04_TaskCellReceivedText_TT"] = { CsdId = "01_04_TaskCell", NodeId = "ReceivedText_TT", Text = "Complete", TextValueArray = "" },
["01_04_TaskCellTaskLoadingText_TT"] = { CsdId = "01_04_TaskCell", NodeId = "TaskLoadingText_TT", Text = "Complete", TextValueArray = "" },
["01_04_TaskPopUpRefreshText_TT"] = { CsdId = "01_04_TaskPopUp", NodeId = "RefreshText_TT", Text = "Resets Sunday 24:00", TextValueArray = "" },
["01_04_TaskPopUpWeekActivityText_TT"] = { CsdId = "01_04_TaskPopUp", NodeId = "WeekActivityText_TT", Text = "POINTS", TextValueArray = "" },
["01_04_TaskPopUpReceiveText_TT"] = { CsdId = "01_04_TaskPopUp", NodeId = "ReceiveText_TT", Text = "Claim all", TextValueArray = "" },
["01_06_HeadSittingLayerPersonalizationText_TT"] = { CsdId = "01_06_HeadSittingLayer", NodeId = "PersonalizationText_TT", Text = "Profile Settings", TextValueArray = "" },
["01_06_HeadSittingLayerModifyHeadText_TT"] = { CsdId = "01_06_HeadSittingLayer", NodeId = "ModifyHeadText_TT", Text = "Profile picture", TextValueArray = "" },
["01_06_ModifyNameConfirmLayerModifyNameConfirmText_TT"] = { CsdId = "01_06_ModifyNameConfirmLayer", NodeId = "ModifyNameConfirmText_TT", Text = "First change is free. Are you sure to continue?", TextValueArray = "" },
["01_06_HeadSittingLayerModifyHeadFrameText_TT"] = { CsdId = "01_06_HeadSittingLayer", NodeId = "ModifyHeadFrameText_TT", Text = "Profile Border", TextValueArray = "" },
["01_06_HeadSittingLayerConfirmText_TT"] = { CsdId = "01_06_HeadSittingLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_HeadSittingLayerCancelText_TT"] = { CsdId = "01_06_HeadSittingLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_ModifyNameConfirmLayerConfirmText_TT"] = { CsdId = "01_06_ModifyNameConfirmLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_ModifyNameConfirmLayerCancelText_TT"] = { CsdId = "01_06_ModifyNameConfirmLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_ModifyNameLayerTitleText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "TitleText_TT", Text = "Change Nickname", TextValueArray = "" },
["01_06_ModifyNameLayerErrorTipText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "ErrorTipText_TT", Text = "Account name is not available", TextValueArray = "" },
["01_06_ModifyNameLayerDiamondText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "DiamondText_TT", Text = " ", TextValueArray = "" },
["01_06_ModifyNameLayerFirstText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "FirstText_TT", Text = "First change is free", TextValueArray = "" },
["01_06_ModifyNameLayerConfirmText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_ModifyNameLayerCancelText_TT"] = { CsdId = "01_06_ModifyNameLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_ModifySexLayerTitleText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "TitleText_TT", Text = "Change Gender", TextValueArray = "" },
["01_06_ModifySexLayerNoDisplayedText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "NoDisplayedText_TT", Text = "Don't show", TextValueArray = "" },
["01_06_ModifySexLayerDiamondText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "DiamondText_TT", Text = " ", TextValueArray = "" },
["01_06_ModifySexLayerFirstText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "FirstText_TT", Text = "First change is free", TextValueArray = "" },
["01_06_ModifySexLayerConfirmText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_ModifySexLayerCancelText_TT"] = { CsdId = "01_06_ModifySexLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_ModifySignatureLayerTitleText_TT"] = { CsdId = "01_06_ModifySignatureLayer", NodeId = "TitleText_TT", Text = "Change Bio", TextValueArray = "" },
["01_06_ModifySignatureLayerConfirmText_TT"] = { CsdId = "01_06_ModifySignatureLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_ModifySignatureLayerCancelText_TT"] = { CsdId = "01_06_ModifySignatureLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_PersonalCenterBlackTipPopUpTipTitleText_TT"] = { CsdId = "01_06_PersonalCenterBlackTipPopUp", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["01_06_PersonalCenterBlackTipPopUpTipContentText_TT"] = { CsdId = "01_06_PersonalCenterBlackTipPopUp", NodeId = "TipContentText_TT", Text = "Are you sure to blacklist this player?", TextValueArray = "" },
["01_06_PersonalCenterBlackTipPopUpConfirmText_TT"] = { CsdId = "01_06_PersonalCenterBlackTipPopUp", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_PersonalCenterBlackTipPopUpCancelText_TT"] = { CsdId = "01_06_PersonalCenterBlackTipPopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_PersonalCenterDeleteTipPopUpTipTitleText_TT"] = { CsdId = "01_06_PersonalCenterDeleteTipPopUp", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["01_06_PersonalCenterDeleteTipPopUpTipContentText_TT"] = { CsdId = "01_06_PersonalCenterDeleteTipPopUp", NodeId = "TipContentText_TT", Text = "Are you sure to delete this friend?", TextValueArray = "" },
["01_06_PersonalCenterDeleteTipPopUpConfirmText_TT"] = { CsdId = "01_06_PersonalCenterDeleteTipPopUp", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_06_PersonalCenterDeleteTipPopUpCancelText_TT"] = { CsdId = "01_06_PersonalCenterDeleteTipPopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_PersonalCenterMorePopUpBlackText_1_TT"] = { CsdId = "01_06_PersonalCenterMorePopUp", NodeId = "BlackText_1_TT", Text = "Unblock Players", TextValueArray = "" },
["01_06_PersonalCenterMorePopUpMoreTitleText_TT"] = { CsdId = "01_06_PersonalCenterMorePopUp", NodeId = "MoreTitleText_TT", Text = "Options", TextValueArray = "" },
["01_06_PersonalCenterMorePopUpBlackText_TT"] = { CsdId = "01_06_PersonalCenterMorePopUp", NodeId = "BlackText_TT", Text = "Block player", TextValueArray = "" },
["01_06_PersonalCenterMorePopUpDeleteText_TT"] = { CsdId = "01_06_PersonalCenterMorePopUp", NodeId = "DeleteText_TT", Text = "Delete friend", TextValueArray = "" },
["01_06_PersonalInformationLayerTitleText_TT"] = { CsdId = "01_06_PersonalInformationLayer", NodeId = "TitleText_TT", Text = "Player Profile", TextValueArray = "" },
["01_06_PersonalInformationLayerSignatureText_TT"] = { CsdId = "01_06_PersonalInformationLayer", NodeId = "SignatureText_TT", Text = "Bio", TextValueArray = "" },
["01_06_PersonalInformationLayerContentText_0_TT"] = { CsdId = "01_06_PersonalInformationLayer", NodeId = "ContentText_0_TT", Text = "Player has no bio information", TextValueArray = "" },
["01_06_PersonalInformationLayerModifyText_TT"] = { CsdId = "01_06_PersonalInformationLayer", NodeId = "ModifyText_TT", Text = "Edit", TextValueArray = "" },
["01_06_PersonalInformationLayerFansText_TT"] = { CsdId = "01_06_PersonalInformationLayer", NodeId = "FansText_TT", Text = "Followers", TextValueArray = "" },
["01_06_PersonalLayerTitleText_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "TitleText_TT", Text = "Player Profile", TextValueArray = "" },
["01_06_PersonalLayerAddFriendText_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "AddFriendText_TT", Text = "Add", TextValueArray = "" },
["01_06_PersonalLayerSignatureText_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "SignatureText_TT", Text = "Bio", TextValueArray = "" },
["01_06_PersonalLayerMoreText_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "MoreText_TT", Text = "Options", TextValueArray = "" },
["01_06_PersonalLayerCancelText_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_06_PersonalLayerContentText_0_TT"] = { CsdId = "01_06_PersonalLayer", NodeId = "ContentText_0_TT", Text = "Player has no bio information", TextValueArray = "" },
["01_07_SittingAccountLayerTitleText_1_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "TitleText_1_TT", Text = "Manage Account", TextValueArray = "" },
["01_07_SittingAccountLayerAccountText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "AccountText_TT", Text = "Account", TextValueArray = "" },
["01_07_SittingAccountLayerAccountSittingText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "AccountSittingText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerPhoneText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "PhoneText_TT", Text = "Phone number", TextValueArray = "" },
["01_07_SittingAccountLayerFacebookbindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "FacebookbindText_TT", Text = "Linked", TextValueArray = "" },
["01_07_SittingAccountLayerPhoneUnBindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "PhoneUnBindText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerGooglebindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "GooglebindText_TT", Text = "Linked", TextValueArray = "" },
["01_07_SittingAccountLayerPasswordText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "PasswordText_TT", Text = "Password", TextValueArray = "" },
["01_07_SittingAccountLayerApplebindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "ApplebindText_TT", Text = "Linked", TextValueArray = "" },
["01_07_SittingAccountLayerPasswordSitting_1_Text_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "PasswordSitting_1_Text_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerWeChatIbindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "WeChatIbindText_TT", Text = "Linked", TextValueArray = "" },
["01_07_SittingAccountLayerPasswordSitting_2_Text_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "PasswordSitting_2_Text_TT", Text = "Change", TextValueArray = "" },
["01_07_SittingAccountLayerTitleText_2_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "TitleText_2_TT", Text = "Social media", TextValueArray = "" },
["01_07_SittingAccountLayerFacebookUnBindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "FacebookUnBindText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerGoogleUnBindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "GoogleUnBindText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerAppleUnBindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "AppleUnBindText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerLineUnBindText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "LineUnBindText_TT", Text = "Not set", TextValueArray = "" },
["01_07_SittingAccountLayerFacebookRelieveText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "FacebookRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingAccountLayerGoogleRelieveText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "GoogleRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingAccountLayerAppleRelieveText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "AppleRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingAccountLayerLineRelieveText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "LineRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingBindChangeLayerReturnText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingBindChangeLayerTitleText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "TitleText_TT", Text = "Change Phone Number", TextValueArray = "" },
["01_07_SittingBindChangeLayerContentText_1_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "ContentText_1_TT", Text = "Enter new phone number", TextValueArray = "" },
["01_07_SittingBindChangeLayerContentText_2_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "ContentText_2_TT", Text = "Enter verification code", TextValueArray = "" },
["01_07_SittingBindChangeLayerPhoneNumErrorTipText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "PhoneNumErrorTipText_TT", Text = "Invalid number", TextValueArray = "" },
["01_07_SittingBindChangeLayerVerifyErrorTipText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "VerifyErrorTipText_TT", Text = "Code error", TextValueArray = "" },
["01_07_SittingBindChangeLayerVertifySendText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "VertifySendText_TT", Text = "Send code", TextValueArray = "" },
["01_07_SittingBindChangeLayerVertifyTimeText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "VertifyTimeText_TT", Text = "Resend in {0}", TextValueArray = "" },
["01_07_SittingBindChangeLayerConfirmText_TT"] = { CsdId = "01_07_SittingBindChangeLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingBindLayerReturnText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingBindLayerTitleText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "TitleText_TT", Text = "Add Phone Number", TextValueArray = "" },
["01_07_SittingBindLayerContentText_1_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "ContentText_1_TT", Text = "Enter phone number", TextValueArray = "" },
["01_07_SittingBindLayerContentText_2_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "ContentText_2_TT", Text = "Enter verification code", TextValueArray = "" },
["01_07_SittingBindLayerPhoneNumErrorTipText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "PhoneNumErrorTipText_TT", Text = "Invalid number", TextValueArray = "" },
["01_07_SittingBindLayerVerifyErrorTipText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "VerifyErrorTipText_TT", Text = "Code error", TextValueArray = "" },
["01_07_SittingBindLayerVertifySendText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "VertifySendText_TT", Text = "Send code", TextValueArray = "" },
["01_07_SittingBindLayerVertifyTimeText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "VertifyTimeText_TT", Text = "Resend in {0}", TextValueArray = "" },
["01_07_SittingBindLayerConfirmText_TT"] = { CsdId = "01_07_SittingBindLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingChangePopUpTipTitleText_TT"] = { CsdId = "01_07_SittingChangePopUp", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["01_07_SittingChangePopUpTipContentText_TT"] = { CsdId = "01_07_SittingChangePopUp", NodeId = "TipContentText_TT", Text = "Are you you want to change your phone number?", TextValueArray = "" },
["01_07_SittingChangePopUpConfirmText_TT"] = { CsdId = "01_07_SittingChangePopUp", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingChangePopUpCancelText_TT"] = { CsdId = "01_07_SittingChangePopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_07_SIttingLanguagePopUpTipTitleText_TT"] = { CsdId = "01_07_SIttingLanguagePopUp", NodeId = "TipTitleText_TT", Text = "Language settings", TextValueArray = "" },
["01_07_SittingLayerUserSittingText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "UserSittingText_TT", Text = "User settings", TextValueArray = "" },
["01_07_SittingLayerPasswordText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "PasswordText_TT", Text = "Account settings", TextValueArray = "" },
["01_07_SittingLayerSoundSittingText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "SoundSittingText_TT", Text = "Sound settings", TextValueArray = "" },
["01_07_SittingLayerSoundEffectText_1_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "SoundEffectText_1_TT", Text = "Music", TextValueArray = "" },
["01_07_SittingLayerSoundEffectText_2_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "SoundEffectText_2_TT", Text = "SFX", TextValueArray = "" },
["01_07_SittingLayerSoundEffectText_3_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "SoundEffectText_3_TT", Text = "Voice", TextValueArray = "" },
["01_07_SittingLayerShockText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "ShockText_TT", Text = "Vibrate", TextValueArray = "" },
["01_07_SittingLayerTurnOffText_1_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "TurnOffText_1_TT", Text = "Off", TextValueArray = "" },
["01_07_SittingLayerTurnOnText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "TurnOnText_TT", Text = "On", TextValueArray = "" },
["01_07_SittingLayerTurnOnText_1_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "TurnOnText_1_TT", Text = "On", TextValueArray = "" },
["01_07_SittingLayerTurnOffText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "TurnOffText_TT", Text = "Off", TextValueArray = "" },
["01_07_SittingLayerUserCenterText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "UserCenterText_TT", Text = "User center", TextValueArray = "" },
["01_07_SittingLayerHelpText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "HelpText_TT", Text = "Game rules", TextValueArray = "" },
["01_07_SittingLayerCustomServiceText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "CustomServiceText_TT", Text = "Customer service", TextValueArray = "" },
["01_07_SittingLayerFollowUsText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "FollowUsText_TT", Text = "Follow us", TextValueArray = "" },
["01_07_SittingLayerAgreementText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "AgreementText_TT", Text = "Terms of Service", TextValueArray = "" },
["01_07_SittingLayerPrivacyText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "PrivacyText_TT", Text = "Privacy Policy", TextValueArray = "" },
["01_07_SittingLayerSittingText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "SittingText_TT", Text = "Settings", TextValueArray = "" },
["01_07_SittingLayerLogoutText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "LogoutText_TT", Text = "Log out", TextValueArray = "" },
["01_07_SittingLayerReturnText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingLayerLanguageText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "LanguageText_TT", Text = "Language settings", TextValueArray = "" },
["01_07_SittingModifyAccountLayerAccountTextField_TNT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "AccountTextField_TNT", Text = "4-12 alphanumeric characters or underscores", TextValueArray = "" },
["01_07_SittingModifyAccountLayerPasswordTextField_TNT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "PasswordTextField_TNT", Text = "4-12 alphanumeric characters", TextValueArray = "" },
["01_07_SittingLayerFacebookRelieveText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "FacebookRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingLayerGoogleRelieveText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "GoogleRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingLayerAppleRelieveText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "AppleRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingLayerWeChatRelieveText_TT"] = { CsdId = "01_07_SittingLayer", NodeId = "WeChatRelieveText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingModifyAccountLayerReturnText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingModifyAccountLayerTitleText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "TitleText_TT", Text = "Register Account", TextValueArray = "" },
["01_07_SittingModifyAccountLayerContentText_1_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "ContentText_1_TT", Text = "Username", TextValueArray = "" },
["01_07_SittingModifyAccountLayerContentText_2_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "ContentText_2_TT", Text = "Password", TextValueArray = "" },
["01_07_SittingModifyAccountLayerAccountErrorTipText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "AccountErrorTipText_TT", Text = "Username is unavailable", TextValueArray = "" },
["01_07_SittingModifyAccountLayerConfirmText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingModifyAccountLayerContentText_3_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "ContentText_3_TT", Text = "Repeat password", TextValueArray = "" },
["01_07_SittingModifyAccountLayerPasswordErrorTipText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "PasswordErrorTipText_TT", Text = "Password has to contain letters", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerAccountTextField_TNT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "AccountTextField_TNT", Text = "4-12 alphanumeric characters or underscores", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerPasswordTextField_TNT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "PasswordTextField_TNT", Text = "4-12 alphanumeric characters", TextValueArray = "" },
["01_07_SittingModifyAccountLayerPasswaordConfirmErrorTipText_TT"] = { CsdId = "01_07_SittingModifyAccountLayer", NodeId = "PasswaordConfirmErrorTipText_TT", Text = "Passwords do not match", TextValueArray = "" },
["01_07_SittingModifyAccountPopUpTipTitleText_TT"] = { CsdId = "01_07_SittingModifyAccountPopUp", NodeId = "TipTitleText_TT", Text = "Register Account", TextValueArray = "" },
["01_07_SittingModifyAccountPopUpTipContentText_TT"] = { CsdId = "01_07_SittingModifyAccountPopUp", NodeId = "TipContentText_TT", Text = "", TextValueArray = "" },
["01_07_SittingModifyAccountPopUpConfirmText_TT"] = { CsdId = "01_07_SittingModifyAccountPopUp", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingModifyAccountPopUpCancelText_TT"] = { CsdId = "01_07_SittingModifyAccountPopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerReturnText_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerTitleText_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "TitleText_TT", Text = "Change Password", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerContentText_1_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "ContentText_1_TT", Text = "Enter current password", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerAccountErrorTipText_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "AccountErrorTipText_TT", Text = "Incorrect password", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerConfirmText_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerTipText_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "TipText_TT", Text = "Password format error", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerContentText_2_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "ContentText_2_TT", Text = "Enter new password", TextValueArray = "" },
["01_07_SittingModifyPasswordLayerContentText_3_TT"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "ContentText_3_TT", Text = "Repeat new password", TextValueArray = "" },
["01_07_SittingModifyPasswordLayer01_07_SittingModifyPasswordLayer"] = { CsdId = "01_07_SittingModifyPasswordLayer", NodeId = "01_07_SittingModifyPasswordLayer", Text = "Passwords do not match", TextValueArray = "" },
["01_07_SittingPhoneNumAreaLayerReturnText_TT"] = { CsdId = "01_07_SittingPhoneNumAreaLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingPhoneNumAreaLayerTitleText_TT"] = { CsdId = "01_07_SittingPhoneNumAreaLayer", NodeId = "TitleText_TT", Text = "Select Area Code", TextValueArray = "" },
["01_07_SittingSignOutAgreementLayerTitleText_TT"] = { CsdId = "01_07_SittingSignOutAgreementLayer", NodeId = "TitleText_TT", Text = "Account Cancellation Agreement", TextValueArray = "" },
["01_10_MailCheckLayerReceivedText_TT"] = { CsdId = "01_10_MailCheckLayer", NodeId = "ReceivedText_TT", Text = "Complete", TextValueArray = "" },
["01_07_SittingSignOutAgreementLayerConfirmText_TT"] = { CsdId = "01_07_SittingSignOutAgreementLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_07_SittingSignOutAgreementLayerCancelText_TT"] = { CsdId = "01_07_SittingSignOutAgreementLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_07_SittingSignOutAgreementLayerAgreeTipText_TT"] = { CsdId = "01_07_SittingSignOutAgreementLayer", NodeId = "AgreeTipText_TT", Text = "To proceed review the agreement and press confirm", TextValueArray = "" },
["01_07_SittingUnbindPopUpTipTitleText_TT"] = { CsdId = "01_07_SittingUnbindPopUp", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["01_07_SittingUnbindPopUpTipContentText_1_TT"] = { CsdId = "01_07_SittingUnbindPopUp", NodeId = "TipContentText_1_TT", Text = "Are you sure you want to unlink {0}?", TextValueArray = "" },
["01_07_SittingUnbindPopUpTipContentText_2_TT"] = { CsdId = "01_07_SittingUnbindPopUp", NodeId = "TipContentText_2_TT", Text = "Once you unlink your {0} account, you can no longer use it to log in.", TextValueArray = "" },
["01_07_SittingUnbindPopUpConfirmText_TT"] = { CsdId = "01_07_SittingUnbindPopUp", NodeId = "ConfirmText_TT", Text = "Unlink", TextValueArray = "" },
["01_07_SittingUnbindPopUpCancelText_TT"] = { CsdId = "01_07_SittingUnbindPopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_10_DeleteConfirmLayerCancelText_TT"] = { CsdId = "01_10_DeleteConfirmLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_10_DeleteConfirmLayerConfirmText_TT"] = { CsdId = "01_10_DeleteConfirmLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_10_DeleteConfirmLayerDeleteConfirmText_1_TT"] = { CsdId = "01_10_DeleteConfirmLayer", NodeId = "DeleteConfirmText_1_TT", Text = "Are you sure you want to delete all read messages?", TextValueArray = "" },
["01_10_DeleteConfirmLayerDeleteConfirmText_2_TT"] = { CsdId = "01_10_DeleteConfirmLayer", NodeId = "DeleteConfirmText_2_TT", Text = "Unable to recover after deletion", TextValueArray = "" },
["01_10_MailBoxLayerDeleteText_TT"] = { CsdId = "01_10_MailBoxLayer", NodeId = "DeleteText_TT", Text = "Delete read", TextValueArray = "" },
["01_10_MailBoxLayerReceiveText_TT"] = { CsdId = "01_10_MailBoxLayer", NodeId = "ReceiveText_TT", Text = "Claim all", TextValueArray = "" },
["01_10_MailBoxLayerReturnText_TT"] = { CsdId = "01_10_MailBoxLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_10_MailBoxLayerNothingImageText_TT"] = { CsdId = "01_10_MailBoxLayer", NodeId = "NothingImageText_TT", Text = "No content", TextValueArray = "" },
["01_10_MailCheckLayerReceiveText_TT"] = { CsdId = "01_10_MailCheckLayer", NodeId = "ReceiveText_TT", Text = "Claim", TextValueArray = "" },
["01_10_MailCheckLayerConfirmText_TT"] = { CsdId = "01_10_MailCheckLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_10_MailLayerMailTitleText_TT"] = { CsdId = "01_10_MailLayer", NodeId = "MailTitleText_TT", Text = "{0}/{1} Patch Notes", TextValueArray = "" },
["01_10_MailLayerExpirationTimeText_TT"] = { CsdId = "01_10_MailLayer", NodeId = "ExpirationTimeText_TT", Text = "Expires in {0}d", TextValueArray = "" },
["01_10_MailLayerReceiveTimeText_TT"] = { CsdId = "01_10_MailLayer", NodeId = "ReceiveTimeText_TT", Text = "{0}d ago", TextValueArray = "" },
["01_11_ActivitiesCellTimeText_TT"] = { CsdId = "01_11_ActivitiesCell", NodeId = "TimeText_TT", Text = "Ends in {0}d {0}h", TextValueArray = "" },
["01_11_ActivitiesLayerActivityText_TT"] = { CsdId = "01_11_ActivitiesLayer", NodeId = "ActivityText_TT", Text = "Events", TextValueArray = "" },
["01_11_ActivitiesLayerNoticeText_TT"] = { CsdId = "01_11_ActivitiesLayer", NodeId = "NoticeText_TT", Text = "Announcements", TextValueArray = "" },
["01_11_ActivitiesNoticePopUpTitleText_TT"] = { CsdId = "01_11_ActivitiesNoticePopUp", NodeId = "TitleText_TT", Text = "Announcements", TextValueArray = "" },
["01_11_ActivitiesNoticePopUpCloseText_TT"] = { CsdId = "01_11_ActivitiesNoticePopUp", NodeId = "CloseText_TT", Text = "Close", TextValueArray = "" },
["01_16_NoviceGuideLayerNoviceGuideText_1_TT"] = { CsdId = "01_16_NoviceGuideLayer", NodeId = "NoviceGuideText_1_TT", Text = "Welcome to Let\'s roll, the hottest dice game around.", TextValueArray = "" },
["01_16_NoviceGuideLayerNoviceGuideText_2_TT"] = { CsdId = "01_16_NoviceGuideLayer", NodeId = "NoviceGuideText_2_TT", Text = "Let me show you how it's done.", TextValueArray = "" },
["01_16_NoviceGuideLayerContinueText_TT"] = { CsdId = "01_16_NoviceGuideLayer", NodeId = "ContinueText_TT", Text = "Press to continue", TextValueArray = "" },
["01_16_NoviceStartGuideLayerNoviceGuideText_1_TT"] = { CsdId = "01_16_NoviceStartGuideLayer", NodeId = "NoviceGuideText_1_TT", Text = "Press to the Bluff button to start the game.", TextValueArray = "" },
["01_18_ReliefLayerReliefButtonText_TT"] = { CsdId = "01_18_ReliefLayer", NodeId = "ReliefButtonText_TT", Text = "Claim {0} gold", TextValueArray = "" },
["01_18_ReliefLayerReliefText_1_TT"] = { CsdId = "01_18_ReliefLayer", NodeId = "ReliefText_1_TT", Text = "Here's a gift!", TextValueArray = "" },
["01_18_ReliefLayerReliefText_2_TT"] = { CsdId = "01_18_ReliefLayer", NodeId = "ReliefText_2_TT", Text = "Today's free gold:  {0}/{1} times", TextValueArray = "" },
["02_01_BoasPlayerListCellStateText_1_TT"] = { CsdId = "02_01_BoasPlayerListCell", NodeId = "StateText_1_TT", Text = "In game", TextValueArray = "" },
["02_01_BoasPlayerListCellStateText_2_TT"] = { CsdId = "02_01_BoasPlayerListCell", NodeId = "StateText_2_TT", Text = "Spectating", TextValueArray = "" },
["02_01_BoastChatPopUpSendText_TT"] = { CsdId = "02_01_BoastChatPopUp", NodeId = "SendText_TT", Text = "Send", TextValueArray = "" },
["02_01_BoastChatPopUpChannelTitleText_TT"] = { CsdId = "02_01_BoastChatPopUp", NodeId = "ChannelTitleText_TT", Text = "Chat", TextValueArray = "" },
["02_01_BoastHangUpPopUpContentText_1_TT"] = { CsdId = "02_01_BoastHangUpPopUp", NodeId = "ContentText_1_TT", Text = "You still there? No sleeping on the job", TextValueArray = "" },
["02_01_BoastLayerGamingReturnText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "GamingReturnText_TT", Text = "Exit game", TextValueArray = "" },
["02_01_GuessingLayerStakeText_2_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "StakeText_2_TT", Text = "× {0} bet", TextValueArray = "" },
["02_01_BoastLayerBottomInjectionText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "BottomInjectionText_TT", Text = "Current call", TextValueArray = "" },
["02_01_BoastLayerBottomInjectionText_1_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "BottomInjectionText_1_TT", Text = "×", TextValueArray = "" },
["02_01_BoastLayerBottomInjectionText_2_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "BottomInjectionText_2_TT", Text = "Bet", TextValueArray = "" },
["02_01_BoastLayerText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "Text_TT", Text = "CALL", TextValueArray = "" },
["02_01_BoastLayerChannelTitleText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "ChannelTitleText_TT", Text = "Chat", TextValueArray = "" },
["02_01_BoastLayerSendText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "SendText_TT", Text = "Send", TextValueArray = "" },
["02_01_BoastLayerGamingWatchText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "GamingWatchText_TT", Text = "Spectate", TextValueArray = "" },
["02_01_BoastLayerStateCancelText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "StateCancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_01_BoastLayerPointText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "PointText_TT", Text = "×", TextValueArray = "" },
["02_01_BoastLayerWatchStateTipText_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "WatchStateTipText_TT", Text = "Spectating", TextValueArray = "" },
["02_01_BoastLayerVerticesText_0_TT"] = { CsdId = "02_01_BoastLayer", NodeId = "VerticesText_0_TT", Text = "×", TextValueArray = "" },
["02_01_BoastMagicEmojiPopUpMagicEmojiText_TT"] = { CsdId = "02_01_BoastMagicEmojiPopUp", NodeId = "MagicEmojiText_TT", Text = "Animated emotes", TextValueArray = "" },
["02_01_BoastMagicEmojiPopUpAddFriendText_TT"] = { CsdId = "02_01_BoastMagicEmojiPopUp", NodeId = "AddFriendText_TT", Text = "Add", TextValueArray = "" },
["02_01_BoastMagicEmojiPopUpCancelText_TT"] = { CsdId = "02_01_BoastMagicEmojiPopUp", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["03_01_GoldConfirmLayerFailText_TT"] = { CsdId = "03_01_GoldConfirmLayer", NodeId = "FailText_TT", Text = "Not enough {0}. Please top up first.", TextValueArray = "" },
["02_01_BoastMagicEmojiPopUpChatText_1_TT"] = { CsdId = "02_01_BoastMagicEmojiPopUp", NodeId = "ChatText_1_TT", Text = "Chat", TextValueArray = "" },
["02_01_BoastResultPopUpResultText_1_TT"] = { CsdId = "02_01_BoastResultPopUp", NodeId = "ResultText_1_TT", Text = "Total", TextValueArray = "" },
["02_01_BoastResultPopUpResultText_2_TT"] = { CsdId = "02_01_BoastResultPopUp", NodeId = "ResultText_2_TT", Text = "×", TextValueArray = "" },
["02_01_DiceCupLayerSitText_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "SitText_TT", Text = "Join", TextValueArray = "" },
["02_01_DiceCupLayerVerticesText_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "VerticesText_TT", Text = "×", TextValueArray = "" },
["02_01_DiceCupLayerVerticesText_1_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "VerticesText_1_TT", Text = "×", TextValueArray = "" },
["02_01_DiceCupLayerResultText_1"] = { CsdId = "02_01_DiceCupLayer", NodeId = "ResultText_1", Text = "Panther", TextValueArray = "" },
["02_01_DiceCupLayerResultText_2"] = { CsdId = "02_01_DiceCupLayer", NodeId = "ResultText_2", Text = "Straight", TextValueArray = "" },
["02_01_GuessingLayerEnoughText_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "EnoughText_TT", Text = "TRUE", TextValueArray = "" },
["02_01_GuessingLayerNotEnoughText_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "NotEnoughText_TT", Text = "BLUFF", TextValueArray = "" },
["02_01_GuessingLayerStakeText_1_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "StakeText_1_TT", Text = "Pick a side and bet {0} gold", TextValueArray = "" },
["02_01_GuessingLayerTimeText_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "TimeText_TT", Text = "Bet & Win ends in {0}s", TextValueArray = "" },
["02_01_GuessingLayerVerticesText_TT"] = { CsdId = "02_01_GuessingLayer", NodeId = "VerticesText_TT", Text = "×", TextValueArray = "" },
["02_01_MatchingLayerTimeText"] = { CsdId = "02_01_MatchingLayer", NodeId = "TimeText", Text = "Matchmaking: {0}s", TextValueArray = "" },
["02_01_MatchingLayerTimeText_TT"] = { CsdId = "02_01_MatchingLayer", NodeId = "TimeText_TT", Text = "Now matchmaking - {0}s", TextValueArray = "" },
["02_01_ReplaceBottomInjectionText_1_TT"] = { CsdId = "02_01_ReplaceBottomInjection", NodeId = "Text_1_TT", Text = " wants to raise", TextValueArray = "" },
["02_01_ReplaceBottomInjectionText_2_TT"] = { CsdId = "02_01_ReplaceBottomInjection", NodeId = "Text_2_TT", Text = "the bet to", TextValueArray = "" },
["02_01_ReplaceBottomInjectionAgreeText_TT"] = { CsdId = "02_01_ReplaceBottomInjection", NodeId = "AgreeText_TT", Text = "Accept", TextValueArray = "" },
["02_01_ReplaceBottomInjectionRefuseText_TT"] = { CsdId = "02_01_ReplaceBottomInjection", NodeId = "RefuseText_TT", Text = "Decline", TextValueArray = "" },
["02_01_ReplaceBottomInjectionFailPromotionSuccess_TT"] = { CsdId = "02_01_ReplaceBottomInjectionFail", NodeId = "PromotionSuccess_TT", Text = "Failed to raise bet", TextValueArray = "" },
["02_01_ReplaceBottomInjectionSuccessPromotionSuccess_TT"] = { CsdId = "02_01_ReplaceBottomInjectionSuccess", NodeId = "PromotionSuccess_TT", Text = "Bet raised to ", TextValueArray = "" },
["02_01_ReplaceBottomLayerStakeGoldText_TT"] = { CsdId = "02_01_ReplaceBottomLayer", NodeId = "StakeGoldText_TT", Text = "Raise the bet to", TextValueArray = "" },
["02_01_ReplaceBottomLayerStakeGoldButtonText_TT"] = { CsdId = "02_01_ReplaceBottomLayer", NodeId = "StakeGoldButtonText_TT", Text = "Later maybe", TextValueArray = "" },
["02_01_ReplaceBottomLayerStakeGoldButtonText_1_TT"] = { CsdId = "02_01_ReplaceBottomLayer", NodeId = "StakeGoldButtonText_1_TT", Text = "Yes", TextValueArray = "" },
["03_01_DiceBoxLayerPossessText_TT"] = { CsdId = "03_01_DiceBoxLayer", NodeId = "PossessText_TT", Text = "Owned", TextValueArray = "" },
["03_01_GoldConfirmLayerConfirmText_TT"] = { CsdId = "03_01_GoldConfirmLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["03_01_GoldConfirmLayerCancelText_TT"] = { CsdId = "03_01_GoldConfirmLayer", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["03_01_RechargeLayerDoubleText_TT"] = { CsdId = "03_01_RechargeLayer", NodeId = "DoubleText_TT", Text = "200% Value", TextValueArray = "" },
["03_01_StoreLayerDiamondStoreText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "DiamondStoreText_TT", Text = "Gems", TextValueArray = "" },
["03_01_StoreLayerGoldStoreText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "GoldStoreText_TT", Text = "Gold", TextValueArray = "" },
["03_01_StoreLayerReturnText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["03_01_StoreLayerRewardText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "RewardText_TT", Text = "Level up to get these rewards", TextValueArray = "" },
["03_01_StoreLayerVipLevelText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "VipLevelText_TT", Text = "Top up {0}/{1} gems to level up", TextValueArray = "" },
["03_01_StoreLayerVipLevelText_1_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "VipLevelText_1_TT", Text = "You've reached max level", TextValueArray = "" },
["03_01_StoreLayerDiceBoxStoreText_TT"] = { CsdId = "03_01_StoreLayer", NodeId = "DiceBoxStoreText_TT", Text = "Skins", TextValueArray = "" },
["03_01_SuccessLayerConfirmText_TT"] = { CsdId = "03_01_SuccessLayer", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["03_01_SuccessLayerSuccessText_TT"] = { CsdId = "03_01_SuccessLayer", NodeId = "SuccessText_TT", Text = "Purchase Complete", TextValueArray = "" },
["03_04_InvitationCheckClickText_1_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "ClickText_1_TT", Text = "Clicks", TextValueArray = "" },
["03_04_InvitationCheckClickText_2_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "ClickText_2_TT", Text = "Total {0} gold", TextValueArray = "" },
["03_04_InvitationCheckRegisterText_1_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RegisterText_1_TT", Text = "Sign-ups", TextValueArray = "" },
["03_04_InvitationCheckRegisterText_2_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RegisterText_2_TT", Text = "Total {0} gold", TextValueArray = "" },
["03_04_InvitationCheckRechargeText_1_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RechargeText_1_TT", Text = "Top-ups", TextValueArray = "" },
["03_04_InvitationCheckRechargeText_2_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RechargeText_2_TT", Text = "Total {0} gems", TextValueArray = "" },
["03_04_InvitationCheckClickTaskText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "ClickTaskText_TT", Text = "When your referral link gets clicks, you earn {0}. Claimed {1}/{2} times today.", TextValueArray = "" },
["03_04_InvitationCheckRegisterTaskText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RegisterTaskText_TT", Text = "When your referrals register, you earn {0}. Claimed {1}/{2} times today.", TextValueArray = "" },
["03_04_InvitationCheckRechargeTaskText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "RechargeTaskText_TT", Text = "When your referrals top up, you receive {0}% reward for each top-up.", TextValueArray = "" },
["03_04_InvitationCheckReturnText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["03_04_InvitationCheckTipTitleText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["03_04_InvitationCheckContentText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "ContentText_TT", Text = "Link copied to clipboard. You can now share it with your friends", TextValueArray = "" },
["03_04_InvitationCheckInvitationTipText_TT"] = { CsdId = "03_04_InvitationCheck", NodeId = "InvitationTipText_TT", Text = "No content", TextValueArray = "" },
["03_04_InvitationCheckCellTimeText_TT"] = { CsdId = "03_04_InvitationCheckCell", NodeId = "TimeText_TT", Text = "{0}h ago", TextValueArray = "" },
["03_04_InvitationCheckCellClickText_TT"] = { CsdId = "03_04_InvitationCheckCell", NodeId = "ClickText_TT", Text = "Referral link click", TextValueArray = "" },
["03_04_InvitationPopUpRuleText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RuleText_TT", Text = "Rules", TextValueArray = "" },
["03_04_InvitationPopUpInvitationText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "InvitationText_TT", Text = "Reach goals and win extra rewards", TextValueArray = "" },
["03_04_InvitationPopUpRewardText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RewardText_TT", Text = "Available", TextValueArray = "" },
["03_04_InvitationPopUpReceiveText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "ReceiveText_TT", Text = "Claim", TextValueArray = "" },
["03_04_InvitationPopUpClickText_1_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "ClickText_1_TT", Text = "Clicks", TextValueArray = "" },
["03_04_InvitationPopUpClickText_2_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "ClickText_2_TT", Text = "Total {0} gold", TextValueArray = "" },
["03_04_InvitationPopUpRegisterText_1_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RegisterText_1_TT", Text = "Sign-ups", TextValueArray = "" },
["03_04_InvitationPopUpRegisterText_2_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RegisterText_2_TT", Text = "Total {0} gold", TextValueArray = "" },
["03_04_InvitationPopUpRechargeText_1_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RechargeText_1_TT", Text = "Top-ups", TextValueArray = "" },
["03_04_InvitationPopUpRechargeText_2_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RechargeText_2_TT", Text = "Total {0} gems", TextValueArray = "" },
["03_04_InvitationPopUpClickTaskText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "ClickTaskText_TT", Text = "When your referral link gets clicks, you earn {0}. Claimed {1}/{2} times today.", TextValueArray = "" },
["03_04_InvitationPopUpRegisterTaskText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RegisterTaskText_TT", Text = "When your referrals register, you earn {0}. Claimed {1}/{2} times today.", TextValueArray = "" },
["03_04_InvitationPopUpRechargeTaskText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "RechargeTaskText_TT", Text = "When your referrals top up, you receive {0}% reward for each top-up.", TextValueArray = "" },
["03_04_InvitationPopUpTimeText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "TimeText_TT", Text = "{0}h ago", TextValueArray = "" },
["03_04_InvitationPopUpClickText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "ClickText_TT", Text = "Referral link click", TextValueArray = "" },
["03_04_InvitationPopUpMoreText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "MoreText_TT", Text = "Expand list", TextValueArray = "" },
["03_04_InvitationPopUpInvitationButtonText_TT"] = { CsdId = "03_04_InvitationPopUp", NodeId = "InvitationButtonText_TT", Text = "Invite friends", TextValueArray = "" },
["03_04_InvitationRulesPopUpTitleText_TT"] = { CsdId = "03_04_InvitationRulesPopUp", NodeId = "TitleText_TT", Text = "Rules", TextValueArray = "" },
["03_04_InvitationSharePopUpTipTitleText_TT"] = { CsdId = "03_04_InvitationSharePopUp", NodeId = "TipTitleText_TT", Text = "Notice", TextValueArray = "" },
["03_04_InvitationSharePopUpContentText_TT"] = { CsdId = "03_04_InvitationSharePopUp", NodeId = "ContentText_TT", Text = "Link copied to clipboard. You can now share it with your friends", TextValueArray = "" },
["03_04_InvitationTaskCellClickText_TT"] = { CsdId = "03_04_InvitationTaskCell", NodeId = "ClickText_TT", Text = "Clicks", TextValueArray = "" },
["04_02_FriendsPopUpAddTextField_TNT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "AddTextField_TNT", Text = "Nickname or player ID", TextValueArray = "" },
["03_04_InvitationTaskCellRegisterText_TT"] = { CsdId = "03_04_InvitationTaskCell", NodeId = "RegisterText_TT", Text = "Sign-ups", TextValueArray = "" },
["03_04_InvitationTaskCellRechargeText_TT"] = { CsdId = "03_04_InvitationTaskCell", NodeId = "RechargeText_TT", Text = "Top-ups", TextValueArray = "" },
["03_08_NewWelfareNovicePopUpResText_TT"] = { CsdId = "03_08_NewWelfareNovicePopUp", NodeId = "ResText_TT", Text = "Contains", TextValueArray = "" },
["03_10_OperateGiftBagNovicePopUpTitleText_TT"] = { CsdId = "03_10_OperateGiftBagNovicePopUp", NodeId = "TitleText_TT", Text = "Event Information", TextValueArray = "" },
["03_10_OperateGiftBagNovicePopUpGiftBagText_TT"] = { CsdId = "03_10_OperateGiftBagNovicePopUp", NodeId = "GiftBagText_TT", Text = "Contains", TextValueArray = "" },
["03_10_OperateGiftBagNovicePopUpContentText_1_TT"] = { CsdId = "03_10_OperateGiftBagNovicePopUp", NodeId = "ContentText_1_TT", Text = "Name: New Player Loot box", TextValueArray = "" },
["03_10_OperateGiftBagNovicePopUpContentText_2_TT"] = { CsdId = "03_10_OperateGiftBagNovicePopUp", NodeId = "ContentText_2_TT", Text = "Duration: Unlimited", TextValueArray = "" },
["03_10_OperateGiftBagNovicePopUpContentText_3_TT"] = { CsdId = "03_10_OperateGiftBagNovicePopUp", NodeId = "ContentText_3_TT", Text = "Description: New players receive 100,000 gold and a rookie dice skin, can be only purchased once", TextValueArray = "" },
["04_01_ChatChannelCellTimeText_TT"] = { CsdId = "04_01_ChatChannelCell", NodeId = "TimeText_TT", Text = "{0}min ago", TextValueArray = "" },
["04_01_ChatLayerReturnText_TT"] = { CsdId = "04_01_ChatLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["04_01_ChatLayerTitleText_TT"] = { CsdId = "04_01_ChatLayer", NodeId = "TitleText_TT", Text = "Chat", TextValueArray = "" },
["04_01_ChatLayerSendText_TT"] = { CsdId = "04_01_ChatLayer", NodeId = "SendText_TT", Text = "Send", TextValueArray = "" },
["04_02_FriendsCellAgreeText_1_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "AgreeText_1_TT", Text = "Accept", TextValueArray = "" },
["04_02_FriendsCellRefuseText_1_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "RefuseText_1_TT", Text = "Decline", TextValueArray = "" },
["04_02_FriendsCellAddText_1_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "AddText_1_TT", Text = "Add", TextValueArray = "" },
["04_02_FriendsCellRemoveText_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "RemoveText_TT", Text = "Remove", TextValueArray = "" },
["04_02_FriendsCellCancelText_1_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "CancelText_1_TT", Text = "Cancel", TextValueArray = "" },
["04_02_FriendsCellFriendsAlreadyText_TT"] = { CsdId = "04_02_FriendsCell", NodeId = "FriendsAlreadyText_TT", Text = "Already added as a friend", TextValueArray = "" },
["04_02_FriendsPopUpListText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "ListText_TT", Text = "Friends", TextValueArray = "" },
["04_02_FriendsPopUpAddText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "AddText_TT", Text = "Add", TextValueArray = "" },
["04_02_FriendsPopUpApplyText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "ApplyText_TT", Text = "Requests", TextValueArray = "" },
["04_02_FriendsPopUpBalckText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "BalckText_TT", Text = "Blocked", TextValueArray = "" },
["04_02_FriendsPopUpListText_1_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "ListText_1_TT", Text = "Friends", TextValueArray = "" },
["04_02_FriendsPopUpRefuseText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "RefuseText_TT", Text = "Decline all", TextValueArray = "" },
["04_02_FriendsPopUpAgreeText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "AgreeText_TT", Text = "Accept all", TextValueArray = "" },
["04_02_FriendsPopUpBlackText_1_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "BlackText_1_TT", Text = "Blocked", TextValueArray = "" },
["04_02_FriendsPopUpEmptyListText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "EmptyListText_TT", Text = "Add players to play together", TextValueArray = "" },
["04_02_FriendsPopUpEmptyAddText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "EmptyAddText_TT", Text = "No matching player found", TextValueArray = "" },
["04_02_FriendsPopUpEmptyApplyText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "EmptyApplyText_TT", Text = "Add players to play together", TextValueArray = "" },
["04_02_FriendsPopUpEmptyBlackText_TT"] = { CsdId = "04_02_FriendsPopUp", NodeId = "EmptyBlackText_TT", Text = "No blocked players", TextValueArray = "" },
["02_02_BankerGuessSizeLayerBankerText_TT"] = { CsdId = "02_02_BankerGuessSizeLayer", NodeId = "BankerText_TT", Text = "Dealer", TextValueArray = "" },
["02_02_BankerGuessSizeLayerResidueBankerGold_TT"] = { CsdId = "02_02_BankerGuessSizeLayer", NodeId = "ResidueBankerGold_TT", Text = "Balance", TextValueArray = "" },
["02_02_BankerGuessSizeLayerOutBankerText_TT"] = { CsdId = "02_02_BankerGuessSizeLayer", NodeId = "OutBankerText_TT", Text = "Step down", TextValueArray = "" },
["02_02_GuessSizeLayerAnteGoldText_TT"] = { CsdId = "02_02_GuessSizeLayer", NodeId = "AnteGoldText_TT", Text = "Deposit amount", TextValueArray = "" },
["02_02_GuessSizeLayerBankerText_TT"] = { CsdId = "02_02_GuessSizeLayer", NodeId = "BankerText_TT", Text = "Dealer", TextValueArray = "" },
["02_02_GuessSizeLayerRobBankerGold_TT"] = { CsdId = "02_02_GuessSizeLayer", NodeId = "RobBankerGold_TT", Text = "Snatch cost", TextValueArray = "" },
["02_02_GuessSizeLayerRobBankerText_TT"] = { CsdId = "02_02_GuessSizeLayer", NodeId = "RobBankerText_TT", Text = "Snatch", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1TitleText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1ContentText_1_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "ContentText_1_TT", Text = "Deposit amount is insufficient", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1ContentText_1_1_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "ContentText_1_1_TT", Text = "Game round is over", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1ContentText_1_2_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "ContentText_1_2_TT", Text = "Your dealer position has been snatched!", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1ContentText_2_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "ContentText_2_TT", Text = "You automatically stepped down as dealer", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_1ConfirmText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Got it", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_2TitleText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_2", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_2ContentText_1_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_2", NodeId = "ContentText_1_TT", Text = "Deposit 30M gold to become dealer", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_2ContentText_2_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_2", NodeId = "ContentText_2_TT", Text = "Snatch rate:", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_2ConfirmText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_2", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_2CancelText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_2", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_3TitleText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_3", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_3ContentText_2_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_3", NodeId = "ContentText_2_TT", Text = "Are you sure to step down as a dealer?", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_3ConfirmText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_3", NodeId = "ConfirmText_TT", Text = "Quit", TextValueArray = "" },
["02_02_GuessSizeMiniTipPopUp_3CancelText_TT"] = { CsdId = "02_02_GuessSizeMiniTipPopUp_3", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_02_RodGoldRankingLayerSumUpGoldText_TT"] = { CsdId = "02_02_RodGoldRankingLayer", NodeId = "SumUpGoldText_TT", Text = "Total plunder ", TextValueArray = "" },
["02_02_RodGoldRankingLayerSumUpEggText_TT"] = { CsdId = "02_02_RodGoldRankingLayer", NodeId = "SumUpEggText_TT", Text = "Total eggs: ", TextValueArray = "" },
["02_02_GuessSizeLayerBankerNameText_TT"] = { CsdId = "02_02_GuessSizeLayer", NodeId = "BankerNameText_TT", Text = "No dealer", TextValueArray = "" },
["02_02_MainGuessSizeHintCellMainGuessSizeHintText_1_TT"] = { CsdId = "02_02_MainGuessSizeHintCell", NodeId = "MainGuessSizeHintText_1_TT", Text = "Someone snatched your dealer position in High Low", TextValueArray = "" },
["02_02_MainGuessSizeHintCellMainGuessSizeHintText_2_TT"] = { CsdId = "02_02_MainGuessSizeHintCell", NodeId = "MainGuessSizeHintText_2_TT", Text = "Round complete. You've stepped down as dealer", TextValueArray = "" },
["02_02_MainGuessSizeHintCellMainGuessSizeHintText_3_TT"] = { CsdId = "02_02_MainGuessSizeHintCell", NodeId = "MainGuessSizeHintText_3_TT", Text = "Sic Bo deposit is insufficient and you have automatically stepped down as dealer", TextValueArray = "" },
["01_07_SittingAccountLayerReturnText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["01_07_SittingAccountLayerDeleteAccountText_TT"] = { CsdId = "01_07_SittingAccountLayer", NodeId = "DeleteAccountText_TT", Text = "Cancel account", TextValueArray = "" },
["01_11_ActivitiesLayerReturnText_TT"] = { CsdId = "01_11_ActivitiesLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["02_01_DiceCupLayerWaitingText_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "WaitingText_TT", Text = "Waiting...", TextValueArray = "" },
["02_01_BoastHangUpPopUpTitleText_TT"] = { CsdId = "02_01_BoastHangUpPopUp", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_01_DiceCupLayerResultText_1_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "ResultText_1_TT", Text = "Panther", TextValueArray = "" },
["02_01_DiceCupLayerResultText_2_TT"] = { CsdId = "02_01_DiceCupLayer", NodeId = "ResultText_2_TT", Text = "Straight", TextValueArray = "" },
["02_01_BoasPlayertListPopUpTitleText_TT"] = { CsdId = "02_01_BoasPlayertListPopUp", NodeId = "TitleText_TT", Text = "Room {0}", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1TitleText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1ContentText_1_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "ContentText_1_TT", Text = "Deposit amount is insufficient", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1ContentText_1_1_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "ContentText_1_1_TT", Text = "Dealer time is up", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1ContentText_1_2_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "ContentText_1_2_TT", Text = "Your dealer position has been snatched!", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1ContentText_2_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "ContentText_2_TT", Text = "You automatically stepped down as dealer", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_1ConfirmText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Got it", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_2TitleText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_2", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_2ContentText_2_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_2", NodeId = "ContentText_2_TT", Text = "Are you sure to step down as a dealer?", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_2ConfirmText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_2", NodeId = "ConfirmText_TT", Text = "Quit", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_2CancelText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_2", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_3TitleText_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_3", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_3ConfirmText_1_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_3", NodeId = "ConfirmText_1_TT", Text = "10M", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_3ConfirmText_2_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_3", NodeId = "ConfirmText_2_TT", Text = "30M", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_3ConfirmText_3_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_3", NodeId = "ConfirmText_3_TT", Text = "50M", TextValueArray = "" },
["02_04_DiceBabyMiniTipPopUp_3ContentText_1_TT"] = { CsdId = "02_04_DiceBabyMiniTipPopUp_3", NodeId = "ContentText_1_TT", Text = "Select deposit amount", TextValueArray = "" },
["02_04_MainDiceBabyHintCellMainDiceBabyHintText_1_TT"] = { CsdId = "02_04_MainDiceBabyHintCell", NodeId = "MainDiceBabyHintText_1_TT", Text = "Someone snatched your dealer position in Sic Bo", TextValueArray = "" },
["02_04_MainDiceBabyHintCellMainDiceBabyHintText_2_TT"] = { CsdId = "02_04_MainDiceBabyHintCell", NodeId = "MainDiceBabyHintText_2_TT", Text = "Sic Bo deposit is insufficient and you have automatically stepped down as dealer", TextValueArray = "" },
["02_04_MainDiceBabyHintCellMainDiceBabyHintText_3_TT"] = { CsdId = "02_04_MainDiceBabyHintCell", NodeId = "MainDiceBabyHintText_3_TT", Text = "Time limit as Sic Bo dealer has been reached and you have automatically stepped down as dealer", TextValueArray = "" },
["01_02_MainLayerNotBankerText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "NotBankerText_TT", Text = "No dealer", TextValueArray = "" },
["01_02_MainLayerDiceBabyRuleText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "DiceBabyRuleText_TT", Text = "Roll 1/2/3 dice to win × 2/3/4", TextValueArray = "" },
["01_02_MainLayerBeOpenCardText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "BeOpenCardText_TT", Text = "00:00", TextValueArray = "" },
["03_12_MiniTipPopUpGenderText_1_TT"] = { CsdId = "03_12_MiniTipPopUp", NodeId = "GenderText_1_TT", Text = "Male", TextValueArray = "" },
["03_12_MiniTipPopUpGenderText_2_TT"] = { CsdId = "03_12_MiniTipPopUp", NodeId = "GenderText_2_TT", Text = "Female", TextValueArray = "" },
["03_12_MiniTipPopUpGenderText_3_TT"] = { CsdId = "03_12_MiniTipPopUp", NodeId = "GenderText_3_TT", Text = "Not set", TextValueArray = "" },
["03_12_MiniTipPopUpGenderText_4_TT"] = { CsdId = "03_12_MiniTipPopUp", NodeId = "GenderText_4_TT", Text = "All", TextValueArray = "" },
["03_12_ServiceCellPlayerGenderText_1_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerGenderText_1_TT", Text = "Male", TextValueArray = "" },
["03_12_ServiceCellPlayerGenderText_2_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerGenderText_2_TT", Text = "Female", TextValueArray = "" },
["03_12_ServiceCellPlayerGenderText_3_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerGenderText_3_TT", Text = "-", TextValueArray = "" },
["03_12_ServiceCellPlayerLanguageText_1_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerLanguageText_1_TT", Text = "Simplified Chinese", TextValueArray = "" },
["03_12_ServiceCellPlayerLanguageText_2_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerLanguageText_2_TT", Text = "Traditional Chinese", TextValueArray = "" },
["03_12_ServiceCellPlayerLanguageText_3_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "PlayerLanguageText_3_TT", Text = "English", TextValueArray = "" },
["03_12_ServiceCellGameStateText_1_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "GameStateText_1_TT", Text = "Playing Brag", TextValueArray = "" },
["03_12_ServiceCellGameStateText_2_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "GameStateText_2_TT", Text = "Sic Bo", TextValueArray = "" },
["03_12_ServiceCellGameStateText_3_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "GameStateText_3_TT", Text = "High Low", TextValueArray = "" },
["03_12_ServiceCellGameStateText_4_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "GameStateText_4_TT", Text = "In lobby", TextValueArray = "" },
["03_12_ServiceCellGameStateText_5_TT"] = { CsdId = "03_12_ServiceCell", NodeId = "GameStateText_5_TT", Text = "吹牛私房中", TextValueArray = "" },
["03_12_ServiceLayerLogoutText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "LogoutText_TT", Text = "Total players online:", TextValueArray = "" },
["03_12_ServiceLayerCollectText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "CollectText_TT", Text = "Claim", TextValueArray = "" },
["03_12_ServiceLayerGenderText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "GenderText_TT", Text = "Gender: All", TextValueArray = "" },
["03_12_ServiceLayerGenderText_1_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "GenderText_1_TT", Text = "Gender: Male", TextValueArray = "" },
["03_12_ServiceLayerGenderText_2_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "GenderText_2_TT", Text = "Gender: Female", TextValueArray = "" },
["03_12_ServiceLayerGenderText_3_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "GenderText_3_TT", Text = "Gender: None", TextValueArray = "" },
["03_12_ServiceLayerRegisterText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "RegisterText_TT", Text = "Registered since ", TextValueArray = "" },
["03_12_ServiceLayerRechargeText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "RechargeText_TT", Text = "Top-up amount", TextValueArray = "" },
["03_12_ServiceLayerLanguageText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "LanguageText_TT", Text = "Language: All", TextValueArray = "" },
["03_12_ServiceLayerLanguageText_1_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "LanguageText_1_TT", Text = "Language: Simplified Chinese", TextValueArray = "" },
["03_12_ServiceLayerLanguageText_2_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "LanguageText_2_TT", Text = "Language: Traditional Chinese", TextValueArray = "" },
["03_12_ServiceLayerLanguageText_3_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "LanguageText_3_TT", Text = "Language: English", TextValueArray = "" },
["03_12_ServiceLayerRoomServiceText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "RoomServiceText_TT", Text = "Customer serivce", TextValueArray = "" },
["03_12_ServiceLayerRoomPlayerText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "RoomPlayerText_TT", Text = "Player", TextValueArray = "" },
["03_12_ServiceLayerStateText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "StateText_TT", Text = "Status", TextValueArray = "" },
["03_12_ServiceLayerHomePageText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "HomePageText_TT", Text = "Main page", TextValueArray = "" },
["03_12_ServiceLayerPageUpText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "PageUpText_TT", Text = "Previous page", TextValueArray = "" },
["03_12_ServiceLayerNextPageText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "NextPageText_TT", Text = "Next page", TextValueArray = "" },
["03_12_ServiceLayerTrailerPageText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "TrailerPageText_TT", Text = "Last page", TextValueArray = "" },
["03_12_ServiceLayerExitText_TT"] = { CsdId = "03_12_ServiceLayer", NodeId = "ExitText_TT", Text = "Exit", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_1"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_1", Text = "Gender", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_2"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_2", Text = "Register", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_3"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_3", Text = "Language", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_4"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_4", Text = "Top-ups", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_5"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_5", Text = "Customer service", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_6"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_6", Text = "User", TextValueArray = "" },
["03_12_ServiceLayerHeadlineText_7"] = { CsdId = "03_12_ServiceLayer", NodeId = "HeadlineText_7", Text = "Claim ", TextValueArray = "" },
["03_12_UserDetailsCellPlayerLanguageText_1_TT"] = { CsdId = "03_12_UserDetailsCell", NodeId = "PlayerLanguageText_1_TT", Text = "Language: Chinese (simplified)", TextValueArray = "" },
["03_12_UserDetailsCellPlayerLanguageText_2_TT"] = { CsdId = "03_12_UserDetailsCell", NodeId = "PlayerLanguageText_2_TT", Text = "Language: Chinese (traditional)", TextValueArray = "" },
["03_12_UserDetailsCellPlayerLanguageText_3_TT"] = { CsdId = "03_12_UserDetailsCell", NodeId = "PlayerLanguageText_3_TT", Text = "Language: English", TextValueArray = "" },
["03_12_UserDetailsCellCurrentServiceText_TT"] = { CsdId = "03_12_UserDetailsCell", NodeId = "CurrentServiceText_TT", Text = "Customer service", TextValueArray = "" },
["03_12_UserDetailsCellEnterText_TT"] = { CsdId = "03_12_UserDetailsCell", NodeId = "EnterText_TT", Text = "Enter game", TextValueArray = "" },
["01_16_GuideBigPrizeLayerBigPrizeHintText_TT"] = { CsdId = "01_16_GuideBigPrizeLayer", NodeId = "BigPrizeHintText_TT", Text = "Rewarded on completion", TextValueArray = "" },
["01_16_GuideBoastLayerBottomInjectionText_2_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "BottomInjectionText_2_TT", Text = "Bet", TextValueArray = "" },
["01_16_GuideBoastLayerBottomInjectionText_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "BottomInjectionText_TT", Text = "Current call", TextValueArray = "" },
["01_16_GuideBoastLayerBottomInjectionText_1_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "BottomInjectionText_1_TT", Text = "×", TextValueArray = "" },
["01_16_GuideBoastLayerVerticesText_0_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "VerticesText_0_TT", Text = "×", TextValueArray = "" },
["01_16_GuideBoastLayerText_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "Text_TT", Text = "CALL", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_1_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_1_TT", Text = "Select number of dice", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_2_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_2_TT", Text = "Press to select", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_3_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_3_TT", Text = "Click to select the number of dice", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_4_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_4_TT", Text = "Press to select", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_5_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_5_TT", Text = "Press to select", TextValueArray = "" },
["01_16_GuideBoastLayerGuideText_6_TT"] = { CsdId = "01_16_GuideBoastLayer", NodeId = "GuideText_6_TT", Text = "View game rules", TextValueArray = "" },
["01_16_GuideBoastResultPopUpResultText_1_TT"] = { CsdId = "01_16_GuideBoastResultPopUp", NodeId = "ResultText_1_TT", Text = "Total", TextValueArray = "" },
["01_16_GuideBoastResultPopUpResultText_2_TT"] = { CsdId = "01_16_GuideBoastResultPopUp", NodeId = "ResultText_2_TT", Text = "×", TextValueArray = "" },
["01_16_GuideDiceCupLayerVerticesText_TT"] = { CsdId = "01_16_GuideDiceCupLayer", NodeId = "VerticesText_TT", Text = "×", TextValueArray = "" },
["01_16_GuideDiceCupLayerVerticesText_1_TT"] = { CsdId = "01_16_GuideDiceCupLayer", NodeId = "VerticesText_1_TT", Text = "×", TextValueArray = "" },
["01_16_GuideDiceCupLayerWaitingText_TT"] = { CsdId = "01_16_GuideDiceCupLayer", NodeId = "WaitingText_TT", Text = "Waiting...", TextValueArray = "" },
["01_16_GuideDiceCupLayerResultText_1_TT"] = { CsdId = "01_16_GuideDiceCupLayer", NodeId = "ResultText_1_TT", Text = "Panther", TextValueArray = "" },
["01_16_GuideDiceCupLayerResultText_2_TT"] = { CsdId = "01_16_GuideDiceCupLayer", NodeId = "ResultText_2_TT", Text = "Straight", TextValueArray = "" },
["01_16_GuideGuessingLayerVerticesText_TT"] = { CsdId = "01_16_GuideGuessingLayer", NodeId = "VerticesText_TT", Text = "×", TextValueArray = "" },
["01_16_GuideGuessingLayerEnoughText_TT"] = { CsdId = "01_16_GuideGuessingLayer", NodeId = "EnoughText_TT", Text = "TRUE", TextValueArray = "" },
["01_16_GuideGuessingLayerNotEnoughText_TT"] = { CsdId = "01_16_GuideGuessingLayer", NodeId = "NotEnoughText_TT", Text = "BLUFF", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_1TitleText_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_1", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_1CancelText_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_1", NodeId = "CancelText_TT", Text = "No", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_1ConfirmText_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Yes", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_1ContentText_3_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_1", NodeId = "ContentText_3_TT", Text = "Just a little more left till jackpot", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_1ContentText_4_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_1", NodeId = "ContentText_4_TT", Text = "Do you really want to quit?", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_2PopupText_1_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_2", NodeId = "PopupText_1_TT", Text = "You have three 5s.\\nGo ahead and make that call.", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_2PopupText_2_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_2", NodeId = "PopupText_2_TT", Text = "There can't be seven 3s on the table, your opponent is bluffing.", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_2PopupText_3_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_2", NodeId = "PopupText_3_TT", Text = "Call BS", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_2PopupText_4_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_2", NodeId = "PopupText_4_TT", Text = "Slide up to open", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_3TitleText_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_3", NodeId = "TitleText_TT", Text = "Notice", TextValueArray = "" },
["01_16_GuideMiniTipPopUp_3ConfirmText_TT"] = { CsdId = "01_16_GuideMiniTipPopUp_3", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["01_16_GuideWinAwardLayerGetText_TT"] = { CsdId = "01_16_GuideWinAwardLayer", NodeId = "GetText_TT", Text = "Claim", TextValueArray = "" },
["01_07_SittingHelpLayerReturnText_TT"] = { CsdId = "01_07_SittingHelpLayer", NodeId = "ReturnText_TT", Text = "Return", TextValueArray = "" },
["04_02_FriendsHintCellHintText_TT"] = { CsdId = "04_02_FriendsHintCell", NodeId = "HintText_TT", Text = "Friend request accepted", TextValueArray = "" },
["02_04_ReleaseShutupCellReleaseShutupText_TT"] = { CsdId = "02_04_ReleaseShutupCell", NodeId = "ReleaseShutupText_TT", Text = "Unmute", TextValueArray = "" },
["03_03_BlackBuyCellBlackBuyText_TT"] = { CsdId = "03_03_BlackBuyCell", NodeId = "BlackBuyText_TT", Text = "Black Pass Acquired", TextValueArray = "" },
["03_03_BlackBuyCellBlackBuyButtonText_TT"] = { CsdId = "03_03_BlackBuyCell", NodeId = "BlackBuyButtonText_TT", Text = "Got it", TextValueArray = "" },
["03_03_BlackSubscriptionCellIDLabelText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "IDLabelText_TT", Text = "Exclusive Profile", TextValueArray = "" },
["03_03_BlackSubscriptionCellSicBoALLinText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "SicBoALLinText_TT", Text = "Sic Bo All In", TextValueArray = "" },
["03_03_BlackSubscriptionCellSicBoDoubleText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "SicBoDoubleText_TT", Text = "Sic Bo Double Up", TextValueArray = "" },
["03_03_BlackSubscriptionCellAdFreeText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "AdFreeText_TT", Text = "Ad-free Access", TextValueArray = "" },
["03_03_BlackSubscriptionCellDailyBonusText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "DailyBonusText_TT", Text = "Daily Rewards", TextValueArray = "" },
["03_03_BlackSubscriptionCellUpMemberText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "UpMemberText_TT", Text = "Upgrade Pass", TextValueArray = "" },
["03_03_BlackSubscriptionCellUpMemberNum_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "UpMemberNum_TT", Text = "$199.99/month", TextValueArray = "" },
["03_03_BlackSubscriptionCellBuyMemberText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "BuyMemberText_TT", Text = "Subscribe", TextValueArray = "" },
["03_03_BlackSubscriptionCellBuyMemberNum_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "BuyMemberNum_TT", Text = "$199.99/month", TextValueArray = "" },
["03_03_BlackSubscriptionCellOpenAutoRenewText_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "OpenAutoRenewText_TT", Text = "Enable Auto-renewal", TextValueArray = "" },
["03_03_BlackSubscriptionCellOpenAutoRenewNum_TT"] = { CsdId = "03_03_BlackSubscriptionCell", NodeId = "OpenAutoRenewNum_TT", Text = "$199.99/month", TextValueArray = "" },
["03_03_GoldBuyCellGoldBuyText_TT"] = { CsdId = "03_03_GoldBuyCell", NodeId = "GoldBuyText_TT", Text = "Gold Pass Acquired", TextValueArray = "" },
["03_03_GoldBuyCellGoldBuyButtonText_TT"] = { CsdId = "03_03_GoldBuyCell", NodeId = "GoldBuyButtonText_TT", Text = "Got it", TextValueArray = "" },
["03_03_GoldSubscriptionCellIDLabelText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "IDLabelText_TT", Text = "Exclusive Profile", TextValueArray = "" },
["03_03_GoldSubscriptionCellSicBoDoubleText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "SicBoDoubleText_TT", Text = "Sic Bo Double Up", TextValueArray = "" },
["03_03_GoldSubscriptionCellAdFreeText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "AdFreeText_TT", Text = "Ad-free Access", TextValueArray = "" },
["03_03_GoldSubscriptionCellDailyBonusText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "DailyBonusText_TT", Text = "Daily Rewards", TextValueArray = "" },
["03_03_GoldSubscriptionCellUpMemberText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "UpMemberText_TT", Text = "Upgrade Pass", TextValueArray = "" },
["03_03_GoldSubscriptionCellUpMemberNum_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "UpMemberNum_TT", Text = "$19.99/month", TextValueArray = "" },
["03_03_GoldSubscriptionCellBuyMemberText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "BuyMemberText_TT", Text = "Subscribe", TextValueArray = "" },
["03_03_GoldSubscriptionCellBuyMemberNum_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "BuyMemberNum_TT", Text = "$19.99/month", TextValueArray = "" },
["03_03_GoldSubscriptionCellOpenAutoRenewText_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "OpenAutoRenewText_TT", Text = "Enable Auto-renewal", TextValueArray = "" },
["03_03_GoldSubscriptionCellOpenAutoRenewNum_TT"] = { CsdId = "03_03_GoldSubscriptionCell", NodeId = "OpenAutoRenewNum_TT", Text = "$19.99/month", TextValueArray = "" },
["03_03_SilverBuyCellSilverBuyText_TT"] = { CsdId = "03_03_SilverBuyCell", NodeId = "SilverBuyText_TT", Text = "Silver Pass Acquired", TextValueArray = "" },
["03_03_SilverBuyCellSilverBuyButtonText_TT"] = { CsdId = "03_03_SilverBuyCell", NodeId = "SilverBuyButtonText_TT", Text = "Got it", TextValueArray = "" },
["03_03_SilverSubscriptionCellIDLabelText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "IDLabelText_TT", Text = "Exclusive Profile", TextValueArray = "" },
["03_03_SilverSubscriptionCellSicBoDoubleText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "SicBoDoubleText_TT", Text = "Sic Bo Double Up", TextValueArray = "" },
["03_03_SilverSubscriptionCellDailyBonusText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "DailyBonusText_TT", Text = "Daily Rewards", TextValueArray = "" },
["03_03_SilverSubscriptionCellUpMemberText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "UpMemberText_TT", Text = "Upgrade Pass", TextValueArray = "" },
["03_03_SilverSubscriptionCellUpMemberNum_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "UpMemberNum_TT", Text = "$4.99/month", TextValueArray = "" },
["03_03_SilverSubscriptionCellBuyMemberText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "BuyMemberText_TT", Text = "Subscribe", TextValueArray = "" },
["03_03_SilverSubscriptionCellBuyMemberNum_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "BuyMemberNum_TT", Text = "$4.99/month", TextValueArray = "" },
["03_03_SilverSubscriptionCellOpenAutoRenewText_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "OpenAutoRenewText_TT", Text = "Enable Auto-renewal", TextValueArray = "" },
["03_03_SilverSubscriptionCellOpenAutoRenewNum_TT"] = { CsdId = "03_03_SilverSubscriptionCell", NodeId = "OpenAutoRenewNum_TT", Text = "$4.99/month", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_1TitleText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_1", NodeId = "TitleText_TT", Text = "Cancel Subscription", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_1ContentText_1_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_1", NodeId = "ContentText_1_TT", Text = "Once canceled, your subscription will remain active until valid date. Are you sure you want to proceed?", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_1ConfirmText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Cancel now", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_1CancelText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_1", NodeId = "CancelText_TT", Text = "Got it", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_2TitleText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_2", NodeId = "TitleText_TT", Text = "Enable Auto-renewal", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_2ContentText_1_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_2", NodeId = "ContentText_1_TT", Text = "When enabled, your monthly subscription fee will be automatically deducted. Please confirm to start. ", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_2ConfirmText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_2", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_2CancelText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_2", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_3TitleText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_3", NodeId = "TitleText_TT", Text = "Upgrade Pass", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_3ContentText_1_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_3", NodeId = "ContentText_1_TT", Text = "Upgrading your pass gives you immediate access to more benefits and monthly gems. New subscription plan is automatically renewed upon expiration.", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_3ConfirmText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_3", NodeId = "ConfirmText_TT", Text = "Upgrade now", TextValueArray = "" },
["03_03_SubscriptionTipPopUp_3CancelText_TT"] = { CsdId = "03_03_SubscriptionTipPopUp_3", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_02_BankerGuessSizeLayerDefault.TTF"] = { CsdId = "02_02_BankerGuessSizeLayer", NodeId = "Default.TTF", Text = "Exit", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpPrivateRoomText_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "PrivateRoomText_TT", Text = "VIP room", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpPrivateRoomNameText_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "PrivateRoomNameText_TT", Text = "Name:", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomAnteText_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomAnteText_TT", Text = "Bet:", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomAnteName_3_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomAnteName_3_TT", Text = "10K", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomAnteName_4_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomAnteName_4_TT", Text = "25K", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomAnteName_5_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomAnteName_5_TT", Text = "100K", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomAnteName_6_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomAnteName_6_TT", Text = "250K", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpRoomPasswordText_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "RoomPasswordText_TT", Text = "Password:", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpSelectText_1_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "SelectText_1_TT", Text = "Cancel", TextValueArray = "" },
["02_01_PrivateRoomSetPopUpSelectText_2_TT"] = { CsdId = "02_01_PrivateRoomSetPopUp", NodeId = "SelectText_2_TT", Text = "Confirm", TextValueArray = "" },
["02_01_BoastMagicEmojiPopUpKickPlayerText_TT"] = { CsdId = "02_01_BoastMagicEmojiPopUp", NodeId = "KickPlayerText_TT", Text = "Kick player", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_1TitleText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_1", NodeId = "TitleText_TT", Text = "Insufficient gems", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_1ContentText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_1", NodeId = "ContentText_TT", Text = "Not enough gold to join this room", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_1ConfirmText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_1", NodeId = "ConfirmText_TT", Text = "Buy", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_1CancelText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_1", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_2TitleText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_2", NodeId = "TitleText_TT", Text = "Multi invite", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_2ContentText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_2", NodeId = "ContentText_TT", Text = "Send invites to all online players?", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_2GoldNumText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_2", NodeId = "GoldNumText_TT", Text = " ", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_2ConfirmText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_2", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_2CancelText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_2", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_3TitleText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_3", NodeId = "TitleText_TT", Text = "VIP room", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_3RoomPasswordText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_3", NodeId = "RoomPasswordText_TT", Text = "Password:", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_3ConfirmText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_3", NodeId = "ConfirmText_TT", Text = "Confirm", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_3CancelText_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_3", NodeId = "CancelText_TT", Text = "Cancel", TextValueArray = "" },
["01_02_MainLayerAllinForbidText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "AllinForbidText_TT", Text = "All in", TextValueArray = "" },
["01_02_MainLayerAllinLimitText_TT"] = { CsdId = "01_02_MainLayer", NodeId = "AllinLimitText_TT", Text = "Max amount", TextValueArray = "" },
["02_01_BoastMiniTipPopUp_1ContentText_1_TT"] = { CsdId = "02_01_BoastMiniTipPopUp_1", NodeId = "ContentText_1_TT", Text = "您的金币不足，无法创建此房间", TextValueArray = "" }

}
cc.exports.g_UIMultiLanguage_EN = UIMultiLanguage_EN
