--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
"ui/00_02_Default/00_02_Default_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 482.0000, height = 104.0000})

--Create AddFriendPopUp
local AddFriendPopUp=cc.Node:create()
AddFriendPopUp:setName("AddFriendPopUp")
AddFriendPopUp:setTag(270)
AddFriendPopUp:setCascadeColorEnabled(true)
AddFriendPopUp:setCascadeOpacityEnabled(true)
AddFriendPopUp:setPosition(0.0000, 52.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AddFriendPopUp)
layout:setPositionPercentY(0.5000)
layout:setRightMargin(482.0000)
layout:setTopMargin(52.0000)
layout:setBottomMargin(52.0000)
Layer:addChild(AddFriendPopUp)

--Create Bg
local Bg = ccui.ImageView:create()
Bg:ignoreContentAdaptWithSize(false)
Bg:loadTexture("02_01_Boast/frame_019.png", 1)
Bg:setLayoutComponentEnabled(true)
Bg:setName("Bg")
Bg:setTag(353)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
Bg:setAnchorPoint(0.0000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setSize({width = 482.0000, height = 104.0000})
layout:setRightMargin(-482.0000)
layout:setTopMargin(-52.0000)
layout:setBottomMargin(-52.0000)
AddFriendPopUp:addChild(Bg)

--Create HeadIcon_3
local HeadIcon_3=cc.Node:create()
HeadIcon_3:setName("HeadIcon_3")
HeadIcon_3:setTag(63)
HeadIcon_3:setCascadeColorEnabled(true)
HeadIcon_3:setCascadeOpacityEnabled(true)
HeadIcon_3:setPosition(44.0000, 7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(HeadIcon_3)
layout:setLeftMargin(44.0000)
layout:setRightMargin(-44.0000)
layout:setTopMargin(-7.0000)
layout:setBottomMargin(7.0000)
AddFriendPopUp:addChild(HeadIcon_3)

--Create HeadFrame_3
local HeadFrame_3 = ccui.ImageView:create()
HeadFrame_3:ignoreContentAdaptWithSize(false)
HeadFrame_3:loadTexture("00_02_Default/102001.png", 1)
HeadFrame_3:setLayoutComponentEnabled(true)
HeadFrame_3:setName("HeadFrame_3")
HeadFrame_3:setTag(487)
HeadFrame_3:setCascadeColorEnabled(true)
HeadFrame_3:setCascadeOpacityEnabled(true)
HeadFrame_3:setPosition(44.0001, 7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(HeadFrame_3)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(-15.9999)
layout:setRightMargin(-104.0001)
layout:setTopMargin(-67.0000)
layout:setBottomMargin(-53.0000)
AddFriendPopUp:addChild(HeadFrame_3)

--Create HeadPanel_3
local HeadPanel_3 = ccui.Layout:create()
HeadPanel_3:ignoreContentAdaptWithSize(false)
HeadPanel_3:setClippingEnabled(false)
HeadPanel_3:setBackGroundColorOpacity(102)
HeadPanel_3:setTouchEnabled(true);
HeadPanel_3:setLayoutComponentEnabled(true)
HeadPanel_3:setName("HeadPanel_3")
HeadPanel_3:setTag(293)
HeadPanel_3:setCascadeColorEnabled(true)
HeadPanel_3:setCascadeOpacityEnabled(true)
HeadPanel_3:setAnchorPoint(0.5000, 0.5000)
HeadPanel_3:setPosition(44.0000, 7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(HeadPanel_3)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(-16.0000)
layout:setRightMargin(-104.0000)
layout:setTopMargin(-67.0000)
layout:setBottomMargin(-53.0000)
AddFriendPopUp:addChild(HeadPanel_3)

--Create RefuseButton

local luaScript = require("csd.LuaScript.newButton")
local RefuseButton = luaScript.CreateCustomNode()
RefuseButton:ignoreContentAdaptWithSize(false)
RefuseButton:loadTextureNormal("02_01_Boast/button_012.png", 1)
RefuseButton:loadTexturePressed("02_01_Boast/button_012.png", 1)
RefuseButton:loadTextureDisabled("02_01_Boast/button_012.png", 1)
RefuseButton:setTitleFontSize(14)
RefuseButton:setLayoutComponentEnabled(true)
RefuseButton:setName("RefuseButton")
RefuseButton:setTag(490)
RefuseButton:setCascadeColorEnabled(true)
RefuseButton:setCascadeOpacityEnabled(true)
RefuseButton:setPosition(444.9674, 8.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RefuseButton)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(420.9674)
layout:setRightMargin(-468.9674)
layout:setTopMargin(-32.0000)
layout:setBottomMargin(-16.0000)

luaScript.SetDownScele(RefuseButton, "0.9800")
luaScript.SetClickEffect(RefuseButton, "Sound004")
luaScript.SetDownColor(RefuseButton, {r = 65, g = 65, b = 70})
AddFriendPopUp:addChild(RefuseButton)

--Create AgreeButton

local luaScript = require("csd.LuaScript.newButton")
local AgreeButton = luaScript.CreateCustomNode()
AgreeButton:ignoreContentAdaptWithSize(false)
AgreeButton:loadTextureNormal("02_01_Boast/button_017.png", 1)
AgreeButton:loadTexturePressed("Default/Button_Press.png", 1)
AgreeButton:loadTextureDisabled("02_01_Boast/button_017.png", 1)
AgreeButton:setTitleFontSize(14)
AgreeButton:setLayoutComponentEnabled(true)
AgreeButton:setName("AgreeButton")
AgreeButton:setTag(492)
AgreeButton:setCascadeColorEnabled(true)
AgreeButton:setCascadeOpacityEnabled(true)
AgreeButton:setPosition(384.6840, 8.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AgreeButton)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(360.6840)
layout:setRightMargin(-408.6840)
layout:setTopMargin(-32.0000)
layout:setBottomMargin(-16.0000)

luaScript.SetDownScele(AgreeButton, "0.9800")
luaScript.SetClickEffect(AgreeButton, "Sound004")
luaScript.SetDownColor(AgreeButton, {r = 65, g = 65, b = 70})
AddFriendPopUp:addChild(AgreeButton)

--Create NameText_3_O
local NameText_3_O = ccui.Text:create()
NameText_3_O:ignoreContentAdaptWithSize(true)
NameText_3_O:setTextAreaSize({width = 0, height = 0})
NameText_3_O:setFontName("font/Font001.ttf")
NameText_3_O:setFontSize(24)
NameText_3_O:setString([[马里奥一二三]])
NameText_3_O:setTextVerticalAlignment(1)
NameText_3_O:setLayoutComponentEnabled(true)
NameText_3_O:setName("NameText_3_O")
NameText_3_O:setTag(494)
NameText_3_O:setCascadeColorEnabled(true)
NameText_3_O:setCascadeOpacityEnabled(true)
NameText_3_O:setAnchorPoint(0.0000, 0.5000)
NameText_3_O:setPosition(85.9999, 24.9999)
NameText_3_O:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(NameText_3_O)
layout:setSize({width = 147.0000, height = 32.0000})
layout:setLeftMargin(85.9999)
layout:setRightMargin(-232.9999)
layout:setTopMargin(-40.9999)
layout:setBottomMargin(8.9999)
AddFriendPopUp:addChild(NameText_3_O)

--Create ContentText_TT
local ContentText_TT = ccui.Text:create()
ContentText_TT:ignoreContentAdaptWithSize(true)
ContentText_TT:setTextAreaSize({width = 0, height = 0})
ContentText_TT:setFontName("font/Default.ttf")
ContentText_TT:setFontSize(24)
ContentText_TT:setString([[请求添加你好友]])
ContentText_TT:setTextVerticalAlignment(1)
ContentText_TT:setLayoutComponentEnabled(true)
ContentText_TT:setName("ContentText_TT")
ContentText_TT:setTag(495)
ContentText_TT:setCascadeColorEnabled(true)
ContentText_TT:setCascadeOpacityEnabled(true)
ContentText_TT:setAnchorPoint(0.0000, 0.5000)
ContentText_TT:setPosition(83.9996, -7.0003)
ContentText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_TT)
layout:setSize({width = 171.0000, height = 32.0000})
layout:setLeftMargin(83.9996)
layout:setRightMargin(-254.9996)
layout:setTopMargin(-8.9997)
layout:setBottomMargin(-23.0003)
AddFriendPopUp:addChild(ContentText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

