--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
"ui/01_10_Mail/01_10_Mail_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 600.0000})

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(11)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(720.0000)
layout:setTopMargin(600.0000)
Layer:addChild(Middle)

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(12)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
Middle:addChild(Bg)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg_1:setScale9Enabled(true)
Bg_1:setCapInsets({x = 17, y = 138, width = 20, height = 144})
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(13)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setAnchorPoint(0.5000, 0.0000)
Bg_1:setPosition(360.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 718.0000, height = 600.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(-719.0000)
layout:setTopMargin(-600.0000)
Bg:addChild(Bg_1)

--Create TitleText
local TitleText = ccui.Text:create()
TitleText:ignoreContentAdaptWithSize(true)
TitleText:setTextAreaSize({width = 0, height = 0})
TitleText:setFontName("font/Font001.ttf")
TitleText:setFontSize(32)
TitleText:setString([[提示]])
TitleText:setTextHorizontalAlignment(1)
TitleText:setTextVerticalAlignment(1)
TitleText:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
TitleText:setLayoutComponentEnabled(true)
TitleText:setName("TitleText")
TitleText:setTag(14)
TitleText:setCascadeColorEnabled(true)
TitleText:setCascadeOpacityEnabled(true)
TitleText:setPosition(359.0000, 562.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText)
layout:setSize({width = 67.0000, height = 42.0000})
layout:setLeftMargin(325.5000)
layout:setRightMargin(-392.5000)
layout:setTopMargin(-583.9999)
layout:setBottomMargin(541.9999)
Middle:addChild(TitleText)

--Create ContentText_1
local ContentText_1 = ccui.Text:create()
ContentText_1:ignoreContentAdaptWithSize(false)
ContentText_1:setFontName("font/Default.ttf")
ContentText_1:setFontSize(32)
ContentText_1:setString([[由于您的账号存在违规行为，账号已被封
禁，如有疑问请联系客服。]])
ContentText_1:setTextHorizontalAlignment(1)
ContentText_1:setTextVerticalAlignment(1)
ContentText_1:setLayoutComponentEnabled(true)
ContentText_1:setName("ContentText_1")
ContentText_1:setTag(15)
ContentText_1:setCascadeColorEnabled(true)
ContentText_1:setCascadeOpacityEnabled(true)
ContentText_1:setPosition(359.0001, 400.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_1)
layout:setSize({width = 600.0000, height = 126.0000})
layout:setLeftMargin(59.0001)
layout:setRightMargin(-659.0001)
layout:setTopMargin(-463.0000)
layout:setBottomMargin(337.0000)
Middle:addChild(ContentText_1)

--Create ContentText_2
local ContentText_2 = ccui.Text:create()
ContentText_2:ignoreContentAdaptWithSize(false)
ContentText_2:setFontName("font/Default.ttf")
ContentText_2:setFontSize(28)
ContentText_2:setString([[封禁结束时间（XXXX-XX-XX 00:00）]])
ContentText_2:setTextVerticalAlignment(1)
ContentText_2:setLayoutComponentEnabled(true)
ContentText_2:setName("ContentText_2")
ContentText_2:setTag(49)
ContentText_2:setCascadeColorEnabled(true)
ContentText_2:setCascadeOpacityEnabled(true)
ContentText_2:setPosition(359.0000, 280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_2)
layout:setSize({width = 600.0000, height = 42.0000})
layout:setLeftMargin(59.0000)
layout:setRightMargin(-659.0000)
layout:setTopMargin(-301.0000)
layout:setBottomMargin(259.0000)
Middle:addChild(ContentText_2)

--Create ContentText_3
local ContentText_3 = ccui.Text:create()
ContentText_3:ignoreContentAdaptWithSize(false)
ContentText_3:setFontName("font/Default.ttf")
ContentText_3:setFontSize(28)
ContentText_3:setString([[封禁理由：【使用外挂及第三方软件】]])
ContentText_3:setTextVerticalAlignment(1)
ContentText_3:setLayoutComponentEnabled(true)
ContentText_3:setName("ContentText_3")
ContentText_3:setTag(50)
ContentText_3:setCascadeColorEnabled(true)
ContentText_3:setCascadeOpacityEnabled(true)
ContentText_3:setPosition(359.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_3)
layout:setSize({width = 600.0000, height = 42.0000})
layout:setLeftMargin(59.0000)
layout:setRightMargin(-659.0000)
layout:setTopMargin(-251.0000)
layout:setBottomMargin(209.0000)
Middle:addChild(ContentText_3)

--Create Confirm
local Confirm=cc.Node:create()
Confirm:setName("Confirm")
Confirm:setTag(16)
Confirm:setCascadeColorEnabled(true)
Confirm:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Confirm)
Middle:addChild(Confirm)

--Create ConfirmButton

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton = luaScript.CreateCustomNode()
ConfirmButton:ignoreContentAdaptWithSize(false)
ConfirmButton:loadTextureNormal("01_10_Mail/button_034.png", 1)
ConfirmButton:loadTexturePressed("01_10_Mail/button_034.png", 1)
ConfirmButton:loadTextureDisabled("01_10_Mail/button_034.png", 1)
ConfirmButton:setTitleFontSize(14)
ConfirmButton:setLayoutComponentEnabled(true)
ConfirmButton:setName("ConfirmButton")
ConfirmButton:setTag(17)
ConfirmButton:setCascadeColorEnabled(true)
ConfirmButton:setCascadeOpacityEnabled(true)
ConfirmButton:setPosition(359.0000, 111.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(255.0000)
layout:setRightMargin(-463.0000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(62.0000)

luaScript.SetDownScele(ConfirmButton, "0.9800")
luaScript.SetClickEffect(ConfirmButton, "Sound004")
luaScript.SetDownColor(ConfirmButton, {r = 65, g = 65, b = 70})
Confirm:addChild(ConfirmButton)

--Create ConfirmText_TT
local ConfirmText_TT = ccui.Text:create()
ConfirmText_TT:ignoreContentAdaptWithSize(true)
ConfirmText_TT:setTextAreaSize({width = 0, height = 0})
ConfirmText_TT:setFontName("font/Font001.ttf")
ConfirmText_TT:setFontSize(28)
ConfirmText_TT:setString([[确定]])
ConfirmText_TT:setTextHorizontalAlignment(1)
ConfirmText_TT:setTextVerticalAlignment(1)
ConfirmText_TT:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
ConfirmText_TT:setLayoutComponentEnabled(true)
ConfirmText_TT:setName("ConfirmText_TT")
ConfirmText_TT:setTag(18)
ConfirmText_TT:setCascadeColorEnabled(true)
ConfirmText_TT:setCascadeOpacityEnabled(true)
ConfirmText_TT:setPosition(104.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmText_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2837)
layout:setPercentHeight(0.3776)
layout:setSize({width = 59.0000, height = 37.0000})
layout:setLeftMargin(74.5000)
layout:setRightMargin(74.5000)
layout:setTopMargin(30.5000)
layout:setBottomMargin(30.5000)
ConfirmButton:addChild(ConfirmText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

