--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 718.0000, height = 300.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(261)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(718.0000)
layout:setTopMargin(300.0000)
Layer:addChild(Bg)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(262)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setRightMargin(-600.0000)
layout:setTopMargin(-300.0000)
Bg:addChild(InteractionPopups)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg_1:setScale9Enabled(true)
Bg_1:setCapInsets({x = 17, y = 138, width = 20, height = 144})
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(263)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 718.0000, height = 300.0000})
layout:setRightMargin(-718.0000)
layout:setTopMargin(-300.0000)
Bg:addChild(Bg_1)

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(252)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(718.0000)
layout:setTopMargin(300.0000)
Layer:addChild(Middle)

--Create TipTitleText
local TipTitleText = ccui.Text:create()
TipTitleText:ignoreContentAdaptWithSize(true)
TipTitleText:setTextAreaSize({width = 0, height = 0})
TipTitleText:setFontName("font/Font001.ttf")
TipTitleText:setFontSize(28)
TipTitleText:setString([[提示]])
TipTitleText:setTextHorizontalAlignment(1)
TipTitleText:setTextVerticalAlignment(1)
TipTitleText:enableShadow({r = 34, g = 31, b = 86, a = 255}, {width = 0, height = -2}, 0)
TipTitleText:setLayoutComponentEnabled(true)
TipTitleText:setName("TipTitleText")
TipTitleText:setTag(253)
TipTitleText:setCascadeColorEnabled(true)
TipTitleText:setCascadeOpacityEnabled(true)
TipTitleText:setPosition(359.0000, 262.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(TipTitleText)
layout:setSize({width = 59.0000, height = 37.0000})
layout:setLeftMargin(329.5000)
layout:setRightMargin(-388.5000)
layout:setTopMargin(-280.5006)
layout:setBottomMargin(243.5006)
Middle:addChild(TipTitleText)

--Create ContentText
local ContentText = ccui.Text:create()
ContentText:ignoreContentAdaptWithSize(false)
ContentText:setFontName("font/Default.ttf")
ContentText:setFontSize(32)
ContentText:setString([[测试文本]])
ContentText:setTextHorizontalAlignment(1)
ContentText:setTextVerticalAlignment(1)
ContentText:setLayoutComponentEnabled(true)
ContentText:setName("ContentText")
ContentText:setTag(62)
ContentText:setCascadeColorEnabled(true)
ContentText:setCascadeOpacityEnabled(true)
ContentText:setPosition(359.0000, 125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText)
layout:setSize({width = 600.0000, height = 126.0000})
layout:setLeftMargin(59.0000)
layout:setRightMargin(-659.0000)
layout:setTopMargin(-188.0000)
layout:setBottomMargin(62.0000)
Middle:addChild(ContentText)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

