--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_04_Invitation/03_04_Invitation_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 218.0000, height = 308.0000})

--Create Task
local Task=cc.Node:create()
Task:setName("Task")
Task:setTag(104)
Task:setCascadeColorEnabled(true)
Task:setCascadeOpacityEnabled(true)
Task:setPosition(109.0000, 154.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Task)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(154.0000)
layout:setBottomMargin(154.0000)
Layer:addChild(Task)

--Create TaskPanel
local TaskPanel = ccui.Layout:create()
TaskPanel:ignoreContentAdaptWithSize(false)
TaskPanel:setClippingEnabled(false)
TaskPanel:setBackGroundColorOpacity(102)
TaskPanel:setTouchEnabled(true);
TaskPanel:setLayoutComponentEnabled(true)
TaskPanel:setName("TaskPanel")
TaskPanel:setTag(188)
TaskPanel:setCascadeColorEnabled(true)
TaskPanel:setCascadeOpacityEnabled(true)
TaskPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskPanel)
layout:setSize({width = 218.0000, height = 308.0000})
layout:setLeftMargin(-109.0000)
layout:setRightMargin(-109.0000)
layout:setTopMargin(-154.0000)
layout:setBottomMargin(-154.0000)
Task:addChild(TaskPanel)

--Create Bg
local Bg = ccui.ImageView:create()
Bg:ignoreContentAdaptWithSize(false)
Bg:loadTexture("03_04_Invitation/frame_066.png", 1)
Bg:setScale9Enabled(true)
Bg:setCapInsets({x = 16, y = 101, width = 18, height = 106})
Bg:setLayoutComponentEnabled(true)
Bg:setName("Bg")
Bg:setTag(106)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
Bg:setPosition(108.9986, 153.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 218.0000, height = 308.0000})
layout:setLeftMargin(-0.0014)
layout:setRightMargin(0.0014)
layout:setTopMargin(0.0002)
layout:setBottomMargin(-0.0002)
TaskPanel:addChild(Bg)

--Create Common
local Common=cc.Node:create()
Common:setName("Common")
Common:setTag(107)
Common:setCascadeColorEnabled(true)
Common:setCascadeOpacityEnabled(true)
Common:setPosition(108.9986, 153.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(Common)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(108.9986)
layout:setRightMargin(109.0014)
layout:setTopMargin(154.0002)
layout:setBottomMargin(153.9998)
TaskPanel:addChild(Common)

--Create TaskLoading
local TaskLoading=cc.Node:create()
TaskLoading:setName("TaskLoading")
TaskLoading:setTag(108)
TaskLoading:setCascadeColorEnabled(true)
TaskLoading:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskLoading)
Common:addChild(TaskLoading)

--Create TaskLoadingBarBg
local TaskLoadingBarBg = ccui.ImageView:create()
TaskLoadingBarBg:ignoreContentAdaptWithSize(false)
TaskLoadingBarBg:loadTexture("03_04_Invitation/strip_019.png", 1)
TaskLoadingBarBg:setScale9Enabled(true)
TaskLoadingBarBg:setCapInsets({x = 52, y = 7, width = 56, height = 10})
TaskLoadingBarBg:setLayoutComponentEnabled(true)
TaskLoadingBarBg:setName("TaskLoadingBarBg")
TaskLoadingBarBg:setTag(109)
TaskLoadingBarBg:setCascadeColorEnabled(true)
TaskLoadingBarBg:setCascadeOpacityEnabled(true)
TaskLoadingBarBg:setPosition(0.0000, -24.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskLoadingBarBg)
layout:setSize({width = 160.0000, height = 24.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(12.0002)
layout:setBottomMargin(-36.0002)
TaskLoading:addChild(TaskLoadingBarBg)

--Create TaskLoadingBar
local TaskLoadingBar = ccui.LoadingBar:create()
TaskLoadingBar:loadTexture("03_04_Invitation/strip_018.png", 1)
TaskLoadingBar:ignoreContentAdaptWithSize(false)
TaskLoadingBar:setPercent(80)
TaskLoadingBar:setLayoutComponentEnabled(true)
TaskLoadingBar:setName("TaskLoadingBar")
TaskLoadingBar:setTag(144)
TaskLoadingBar:setCascadeColorEnabled(true)
TaskLoadingBar:setCascadeOpacityEnabled(true)
TaskLoadingBar:setPosition(0.0000, -24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskLoadingBar)
layout:setSize({width = 160.0000, height = 24.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(-36.0000)
TaskLoading:addChild(TaskLoadingBar)

--Create TaskNum
local TaskNum = ccui.Text:create()
TaskNum:ignoreContentAdaptWithSize(true)
TaskNum:setTextAreaSize({width = 0, height = 0})
TaskNum:setFontName("font/Font003.ttf")
TaskNum:setFontSize(23)
TaskNum:setString([[10/10]])
TaskNum:setLayoutComponentEnabled(true)
TaskNum:setName("TaskNum")
TaskNum:setTag(155)
TaskNum:setCascadeColorEnabled(true)
TaskNum:setCascadeOpacityEnabled(true)
TaskNum:setPosition(-1.9999, -23.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskNum)
layout:setSize({width = 55.0000, height = 27.0000})
layout:setLeftMargin(-29.4999)
layout:setRightMargin(-25.5001)
layout:setTopMargin(9.5000)
layout:setBottomMargin(-36.5000)
TaskLoading:addChild(TaskNum)

--Create Reward
local Reward=cc.Node:create()
Reward:setName("Reward")
Reward:setTag(145)
Reward:setCascadeColorEnabled(true)
Reward:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Reward)
Common:addChild(Reward)

--Create RewardPanel
local RewardPanel = ccui.Layout:create()
RewardPanel:ignoreContentAdaptWithSize(false)
RewardPanel:setClippingEnabled(false)
RewardPanel:setBackGroundColorOpacity(102)
RewardPanel:setTouchEnabled(true);
RewardPanel:setLayoutComponentEnabled(true)
RewardPanel:setName("RewardPanel")
RewardPanel:setTag(436)
RewardPanel:setCascadeColorEnabled(true)
RewardPanel:setCascadeOpacityEnabled(true)
RewardPanel:setAnchorPoint(0.5000, 0.5000)
RewardPanel:setPosition(0.0000, -88.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RewardPanel)
layout:setSize({width = 86.0000, height = 86.0000})
layout:setLeftMargin(-43.0000)
layout:setRightMargin(-43.0000)
layout:setTopMargin(45.0000)
layout:setBottomMargin(-131.0000)
Reward:addChild(RewardPanel)

--Create RewardBg
local RewardBg = cc.Sprite:createWithSpriteFrameName("03_04_Invitation/frame_134.png")
RewardBg:setName("RewardBg")
RewardBg:setTag(193)
RewardBg:setCascadeColorEnabled(true)
RewardBg:setCascadeOpacityEnabled(true)
RewardBg:setPosition(0.0000, -88.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RewardBg)
layout:setSize({width = 86.0000, height = 86.0000})
layout:setLeftMargin(-43.0000)
layout:setRightMargin(-43.0000)
layout:setTopMargin(45.0000)
layout:setBottomMargin(-131.0000)
RewardBg:setBlendFunc({src = 1, dst = 771})
Reward:addChild(RewardBg)

--Create RewardIcon
local RewardIcon = ccui.ImageView:create()
RewardIcon:ignoreContentAdaptWithSize(false)
RewardIcon:loadTexture("Default/ImageFile.png", 1)
RewardIcon:setLayoutComponentEnabled(true)
RewardIcon:setName("RewardIcon")
RewardIcon:setTag(148)
RewardIcon:setCascadeColorEnabled(true)
RewardIcon:setCascadeOpacityEnabled(true)
RewardIcon:setPosition(0.0000, -87.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RewardIcon)
layout:setSize({width = 64.0000, height = 64.0000})
layout:setLeftMargin(-32.0000)
layout:setRightMargin(-32.0000)
layout:setTopMargin(55.0000)
layout:setBottomMargin(-119.0000)
Reward:addChild(RewardIcon)

--Create RewardText
local RewardText = ccui.Text:create()
RewardText:ignoreContentAdaptWithSize(true)
RewardText:setTextAreaSize({width = 0, height = 0})
RewardText:setFontName("font/Font003.ttf")
RewardText:setFontSize(24)
RewardText:setString([[1000]])
RewardText:setTextHorizontalAlignment(2)
RewardText:setTextVerticalAlignment(1)
RewardText:enableOutline({r = 255, g = 255, b = 255, a = 255}, 1)
RewardText:setLayoutComponentEnabled(true)
RewardText:setName("RewardText")
RewardText:setTag(149)
RewardText:setCascadeColorEnabled(true)
RewardText:setCascadeOpacityEnabled(true)
RewardText:setAnchorPoint(1.0000, 0.5000)
RewardText:setPosition(37.5004, -112.9998)
RewardText:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(RewardText)
layout:setSize({width = 51.0000, height = 30.0000})
layout:setLeftMargin(-13.4996)
layout:setRightMargin(-37.5004)
layout:setTopMargin(97.9998)
layout:setBottomMargin(-127.9998)
Reward:addChild(RewardText)

--Create Click
local Click=cc.Node:create()
Click:setName("Click")
Click:setTag(150)
Click:setCascadeColorEnabled(true)
Click:setCascadeOpacityEnabled(true)
Click:setPosition(108.9986, 153.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(Click)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(108.9986)
layout:setRightMargin(109.0014)
layout:setTopMargin(154.0002)
layout:setBottomMargin(153.9998)
TaskPanel:addChild(Click)

--Create ClickImage
local ClickImage = ccui.ImageView:create()
ClickImage:ignoreContentAdaptWithSize(false)
ClickImage:loadTexture("03_04_Invitation/icon_047.png", 1)
ClickImage:setLayoutComponentEnabled(true)
ClickImage:setName("ClickImage")
ClickImage:setTag(153)
ClickImage:setCascadeColorEnabled(true)
ClickImage:setCascadeOpacityEnabled(true)
ClickImage:setPosition(-0.0001, 81.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(ClickImage)
layout:setSize({width = 84.0000, height = 96.0000})
layout:setLeftMargin(-42.0001)
layout:setRightMargin(-41.9999)
layout:setTopMargin(-129.9998)
layout:setBottomMargin(33.9998)
Click:addChild(ClickImage)

--Create ClickText_TT
local ClickText_TT = ccui.Text:create()
ClickText_TT:ignoreContentAdaptWithSize(true)
ClickText_TT:setTextAreaSize({width = 0, height = 0})
ClickText_TT:setFontName("font/Font001.ttf")
ClickText_TT:setFontSize(26)
ClickText_TT:setString([[点击数]])
ClickText_TT:setLayoutComponentEnabled(true)
ClickText_TT:setName("ClickText_TT")
ClickText_TT:setTag(154)
ClickText_TT:setCascadeColorEnabled(true)
ClickText_TT:setCascadeOpacityEnabled(true)
ClickText_TT:setPosition(-0.9997, 12.0000)
ClickText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(ClickText_TT)
layout:setSize({width = 81.0000, height = 34.0000})
layout:setLeftMargin(-41.4997)
layout:setRightMargin(-39.5003)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-5.0000)
Click:addChild(ClickText_TT)

--Create Register
local Register=cc.Node:create()
Register:setName("Register")
Register:setTag(151)
Register:setCascadeColorEnabled(true)
Register:setCascadeOpacityEnabled(true)
Register:setPosition(109.0000, 154.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Register)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(154.0000)
layout:setBottomMargin(154.0000)
TaskPanel:addChild(Register)

--Create RegisterImage
local RegisterImage = ccui.ImageView:create()
RegisterImage:ignoreContentAdaptWithSize(false)
RegisterImage:loadTexture("03_04_Invitation/icon_048.png", 1)
RegisterImage:setScale9Enabled(true)
RegisterImage:setCapInsets({x = 27, y = 31, width = 30, height = 34})
RegisterImage:setLayoutComponentEnabled(true)
RegisterImage:setName("RegisterImage")
RegisterImage:setTag(156)
RegisterImage:setCascadeColorEnabled(true)
RegisterImage:setCascadeOpacityEnabled(true)
RegisterImage:setPosition(0.0000, 82.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RegisterImage)
layout:setSize({width = 84.0000, height = 96.0000})
layout:setLeftMargin(-42.0000)
layout:setRightMargin(-42.0000)
layout:setTopMargin(-130.0000)
layout:setBottomMargin(34.0000)
Register:addChild(RegisterImage)

--Create RegisterText_TT
local RegisterText_TT = ccui.Text:create()
RegisterText_TT:ignoreContentAdaptWithSize(true)
RegisterText_TT:setTextAreaSize({width = 0, height = 0})
RegisterText_TT:setFontName("font/Font001.ttf")
RegisterText_TT:setFontSize(26)
RegisterText_TT:setString([[注册数]])
RegisterText_TT:setLayoutComponentEnabled(true)
RegisterText_TT:setName("RegisterText_TT")
RegisterText_TT:setTag(158)
RegisterText_TT:setCascadeColorEnabled(true)
RegisterText_TT:setCascadeOpacityEnabled(true)
RegisterText_TT:setPosition(-1.0000, 12.0000)
RegisterText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(RegisterText_TT)
layout:setSize({width = 81.0000, height = 34.0000})
layout:setLeftMargin(-41.5000)
layout:setRightMargin(-39.5000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-5.0000)
Register:addChild(RegisterText_TT)

--Create Recharge
local Recharge=cc.Node:create()
Recharge:setName("Recharge")
Recharge:setTag(152)
Recharge:setCascadeColorEnabled(true)
Recharge:setCascadeOpacityEnabled(true)
Recharge:setPosition(109.0000, 154.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Recharge)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(154.0000)
layout:setBottomMargin(154.0000)
TaskPanel:addChild(Recharge)

--Create RechargeImage
local RechargeImage = ccui.ImageView:create()
RechargeImage:ignoreContentAdaptWithSize(false)
RechargeImage:loadTexture("03_04_Invitation/icon_049.png", 1)
RechargeImage:setScale9Enabled(true)
RechargeImage:setCapInsets({x = 27, y = 31, width = 30, height = 34})
RechargeImage:setLayoutComponentEnabled(true)
RechargeImage:setName("RechargeImage")
RechargeImage:setTag(157)
RechargeImage:setCascadeColorEnabled(true)
RechargeImage:setCascadeOpacityEnabled(true)
RechargeImage:setPosition(0.0000, 82.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RechargeImage)
layout:setSize({width = 84.0000, height = 96.0000})
layout:setLeftMargin(-42.0000)
layout:setRightMargin(-42.0000)
layout:setTopMargin(-130.0000)
layout:setBottomMargin(34.0000)
Recharge:addChild(RechargeImage)

--Create RechargeText_TT
local RechargeText_TT = ccui.Text:create()
RechargeText_TT:ignoreContentAdaptWithSize(true)
RechargeText_TT:setTextAreaSize({width = 0, height = 0})
RechargeText_TT:setFontName("font/Font001.ttf")
RechargeText_TT:setFontSize(26)
RechargeText_TT:setString([[充值]])
RechargeText_TT:setLayoutComponentEnabled(true)
RechargeText_TT:setName("RechargeText_TT")
RechargeText_TT:setTag(159)
RechargeText_TT:setCascadeColorEnabled(true)
RechargeText_TT:setCascadeOpacityEnabled(true)
RechargeText_TT:setPosition(-1.0000, 12.0000)
RechargeText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(RechargeText_TT)
layout:setSize({width = 55.0000, height = 34.0000})
layout:setLeftMargin(-28.5000)
layout:setRightMargin(-26.5000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-5.0000)
Recharge:addChild(RechargeText_TT)

--Create TaskAnimation
local TaskAnimation=cc.Node:create()
TaskAnimation:setName("TaskAnimation")
TaskAnimation:setTag(856)
TaskAnimation:setCascadeColorEnabled(true)
TaskAnimation:setCascadeOpacityEnabled(true)
TaskAnimation:setPosition(109.0000, 157.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TaskAnimation)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5097)
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(151.0000)
layout:setBottomMargin(157.0000)
TaskPanel:addChild(TaskAnimation)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

