--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_08_NewWelfare/03_08_NewWelfare_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 130.0000, height = 144.0000})

--Create LoginCell
local LoginCell=cc.Node:create()
LoginCell:setName("LoginCell")
LoginCell:setTag(321)
LoginCell:setCascadeColorEnabled(true)
LoginCell:setCascadeOpacityEnabled(true)
LoginCell:setPosition(65.0000, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(LoginCell)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(65.0000)
layout:setRightMargin(65.0000)
layout:setTopMargin(72.0000)
layout:setBottomMargin(72.0000)
Layer:addChild(LoginCell)

--Create LoginPanel
local LoginPanel = ccui.Layout:create()
LoginPanel:ignoreContentAdaptWithSize(false)
LoginPanel:setClippingEnabled(false)
LoginPanel:setBackGroundColorOpacity(102)
LoginPanel:setTouchEnabled(true);
LoginPanel:setLayoutComponentEnabled(true)
LoginPanel:setName("LoginPanel")
LoginPanel:setTag(340)
LoginPanel:setCascadeColorEnabled(true)
LoginPanel:setCascadeOpacityEnabled(true)
LoginPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(LoginPanel)
layout:setSize({width = 130.0000, height = 144.0000})
layout:setLeftMargin(-65.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-72.0000)
LoginCell:addChild(LoginPanel)

--Create State_1
local State_1=cc.Node:create()
State_1:setName("State_1")
State_1:setTag(325)
State_1:setCascadeColorEnabled(true)
State_1:setCascadeOpacityEnabled(true)
State_1:setPosition(64.9996, 71.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(State_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(72.0007)
layout:setBottomMargin(71.9993)
LoginPanel:addChild(State_1)

--Create Bg_1
local Bg_1 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_095.png")
Bg_1:setName("Bg_1")
Bg_1:setTag(423)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 130.0000, height = 144.0000})
layout:setLeftMargin(-65.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-72.0000)
Bg_1:setBlendFunc({src = 1, dst = 771})
State_1:addChild(Bg_1)

--Create State_2
local State_2=cc.Node:create()
State_2:setName("State_2")
State_2:setTag(332)
State_2:setCascadeColorEnabled(true)
State_2:setCascadeOpacityEnabled(true)
State_2:setPosition(64.9996, 71.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(State_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(72.0007)
layout:setBottomMargin(71.9993)
LoginPanel:addChild(State_2)

--Create Bg_2
local Bg_2 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_093.png")
Bg_2:setName("Bg_2")
Bg_2:setTag(424)
Bg_2:setCascadeColorEnabled(true)
Bg_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_2)
layout:setSize({width = 130.0000, height = 144.0000})
layout:setLeftMargin(-65.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-72.0000)
Bg_2:setBlendFunc({src = 1, dst = 771})
State_2:addChild(Bg_2)

--Create Day
local Day=cc.Node:create()
Day:setName("Day")
Day:setTag(326)
Day:setCascadeColorEnabled(true)
Day:setCascadeOpacityEnabled(true)
Day:setPosition(64.9996, 71.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(Day)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(72.0007)
layout:setBottomMargin(71.9993)
LoginPanel:addChild(Day)

--Create DayImage_1_IVT
local DayImage_1_IVT = ccui.ImageView:create()
DayImage_1_IVT:ignoreContentAdaptWithSize(false)
DayImage_1_IVT:loadTexture("03_08_NewWelfare/picture_023_zh_CN.png", 1)
DayImage_1_IVT:setLayoutComponentEnabled(true)
DayImage_1_IVT:setName("DayImage_1_IVT")
DayImage_1_IVT:setTag(324)
DayImage_1_IVT:setCascadeColorEnabled(true)
DayImage_1_IVT:setCascadeOpacityEnabled(true)
DayImage_1_IVT:setPosition(-0.0001, 48.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_1_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0001)
layout:setRightMargin(-44.9999)
layout:setTopMargin(-65.0001)
layout:setBottomMargin(31.0001)
Day:addChild(DayImage_1_IVT)

--Create DayImage_2_IVT
local DayImage_2_IVT = ccui.ImageView:create()
DayImage_2_IVT:ignoreContentAdaptWithSize(false)
DayImage_2_IVT:loadTexture("03_08_NewWelfare/picture_024_zh_CN.png", 1)
DayImage_2_IVT:setLayoutComponentEnabled(true)
DayImage_2_IVT:setName("DayImage_2_IVT")
DayImage_2_IVT:setTag(327)
DayImage_2_IVT:setCascadeColorEnabled(true)
DayImage_2_IVT:setCascadeOpacityEnabled(true)
DayImage_2_IVT:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_2_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(-65.0000)
layout:setBottomMargin(31.0000)
Day:addChild(DayImage_2_IVT)

--Create DayImage_3_IVT
local DayImage_3_IVT = ccui.ImageView:create()
DayImage_3_IVT:ignoreContentAdaptWithSize(false)
DayImage_3_IVT:loadTexture("03_08_NewWelfare/picture_025_zh_CN.png", 1)
DayImage_3_IVT:setLayoutComponentEnabled(true)
DayImage_3_IVT:setName("DayImage_3_IVT")
DayImage_3_IVT:setTag(328)
DayImage_3_IVT:setCascadeColorEnabled(true)
DayImage_3_IVT:setCascadeOpacityEnabled(true)
DayImage_3_IVT:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_3_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(-65.0000)
layout:setBottomMargin(31.0000)
Day:addChild(DayImage_3_IVT)

--Create DayImage_4_IVT
local DayImage_4_IVT = ccui.ImageView:create()
DayImage_4_IVT:ignoreContentAdaptWithSize(false)
DayImage_4_IVT:loadTexture("03_08_NewWelfare/picture_026_zh_CN.png", 1)
DayImage_4_IVT:setLayoutComponentEnabled(true)
DayImage_4_IVT:setName("DayImage_4_IVT")
DayImage_4_IVT:setTag(329)
DayImage_4_IVT:setCascadeColorEnabled(true)
DayImage_4_IVT:setCascadeOpacityEnabled(true)
DayImage_4_IVT:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_4_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(-65.0000)
layout:setBottomMargin(31.0000)
Day:addChild(DayImage_4_IVT)

--Create DayImage_5_IVT
local DayImage_5_IVT = ccui.ImageView:create()
DayImage_5_IVT:ignoreContentAdaptWithSize(false)
DayImage_5_IVT:loadTexture("03_08_NewWelfare/picture_027_zh_CN.png", 1)
DayImage_5_IVT:setLayoutComponentEnabled(true)
DayImage_5_IVT:setName("DayImage_5_IVT")
DayImage_5_IVT:setTag(330)
DayImage_5_IVT:setCascadeColorEnabled(true)
DayImage_5_IVT:setCascadeOpacityEnabled(true)
DayImage_5_IVT:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_5_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(-65.0000)
layout:setBottomMargin(31.0000)
Day:addChild(DayImage_5_IVT)

--Create DayImage_6_IVT
local DayImage_6_IVT = ccui.ImageView:create()
DayImage_6_IVT:ignoreContentAdaptWithSize(false)
DayImage_6_IVT:loadTexture("03_08_NewWelfare/picture_028_zh_CN.png", 1)
DayImage_6_IVT:setLayoutComponentEnabled(true)
DayImage_6_IVT:setName("DayImage_6_IVT")
DayImage_6_IVT:setTag(331)
DayImage_6_IVT:setCascadeColorEnabled(true)
DayImage_6_IVT:setCascadeOpacityEnabled(true)
DayImage_6_IVT:setPosition(0.0000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DayImage_6_IVT)
layout:setSize({width = 90.0000, height = 34.0000})
layout:setLeftMargin(-45.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(-65.0000)
layout:setBottomMargin(31.0000)
Day:addChild(DayImage_6_IVT)

--Create Common
local Common=cc.Node:create()
Common:setName("Common")
Common:setTag(333)
Common:setCascadeColorEnabled(true)
Common:setCascadeOpacityEnabled(true)
Common:setPosition(64.9996, 71.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(Common)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(72.0007)
layout:setBottomMargin(71.9993)
LoginPanel:addChild(Common)

--Create Res
local Res = ccui.ImageView:create()
Res:ignoreContentAdaptWithSize(false)
Res:loadTexture("Default/ImageFile.png", 1)
Res:setScale9Enabled(true)
Res:setCapInsets({x = 0, y = 0, width = 46, height = 46})
Res:setLayoutComponentEnabled(true)
Res:setName("Res")
Res:setTag(335)
Res:setCascadeColorEnabled(true)
Res:setCascadeOpacityEnabled(true)
Res:setPosition(0.0000, -13.0000)
Res:setScaleX(0.8000)
Res:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Res)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-63.0000)
Common:addChild(Res)

--Create ResNum
local ResNum = ccui.Text:create()
ResNum:ignoreContentAdaptWithSize(true)
ResNum:setTextAreaSize({width = 0, height = 0})
ResNum:setFontName("font/Font003.ttf")
ResNum:setFontSize(24)
ResNum:setString([[1000]])
ResNum:setTextVerticalAlignment(1)
ResNum:setLayoutComponentEnabled(true)
ResNum:setName("ResNum")
ResNum:setTag(337)
ResNum:setCascadeColorEnabled(true)
ResNum:setCascadeOpacityEnabled(true)
ResNum:setAnchorPoint(0.9000, 0.5000)
ResNum:setPosition(28.0000, -37.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ResNum)
layout:setSize({width = 50.0000, height = 28.0000})
layout:setLeftMargin(-17.0000)
layout:setRightMargin(-33.0000)
layout:setTopMargin(23.0000)
layout:setBottomMargin(-51.0000)
Common:addChild(ResNum)

--Create State_3
local State_3=cc.Node:create()
State_3:setName("State_3")
State_3:setTag(336)
State_3:setCascadeColorEnabled(true)
State_3:setCascadeOpacityEnabled(true)
State_3:setPosition(64.9996, 71.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(State_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(72.0007)
layout:setBottomMargin(71.9993)
LoginPanel:addChild(State_3)

--Create Bg_3
local Bg_3 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_098.png")
Bg_3:setName("Bg_3")
Bg_3:setTag(426)
Bg_3:setCascadeColorEnabled(true)
Bg_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_3)
layout:setSize({width = 130.0000, height = 144.0000})
layout:setLeftMargin(-65.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-72.0000)
Bg_3:setBlendFunc({src = 1, dst = 771})
State_3:addChild(Bg_3)

--Create ReceivedTipIcon
local ReceivedTipIcon = ccui.ImageView:create()
ReceivedTipIcon:ignoreContentAdaptWithSize(false)
ReceivedTipIcon:loadTexture("03_08_NewWelfare/icon_057.png", 1)
ReceivedTipIcon:setLayoutComponentEnabled(true)
ReceivedTipIcon:setName("ReceivedTipIcon")
ReceivedTipIcon:setTag(339)
ReceivedTipIcon:setCascadeColorEnabled(true)
ReceivedTipIcon:setCascadeOpacityEnabled(true)
ReceivedTipIcon:setPosition(2.0004, -4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ReceivedTipIcon)
layout:setSize({width = 54.0000, height = 54.0000})
layout:setLeftMargin(-24.9996)
layout:setRightMargin(-29.0004)
layout:setTopMargin(-23.0000)
layout:setBottomMargin(-31.0000)
State_3:addChild(ReceivedTipIcon)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

