--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_08_NewWelfare/03_08_NewWelfare_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 553.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(273)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(720.0000)
layout:setTopMargin(553.0000)
Layer:addChild(Bg)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(277)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 720.0000, height = 553.0000})
layout:setRightMargin(-720.0000)
layout:setTopMargin(-553.0000)
Bg:addChild(InteractionPopups)

--Create Bg_0
local Bg_0 = ccui.ImageView:create()
Bg_0:ignoreContentAdaptWithSize(false)
Bg_0:loadTexture("03_08_NewWelfare/frame_208.png", 1)
Bg_0:setLayoutComponentEnabled(true)
Bg_0:setName("Bg_0")
Bg_0:setTag(274)
Bg_0:setCascadeColorEnabled(true)
Bg_0:setCascadeOpacityEnabled(true)
Bg_0:setPosition(359.9998, 337.0014)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_0)
layout:setSize({width = 720.0000, height = 674.0000})
layout:setLeftMargin(-0.0002)
layout:setRightMargin(-719.9998)
layout:setTopMargin(-674.0014)
layout:setBottomMargin(0.0014)
Bg:addChild(Bg_0)

--Create LoginImage_1_IVT
local LoginImage_1_IVT = ccui.ImageView:create()
LoginImage_1_IVT:ignoreContentAdaptWithSize(false)
LoginImage_1_IVT:loadTexture("03_08_NewWelfare/picture_030_zh_CN.png", 1)
LoginImage_1_IVT:setLayoutComponentEnabled(true)
LoginImage_1_IVT:setName("LoginImage_1_IVT")
LoginImage_1_IVT:setTag(275)
LoginImage_1_IVT:setCascadeColorEnabled(true)
LoginImage_1_IVT:setCascadeOpacityEnabled(true)
LoginImage_1_IVT:setPosition(537.9985, 555.0021)
layout = ccui.LayoutComponent:bindLayoutComponent(LoginImage_1_IVT)
layout:setSize({width = 436.0000, height = 116.0000})
layout:setLeftMargin(319.9985)
layout:setRightMargin(-755.9985)
layout:setTopMargin(-613.0021)
layout:setBottomMargin(497.0021)
Bg:addChild(LoginImage_1_IVT)

--Create LoginImage_2_IVT
local LoginImage_2_IVT = ccui.ImageView:create()
LoginImage_2_IVT:ignoreContentAdaptWithSize(false)
LoginImage_2_IVT:loadTexture("03_08_NewWelfare/picture_031_zh_CN.png", 1)
LoginImage_2_IVT:setLayoutComponentEnabled(true)
LoginImage_2_IVT:setName("LoginImage_2_IVT")
LoginImage_2_IVT:setTag(276)
LoginImage_2_IVT:setCascadeColorEnabled(true)
LoginImage_2_IVT:setCascadeOpacityEnabled(true)
LoginImage_2_IVT:setPosition(544.9998, 479.9995)
layout = ccui.LayoutComponent:bindLayoutComponent(LoginImage_2_IVT)
layout:setSize({width = 286.0000, height = 30.0000})
layout:setLeftMargin(401.9998)
layout:setRightMargin(-687.9998)
layout:setTopMargin(-494.9995)
layout:setBottomMargin(464.9995)
Bg:addChild(LoginImage_2_IVT)

--Create DayNode
local DayNode=cc.Node:create()
DayNode:setName("DayNode")
DayNode:setTag(278)
DayNode:setCascadeColorEnabled(true)
DayNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode)
layout:setRightMargin(720.0000)
layout:setTopMargin(553.0000)
Layer:addChild(DayNode)

--Create DayNode_1
local DayNode_1=cc.Node:create()
DayNode_1:setName("DayNode_1")
DayNode_1:setTag(279)
DayNode_1:setCascadeColorEnabled(true)
DayNode_1:setCascadeOpacityEnabled(true)
DayNode_1:setPosition(366.9988, 381.9993)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_1)
layout:setLeftMargin(366.9988)
layout:setRightMargin(-366.9988)
layout:setTopMargin(-381.9993)
layout:setBottomMargin(381.9993)
DayNode:addChild(DayNode_1)

--Create DayNode_2
local DayNode_2=cc.Node:create()
DayNode_2:setName("DayNode_2")
DayNode_2:setTag(281)
DayNode_2:setCascadeColorEnabled(true)
DayNode_2:setCascadeOpacityEnabled(true)
DayNode_2:setPosition(490.9986, 381.9990)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_2)
layout:setLeftMargin(490.9986)
layout:setRightMargin(-490.9986)
layout:setTopMargin(-381.9990)
layout:setBottomMargin(381.9990)
DayNode:addChild(DayNode_2)

--Create DayNode_3
local DayNode_3=cc.Node:create()
DayNode_3:setName("DayNode_3")
DayNode_3:setTag(283)
DayNode_3:setCascadeColorEnabled(true)
DayNode_3:setCascadeOpacityEnabled(true)
DayNode_3:setPosition(616.9987, 381.9990)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_3)
layout:setLeftMargin(616.9987)
layout:setRightMargin(-616.9987)
layout:setTopMargin(-381.9990)
layout:setBottomMargin(381.9990)
DayNode:addChild(DayNode_3)

--Create DayNode_4
local DayNode_4=cc.Node:create()
DayNode_4:setName("DayNode_4")
DayNode_4:setTag(287)
DayNode_4:setCascadeColorEnabled(true)
DayNode_4:setCascadeOpacityEnabled(true)
DayNode_4:setPosition(362.9984, 238.9986)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_4)
layout:setLeftMargin(362.9984)
layout:setRightMargin(-362.9984)
layout:setTopMargin(-238.9986)
layout:setBottomMargin(238.9986)
DayNode:addChild(DayNode_4)

--Create DayNode_5
local DayNode_5=cc.Node:create()
DayNode_5:setName("DayNode_5")
DayNode_5:setTag(289)
DayNode_5:setCascadeColorEnabled(true)
DayNode_5:setCascadeOpacityEnabled(true)
DayNode_5:setPosition(485.9990, 238.9986)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_5)
layout:setLeftMargin(485.9990)
layout:setRightMargin(-485.9990)
layout:setTopMargin(-238.9986)
layout:setBottomMargin(238.9986)
DayNode:addChild(DayNode_5)

--Create DayNode_6
local DayNode_6=cc.Node:create()
DayNode_6:setName("DayNode_6")
DayNode_6:setTag(285)
DayNode_6:setCascadeColorEnabled(true)
DayNode_6:setCascadeOpacityEnabled(true)
DayNode_6:setPosition(610.9984, 238.9986)
layout = ccui.LayoutComponent:bindLayoutComponent(DayNode_6)
layout:setLeftMargin(610.9984)
layout:setRightMargin(-610.9984)
layout:setTopMargin(-238.9986)
layout:setBottomMargin(238.9986)
DayNode:addChild(DayNode_6)

--Create SeventhDay
local SeventhDay=cc.Node:create()
SeventhDay:setName("SeventhDay")
SeventhDay:setTag(291)
SeventhDay:setCascadeColorEnabled(true)
SeventhDay:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(SeventhDay)
layout:setRightMargin(720.0000)
layout:setTopMargin(553.0000)
Layer:addChild(SeventhDay)

--Create SeventhDayPanel
local SeventhDayPanel = ccui.Layout:create()
SeventhDayPanel:ignoreContentAdaptWithSize(false)
SeventhDayPanel:setClippingEnabled(false)
SeventhDayPanel:setBackGroundColorOpacity(102)
SeventhDayPanel:setTouchEnabled(true);
SeventhDayPanel:setLayoutComponentEnabled(true)
SeventhDayPanel:setName("SeventhDayPanel")
SeventhDayPanel:setTag(292)
SeventhDayPanel:setCascadeColorEnabled(true)
SeventhDayPanel:setCascadeOpacityEnabled(true)
SeventhDayPanel:setAnchorPoint(0.5000, 0.5000)
SeventhDayPanel:setPosition(481.9988, 107.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(SeventhDayPanel)
layout:setSize({width = 376.0000, height = 126.0000})
layout:setLeftMargin(293.9988)
layout:setRightMargin(-669.9988)
layout:setTopMargin(-170.9998)
layout:setBottomMargin(44.9998)
SeventhDay:addChild(SeventhDayPanel)

--Create State_1
local State_1=cc.Node:create()
State_1:setName("State_1")
State_1:setTag(314)
State_1:setCascadeColorEnabled(true)
State_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(State_1)
layout:setRightMargin(376.0000)
layout:setTopMargin(126.0000)
SeventhDayPanel:addChild(State_1)

--Create Bg_1
local Bg_1 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_096.png")
Bg_1:setName("Bg_1")
Bg_1:setTag(427)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setPosition(188.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 376.0000, height = 126.0000})
layout:setRightMargin(-376.0000)
layout:setTopMargin(-126.0000)
Bg_1:setBlendFunc({src = 1, dst = 771})
State_1:addChild(Bg_1)

--Create State_2
local State_2=cc.Node:create()
State_2:setName("State_2")
State_2:setTag(315)
State_2:setCascadeColorEnabled(true)
State_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(State_2)
layout:setRightMargin(376.0000)
layout:setTopMargin(126.0000)
SeventhDayPanel:addChild(State_2)

--Create Bg_2
local Bg_2 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_101.png")
Bg_2:setName("Bg_2")
Bg_2:setTag(428)
Bg_2:setCascadeColorEnabled(true)
Bg_2:setCascadeOpacityEnabled(true)
Bg_2:setPosition(188.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_2)
layout:setSize({width = 376.0000, height = 126.0000})
layout:setRightMargin(-376.0000)
layout:setTopMargin(-126.0000)
Bg_2:setBlendFunc({src = 1, dst = 771})
State_2:addChild(Bg_2)

--Create Common
local Common=cc.Node:create()
Common:setName("Common")
Common:setTag(316)
Common:setCascadeColorEnabled(true)
Common:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Common)
layout:setRightMargin(376.0000)
layout:setTopMargin(126.0000)
SeventhDayPanel:addChild(Common)

--Create SevenDayImage_IVT
local SevenDayImage_IVT = ccui.ImageView:create()
SevenDayImage_IVT:ignoreContentAdaptWithSize(false)
SevenDayImage_IVT:loadTexture("03_08_NewWelfare/picture_029_zh_CN.png", 1)
SevenDayImage_IVT:setLayoutComponentEnabled(true)
SevenDayImage_IVT:setName("SevenDayImage_IVT")
SevenDayImage_IVT:setTag(294)
SevenDayImage_IVT:setCascadeColorEnabled(true)
SevenDayImage_IVT:setCascadeOpacityEnabled(true)
SevenDayImage_IVT:setPosition(328.0007, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SevenDayImage_IVT)
layout:setSize({width = 134.0000, height = 74.0000})
layout:setLeftMargin(261.0007)
layout:setRightMargin(-395.0007)
layout:setTopMargin(-137.0000)
layout:setBottomMargin(63.0000)
Common:addChild(SevenDayImage_IVT)

--Create ResIcon
local ResIcon = ccui.ImageView:create()
ResIcon:ignoreContentAdaptWithSize(false)
ResIcon:loadTexture("Default/ImageFile.png", 1)
ResIcon:setScale9Enabled(true)
ResIcon:setCapInsets({x = 0, y = 0, width = 46, height = 46})
ResIcon:setLayoutComponentEnabled(true)
ResIcon:setName("ResIcon")
ResIcon:setTag(296)
ResIcon:setCascadeColorEnabled(true)
ResIcon:setCascadeOpacityEnabled(true)
ResIcon:setPosition(178.9997, 63.0000)
ResIcon:setScaleX(0.8000)
ResIcon:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(ResIcon)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(128.9997)
layout:setRightMargin(-228.9997)
layout:setTopMargin(-113.0000)
layout:setBottomMargin(13.0000)
Common:addChild(ResIcon)

--Create ResNum
local ResNum = ccui.Text:create()
ResNum:ignoreContentAdaptWithSize(true)
ResNum:setTextAreaSize({width = 0, height = 0})
ResNum:setFontName("font/Font003.ttf")
ResNum:setFontSize(24)
ResNum:setString([[1000]])
ResNum:setTextVerticalAlignment(1)
ResNum:setLayoutComponentEnabled(true)
ResNum:setName("ResNum")
ResNum:setTag(297)
ResNum:setCascadeColorEnabled(true)
ResNum:setCascadeOpacityEnabled(true)
ResNum:setAnchorPoint(1.0000, 0.5000)
ResNum:setPosition(210.9995, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ResNum)
layout:setSize({width = 50.0000, height = 28.0000})
layout:setLeftMargin(160.9995)
layout:setRightMargin(-210.9995)
layout:setTopMargin(-55.0000)
layout:setBottomMargin(27.0000)
Common:addChild(ResNum)

--Create State_3
local State_3=cc.Node:create()
State_3:setName("State_3")
State_3:setTag(317)
State_3:setCascadeColorEnabled(true)
State_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(State_3)
layout:setRightMargin(376.0000)
layout:setTopMargin(126.0000)
SeventhDayPanel:addChild(State_3)

--Create Bg_3
local Bg_3 = cc.Sprite:createWithSpriteFrameName("03_08_NewWelfare/frame_102.png")
Bg_3:setName("Bg_3")
Bg_3:setTag(429)
Bg_3:setCascadeColorEnabled(true)
Bg_3:setCascadeOpacityEnabled(true)
Bg_3:setPosition(188.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_3)
layout:setSize({width = 376.0000, height = 126.0000})
layout:setRightMargin(-376.0000)
layout:setTopMargin(-126.0000)
Bg_3:setBlendFunc({src = 1, dst = 771})
State_3:addChild(Bg_3)

--Create ReceivedTipIcpn
local ReceivedTipIcpn = ccui.ImageView:create()
ReceivedTipIcpn:ignoreContentAdaptWithSize(false)
ReceivedTipIcpn:loadTexture("03_08_NewWelfare/icon_057.png", 1)
ReceivedTipIcpn:setLayoutComponentEnabled(true)
ReceivedTipIcpn:setName("ReceivedTipIcpn")
ReceivedTipIcpn:setTag(318)
ReceivedTipIcpn:setCascadeColorEnabled(true)
ReceivedTipIcpn:setCascadeOpacityEnabled(true)
ReceivedTipIcpn:setPosition(188.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ReceivedTipIcpn)
layout:setSize({width = 54.0000, height = 54.0000})
layout:setLeftMargin(161.0000)
layout:setRightMargin(-215.0000)
layout:setTopMargin(-90.0000)
layout:setBottomMargin(36.0000)
State_3:addChild(ReceivedTipIcpn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

