--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
"ui/01_07_Sitting/01_07_Sitting_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 718.0000, height = 420.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(261)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(718.0000)
layout:setTopMargin(420.0000)
Layer:addChild(Bg)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(262)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
InteractionPopups:setAnchorPoint(0.5000, 0.5000)
InteractionPopups:setPosition(360.0000, 209.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 718.0000, height = 420.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(-719.0000)
layout:setTopMargin(-419.0000)
layout:setBottomMargin(-1.0000)
Bg:addChild(InteractionPopups)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg_1:setScale9Enabled(true)
Bg_1:setCapInsets({x = 17, y = 138, width = 20, height = 144})
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(263)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setPosition(359.9999, 209.0039)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 718.0000, height = 420.0000})
layout:setLeftMargin(0.9999)
layout:setRightMargin(-718.9999)
layout:setTopMargin(-419.0039)
layout:setBottomMargin(-0.9961)
Bg:addChild(Bg_1)

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(252)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(718.0000)
layout:setTopMargin(420.0000)
Layer:addChild(Middle)

--Create TipTitleText_TT
local TipTitleText_TT = ccui.Text:create()
TipTitleText_TT:ignoreContentAdaptWithSize(true)
TipTitleText_TT:setTextAreaSize({width = 0, height = 0})
TipTitleText_TT:setFontName("font/Font001.ttf")
TipTitleText_TT:setFontSize(32)
TipTitleText_TT:setString([[语言设置]])
TipTitleText_TT:setTextHorizontalAlignment(1)
TipTitleText_TT:setTextVerticalAlignment(1)
TipTitleText_TT:setLayoutComponentEnabled(true)
TipTitleText_TT:setName("TipTitleText_TT")
TipTitleText_TT:setTag(253)
TipTitleText_TT:setCascadeColorEnabled(true)
TipTitleText_TT:setCascadeOpacityEnabled(true)
TipTitleText_TT:setPosition(360.0000, 379.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TipTitleText_TT)
layout:setSize({width = 131.0000, height = 42.0000})
layout:setLeftMargin(294.5000)
layout:setRightMargin(-425.5000)
layout:setTopMargin(-400.0000)
layout:setBottomMargin(358.0000)
Middle:addChild(TipTitleText_TT)

--Create Language_1
local Language_1=cc.Node:create()
Language_1:setName("Language_1")
Language_1:setTag(515)
Language_1:setCascadeColorEnabled(true)
Language_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Language_1)
Middle:addChild(Language_1)

--Create LanguageCheckBox_1
local LanguageCheckBox_1 = ccui.CheckBox:create()
LanguageCheckBox_1:ignoreContentAdaptWithSize(false)
LanguageCheckBox_1:loadTextureBackGround("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_1:loadTextureBackGroundSelected("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_1:loadTextureBackGroundDisabled("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_1:loadTextureFrontCross("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_1:loadTextureFrontCrossDisabled("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_1:setSelected(true)
LanguageCheckBox_1:setLayoutComponentEnabled(true)
LanguageCheckBox_1:setName("LanguageCheckBox_1")
LanguageCheckBox_1:setTag(516)
LanguageCheckBox_1:setCascadeColorEnabled(true)
LanguageCheckBox_1:setCascadeOpacityEnabled(true)
LanguageCheckBox_1:setPosition(100.0000, 260.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageCheckBox_1)
layout:setSize({width = 52.0000, height = 48.0000})
layout:setLeftMargin(74.0000)
layout:setRightMargin(-126.0000)
layout:setTopMargin(-284.0001)
layout:setBottomMargin(236.0001)
Language_1:addChild(LanguageCheckBox_1)

--Create LanguageText_1_O
local LanguageText_1_O = ccui.Text:create()
LanguageText_1_O:ignoreContentAdaptWithSize(true)
LanguageText_1_O:setTextAreaSize({width = 0, height = 0})
LanguageText_1_O:setFontName("font/Default.ttf")
LanguageText_1_O:setFontSize(28)
LanguageText_1_O:setString([[繁體中文]])
LanguageText_1_O:setLayoutComponentEnabled(true)
LanguageText_1_O:setName("LanguageText_1_O")
LanguageText_1_O:setTag(254)
LanguageText_1_O:setCascadeColorEnabled(true)
LanguageText_1_O:setCascadeOpacityEnabled(true)
LanguageText_1_O:setAnchorPoint(0.0000, 0.5000)
LanguageText_1_O:setPosition(152.5000, 260.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageText_1_O)
layout:setSize({width = 115.0000, height = 37.0000})
layout:setLeftMargin(152.5000)
layout:setRightMargin(-267.5000)
layout:setTopMargin(-278.5000)
layout:setBottomMargin(241.5000)
Language_1:addChild(LanguageText_1_O)

--Create Language_2
local Language_2=cc.Node:create()
Language_2:setName("Language_2")
Language_2:setTag(517)
Language_2:setCascadeColorEnabled(true)
Language_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Language_2)
Middle:addChild(Language_2)

--Create LanguageCheckBox_2
local LanguageCheckBox_2 = ccui.CheckBox:create()
LanguageCheckBox_2:ignoreContentAdaptWithSize(false)
LanguageCheckBox_2:loadTextureBackGround("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_2:loadTextureBackGroundSelected("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_2:loadTextureBackGroundDisabled("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_2:loadTextureFrontCross("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_2:loadTextureFrontCrossDisabled("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_2:setSelected(true)
LanguageCheckBox_2:setLayoutComponentEnabled(true)
LanguageCheckBox_2:setName("LanguageCheckBox_2")
LanguageCheckBox_2:setTag(518)
LanguageCheckBox_2:setCascadeColorEnabled(true)
LanguageCheckBox_2:setCascadeOpacityEnabled(true)
LanguageCheckBox_2:setPosition(456.9969, 260.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageCheckBox_2)
layout:setSize({width = 52.0000, height = 48.0000})
layout:setLeftMargin(430.9969)
layout:setRightMargin(-482.9969)
layout:setTopMargin(-284.0000)
layout:setBottomMargin(236.0000)
Language_2:addChild(LanguageCheckBox_2)

--Create LanguageText_2_O
local LanguageText_2_O = ccui.Text:create()
LanguageText_2_O:ignoreContentAdaptWithSize(true)
LanguageText_2_O:setTextAreaSize({width = 0, height = 0})
LanguageText_2_O:setFontName("font/Default.ttf")
LanguageText_2_O:setFontSize(28)
LanguageText_2_O:setString([[简体中文]])
LanguageText_2_O:setLayoutComponentEnabled(true)
LanguageText_2_O:setName("LanguageText_2_O")
LanguageText_2_O:setTag(519)
LanguageText_2_O:setCascadeColorEnabled(true)
LanguageText_2_O:setCascadeOpacityEnabled(true)
LanguageText_2_O:setAnchorPoint(0.0000, 0.5000)
LanguageText_2_O:setPosition(509.5000, 260.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageText_2_O)
layout:setSize({width = 115.0000, height = 37.0000})
layout:setLeftMargin(509.5000)
layout:setRightMargin(-624.5000)
layout:setTopMargin(-278.5000)
layout:setBottomMargin(241.5000)
Language_2:addChild(LanguageText_2_O)

--Create Language_3
local Language_3=cc.Node:create()
Language_3:setName("Language_3")
Language_3:setTag(520)
Language_3:setCascadeColorEnabled(true)
Language_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Language_3)
Middle:addChild(Language_3)

--Create LanguageCheckBox_3
local LanguageCheckBox_3 = ccui.CheckBox:create()
LanguageCheckBox_3:ignoreContentAdaptWithSize(false)
LanguageCheckBox_3:loadTextureBackGround("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_3:loadTextureBackGroundSelected("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_3:loadTextureBackGroundDisabled("01_07_Sitting/icon_026.png", 1)
LanguageCheckBox_3:loadTextureFrontCross("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_3:loadTextureFrontCrossDisabled("01_07_Sitting/icon_025.png", 1)
LanguageCheckBox_3:setSelected(true)
LanguageCheckBox_3:setLayoutComponentEnabled(true)
LanguageCheckBox_3:setName("LanguageCheckBox_3")
LanguageCheckBox_3:setTag(521)
LanguageCheckBox_3:setCascadeColorEnabled(true)
LanguageCheckBox_3:setCascadeOpacityEnabled(true)
LanguageCheckBox_3:setPosition(99.9976, 140.0012)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageCheckBox_3)
layout:setSize({width = 52.0000, height = 48.0000})
layout:setLeftMargin(73.9976)
layout:setRightMargin(-125.9976)
layout:setTopMargin(-164.0012)
layout:setBottomMargin(116.0012)
Language_3:addChild(LanguageCheckBox_3)

--Create LanguageText_3_O
local LanguageText_3_O = ccui.Text:create()
LanguageText_3_O:ignoreContentAdaptWithSize(true)
LanguageText_3_O:setTextAreaSize({width = 0, height = 0})
LanguageText_3_O:setFontName("font/Default.ttf")
LanguageText_3_O:setFontSize(28)
LanguageText_3_O:setString([[English]])
LanguageText_3_O:setLayoutComponentEnabled(true)
LanguageText_3_O:setName("LanguageText_3_O")
LanguageText_3_O:setTag(522)
LanguageText_3_O:setCascadeColorEnabled(true)
LanguageText_3_O:setCascadeOpacityEnabled(true)
LanguageText_3_O:setAnchorPoint(0.0000, 0.5000)
LanguageText_3_O:setPosition(152.4989, 140.0010)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageText_3_O)
layout:setSize({width = 95.0000, height = 37.0000})
layout:setLeftMargin(152.4989)
layout:setRightMargin(-247.4989)
layout:setTopMargin(-158.5010)
layout:setBottomMargin(121.5010)
Language_3:addChild(LanguageText_3_O)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

