--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_10_OperateGiftBag/03_10_OperateGiftBag_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 120.0000, height = 120.0000})

--Create GiftRes
local GiftRes=cc.Node:create()
GiftRes:setName("GiftRes")
GiftRes:setTag(58)
GiftRes:setCascadeColorEnabled(true)
GiftRes:setCascadeOpacityEnabled(true)
GiftRes:setPosition(60.0000, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GiftRes)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(60.0000)
layout:setRightMargin(60.0000)
layout:setTopMargin(60.0000)
layout:setBottomMargin(60.0000)
Layer:addChild(GiftRes)

--Create GiftResPanel
local GiftResPanel = ccui.Layout:create()
GiftResPanel:ignoreContentAdaptWithSize(false)
GiftResPanel:setClippingEnabled(false)
GiftResPanel:setBackGroundColorOpacity(102)
GiftResPanel:setTouchEnabled(true);
GiftResPanel:setLayoutComponentEnabled(true)
GiftResPanel:setName("GiftResPanel")
GiftResPanel:setTag(63)
GiftResPanel:setCascadeColorEnabled(true)
GiftResPanel:setCascadeOpacityEnabled(true)
GiftResPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(GiftResPanel)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(-60.0000)
layout:setRightMargin(-60.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(-60.0000)
GiftRes:addChild(GiftResPanel)

--Create Bg
local Bg = cc.Sprite:createWithSpriteFrameName("03_10_OperateGiftBag/frame_107.png")
Bg:setName("Bg")
Bg:setTag(437)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setSize({width = 126.0000, height = 126.0000})
layout:setLeftMargin(-63.0000)
layout:setRightMargin(-63.0000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(-63.0000)
Bg:setBlendFunc({src = 1, dst = 771})
GiftRes:addChild(Bg)

--Create GiftResIcon
local GiftResIcon = ccui.ImageView:create()
GiftResIcon:ignoreContentAdaptWithSize(false)
GiftResIcon:loadTexture("Default/ImageFile.png", 1)
GiftResIcon:setLayoutComponentEnabled(true)
GiftResIcon:setName("GiftResIcon")
GiftResIcon:setTag(60)
GiftResIcon:setCascadeColorEnabled(true)
GiftResIcon:setCascadeOpacityEnabled(true)
GiftResIcon:setScaleX(0.8000)
GiftResIcon:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(GiftResIcon)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
GiftRes:addChild(GiftResIcon)

--Create GiftResNum
local GiftResNum = ccui.Text:create()
GiftResNum:ignoreContentAdaptWithSize(true)
GiftResNum:setTextAreaSize({width = 0, height = 0})
GiftResNum:setFontName("font/Font003.ttf")
GiftResNum:setFontSize(24)
GiftResNum:setString([[1000]])
GiftResNum:setTextHorizontalAlignment(2)
GiftResNum:setTextVerticalAlignment(1)
GiftResNum:setLayoutComponentEnabled(true)
GiftResNum:setName("GiftResNum")
GiftResNum:setTag(61)
GiftResNum:setCascadeColorEnabled(true)
GiftResNum:setCascadeOpacityEnabled(true)
GiftResNum:setAnchorPoint(0.9000, 0.5000)
GiftResNum:setPosition(40.0000, -31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GiftResNum)
layout:setSize({width = 50.0000, height = 28.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-45.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(-45.0000)
GiftRes:addChild(GiftResNum)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

