--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_02_GuessSize/02_02_GuessSize_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 48.0000, height = 98.0000})

--Create SelectedLeopardCell
local SelectedLeopardCell=cc.Node:create()
SelectedLeopardCell:setName("SelectedLeopardCell")
SelectedLeopardCell:setTag(1168)
SelectedLeopardCell:setCascadeColorEnabled(true)
SelectedLeopardCell:setCascadeOpacityEnabled(true)
SelectedLeopardCell:setPosition(24.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SelectedLeopardCell)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(24.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(49.0000)
Layer:addChild(SelectedLeopardCell)

--Create SelectedLeopardBg
local SelectedLeopardBg = cc.Sprite:createWithSpriteFrameName("02_02_GuessSize/frame_158.png")
SelectedLeopardBg:setName("SelectedLeopardBg")
SelectedLeopardBg:setTag(1166)
SelectedLeopardBg:setCascadeColorEnabled(true)
SelectedLeopardBg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(SelectedLeopardBg)
layout:setSize({width = 48.0000, height = 98.0000})
layout:setLeftMargin(-24.0000)
layout:setRightMargin(-24.0000)
layout:setTopMargin(-49.0000)
layout:setBottomMargin(-49.0000)
SelectedLeopardBg:setBlendFunc({src = 1, dst = 771})
SelectedLeopardCell:addChild(SelectedLeopardBg)

--Create LeopardHeadNode
local LeopardHeadNode=cc.Node:create()
LeopardHeadNode:setName("LeopardHeadNode")
LeopardHeadNode:setTag(1167)
LeopardHeadNode:setCascadeColorEnabled(true)
LeopardHeadNode:setCascadeOpacityEnabled(true)
LeopardHeadNode:setPosition(0.0000, -20.0000)
LeopardHeadNode:setScaleX(0.4000)
LeopardHeadNode:setScaleY(0.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(LeopardHeadNode)
layout:setTopMargin(20.0000)
layout:setBottomMargin(-20.0000)
SelectedLeopardCell:addChild(LeopardHeadNode)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

