--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 288.0000, height = 32.0000})

--Create SizeResultNode
local SizeResultNode=cc.Node:create()
SizeResultNode:setName("SizeResultNode")
SizeResultNode:setTag(219)
SizeResultNode:setCascadeColorEnabled(true)
SizeResultNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResultNode)
layout:setRightMargin(288.0000)
layout:setTopMargin(32.0000)
Layer:addChild(SizeResultNode)

--Create SizeResult_1
local SizeResult_1=cc.Node:create()
SizeResult_1:setName("SizeResult_1")
SizeResult_1:setTag(251)
SizeResult_1:setCascadeColorEnabled(true)
SizeResult_1:setCascadeOpacityEnabled(true)
SizeResult_1:setPosition(-16.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_1)
layout:setLeftMargin(-16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_1)

--Create SizeResult_2
local SizeResult_2=cc.Node:create()
SizeResult_2:setName("SizeResult_2")
SizeResult_2:setTag(252)
SizeResult_2:setCascadeColorEnabled(true)
SizeResult_2:setCascadeOpacityEnabled(true)
SizeResult_2:setPosition(16.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_2)
layout:setLeftMargin(16.0000)
layout:setRightMargin(-16.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_2)

--Create SizeResult_3
local SizeResult_3=cc.Node:create()
SizeResult_3:setName("SizeResult_3")
SizeResult_3:setTag(253)
SizeResult_3:setCascadeColorEnabled(true)
SizeResult_3:setCascadeOpacityEnabled(true)
SizeResult_3:setPosition(48.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_3)
layout:setLeftMargin(48.0000)
layout:setRightMargin(-48.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_3)

--Create SizeResult_4
local SizeResult_4=cc.Node:create()
SizeResult_4:setName("SizeResult_4")
SizeResult_4:setTag(254)
SizeResult_4:setCascadeColorEnabled(true)
SizeResult_4:setCascadeOpacityEnabled(true)
SizeResult_4:setPosition(80.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_4)
layout:setLeftMargin(80.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_4)

--Create SizeResult_5
local SizeResult_5=cc.Node:create()
SizeResult_5:setName("SizeResult_5")
SizeResult_5:setTag(255)
SizeResult_5:setCascadeColorEnabled(true)
SizeResult_5:setCascadeOpacityEnabled(true)
SizeResult_5:setPosition(112.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_5)
layout:setLeftMargin(112.0000)
layout:setRightMargin(-112.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_5)

--Create SizeResult_6
local SizeResult_6=cc.Node:create()
SizeResult_6:setName("SizeResult_6")
SizeResult_6:setTag(256)
SizeResult_6:setCascadeColorEnabled(true)
SizeResult_6:setCascadeOpacityEnabled(true)
SizeResult_6:setPosition(144.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_6)
layout:setLeftMargin(144.0000)
layout:setRightMargin(-144.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_6)

--Create SizeResult_7
local SizeResult_7=cc.Node:create()
SizeResult_7:setName("SizeResult_7")
SizeResult_7:setTag(257)
SizeResult_7:setCascadeColorEnabled(true)
SizeResult_7:setCascadeOpacityEnabled(true)
SizeResult_7:setPosition(176.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_7)
layout:setLeftMargin(176.0000)
layout:setRightMargin(-176.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_7)

--Create SizeResult_8
local SizeResult_8=cc.Node:create()
SizeResult_8:setName("SizeResult_8")
SizeResult_8:setTag(258)
SizeResult_8:setCascadeColorEnabled(true)
SizeResult_8:setCascadeOpacityEnabled(true)
SizeResult_8:setPosition(208.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_8)
layout:setLeftMargin(208.0000)
layout:setRightMargin(-208.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_8)

--Create SizeResult_9
local SizeResult_9=cc.Node:create()
SizeResult_9:setName("SizeResult_9")
SizeResult_9:setTag(259)
SizeResult_9:setCascadeColorEnabled(true)
SizeResult_9:setCascadeOpacityEnabled(true)
SizeResult_9:setPosition(240.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_9)
layout:setLeftMargin(240.0000)
layout:setRightMargin(-240.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_9)

--Create SizeResult_10
local SizeResult_10=cc.Node:create()
SizeResult_10:setName("SizeResult_10")
SizeResult_10:setTag(260)
SizeResult_10:setCascadeColorEnabled(true)
SizeResult_10:setCascadeOpacityEnabled(true)
SizeResult_10:setPosition(272.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_10)
layout:setLeftMargin(272.0000)
layout:setRightMargin(-272.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_10)

--Create SizeResult_11
local SizeResult_11=cc.Node:create()
SizeResult_11:setName("SizeResult_11")
SizeResult_11:setTag(261)
SizeResult_11:setCascadeColorEnabled(true)
SizeResult_11:setCascadeOpacityEnabled(true)
SizeResult_11:setPosition(304.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_11)
layout:setLeftMargin(304.0000)
layout:setRightMargin(-304.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode:addChild(SizeResult_11)

--Create SizeResultNode_1
local SizeResultNode_1=cc.Node:create()
SizeResultNode_1:setName("SizeResultNode_1")
SizeResultNode_1:setTag(262)
SizeResultNode_1:setCascadeColorEnabled(true)
SizeResultNode_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResultNode_1)
layout:setRightMargin(288.0000)
layout:setTopMargin(32.0000)
Layer:addChild(SizeResultNode_1)

--Create SizeResult_1_0
local SizeResult_1_0=cc.Node:create()
SizeResult_1_0:setName("SizeResult_1_0")
SizeResult_1_0:setTag(263)
SizeResult_1_0:setCascadeColorEnabled(true)
SizeResult_1_0:setCascadeOpacityEnabled(true)
SizeResult_1_0:setPosition(-16.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_1_0)
layout:setLeftMargin(-16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_1_0)

--Create SizeResult_2_0
local SizeResult_2_0=cc.Node:create()
SizeResult_2_0:setName("SizeResult_2_0")
SizeResult_2_0:setTag(264)
SizeResult_2_0:setCascadeColorEnabled(true)
SizeResult_2_0:setCascadeOpacityEnabled(true)
SizeResult_2_0:setPosition(16.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_2_0)
layout:setLeftMargin(16.0000)
layout:setRightMargin(-16.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_2_0)

--Create SizeResult_3_0
local SizeResult_3_0=cc.Node:create()
SizeResult_3_0:setName("SizeResult_3_0")
SizeResult_3_0:setTag(265)
SizeResult_3_0:setCascadeColorEnabled(true)
SizeResult_3_0:setCascadeOpacityEnabled(true)
SizeResult_3_0:setPosition(48.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_3_0)
layout:setLeftMargin(48.0000)
layout:setRightMargin(-48.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_3_0)

--Create SizeResult_4_0
local SizeResult_4_0=cc.Node:create()
SizeResult_4_0:setName("SizeResult_4_0")
SizeResult_4_0:setTag(266)
SizeResult_4_0:setCascadeColorEnabled(true)
SizeResult_4_0:setCascadeOpacityEnabled(true)
SizeResult_4_0:setPosition(80.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_4_0)
layout:setLeftMargin(80.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_4_0)

--Create SizeResult_5_0
local SizeResult_5_0=cc.Node:create()
SizeResult_5_0:setName("SizeResult_5_0")
SizeResult_5_0:setTag(267)
SizeResult_5_0:setCascadeColorEnabled(true)
SizeResult_5_0:setCascadeOpacityEnabled(true)
SizeResult_5_0:setPosition(112.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_5_0)
layout:setLeftMargin(112.0000)
layout:setRightMargin(-112.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_5_0)

--Create SizeResult_6_0
local SizeResult_6_0=cc.Node:create()
SizeResult_6_0:setName("SizeResult_6_0")
SizeResult_6_0:setTag(268)
SizeResult_6_0:setCascadeColorEnabled(true)
SizeResult_6_0:setCascadeOpacityEnabled(true)
SizeResult_6_0:setPosition(144.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_6_0)
layout:setLeftMargin(144.0000)
layout:setRightMargin(-144.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_6_0)

--Create SizeResult_7_0
local SizeResult_7_0=cc.Node:create()
SizeResult_7_0:setName("SizeResult_7_0")
SizeResult_7_0:setTag(269)
SizeResult_7_0:setCascadeColorEnabled(true)
SizeResult_7_0:setCascadeOpacityEnabled(true)
SizeResult_7_0:setPosition(176.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_7_0)
layout:setLeftMargin(176.0000)
layout:setRightMargin(-176.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_7_0)

--Create SizeResult_8_0
local SizeResult_8_0=cc.Node:create()
SizeResult_8_0:setName("SizeResult_8_0")
SizeResult_8_0:setTag(270)
SizeResult_8_0:setCascadeColorEnabled(true)
SizeResult_8_0:setCascadeOpacityEnabled(true)
SizeResult_8_0:setPosition(208.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_8_0)
layout:setLeftMargin(208.0000)
layout:setRightMargin(-208.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_8_0)

--Create SizeResult_9_0
local SizeResult_9_0=cc.Node:create()
SizeResult_9_0:setName("SizeResult_9_0")
SizeResult_9_0:setTag(271)
SizeResult_9_0:setCascadeColorEnabled(true)
SizeResult_9_0:setCascadeOpacityEnabled(true)
SizeResult_9_0:setPosition(240.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_9_0)
layout:setLeftMargin(240.0000)
layout:setRightMargin(-240.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_9_0)

--Create SizeResult_10_0
local SizeResult_10_0=cc.Node:create()
SizeResult_10_0:setName("SizeResult_10_0")
SizeResult_10_0:setTag(272)
SizeResult_10_0:setCascadeColorEnabled(true)
SizeResult_10_0:setCascadeOpacityEnabled(true)
SizeResult_10_0:setPosition(272.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_10_0)
layout:setLeftMargin(272.0000)
layout:setRightMargin(-272.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_10_0)

--Create SizeResult_11_0
local SizeResult_11_0=cc.Node:create()
SizeResult_11_0:setName("SizeResult_11_0")
SizeResult_11_0:setTag(273)
SizeResult_11_0:setCascadeColorEnabled(true)
SizeResult_11_0:setCascadeOpacityEnabled(true)
SizeResult_11_0:setPosition(304.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SizeResult_11_0)
layout:setLeftMargin(304.0000)
layout:setRightMargin(-304.0000)
layout:setTopMargin(-16.0000)
layout:setBottomMargin(16.0000)
SizeResultNode_1:addChild(SizeResult_11_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

