--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_04_DiceBaby/02_04_DiceBaby_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 338.0000, height = 64.0000})

--Create MainDiceBabyHintBg
local MainDiceBabyHintBg = cc.Sprite:createWithSpriteFrameName("02_04_DiceBaby/frame_206.png")
MainDiceBabyHintBg:setName("MainDiceBabyHintBg")
MainDiceBabyHintBg:setTag(1156)
MainDiceBabyHintBg:setCascadeColorEnabled(true)
MainDiceBabyHintBg:setCascadeOpacityEnabled(true)
MainDiceBabyHintBg:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(MainDiceBabyHintBg)
layout:setPercentWidth(0.9586)
layout:setPercentHeight(1.0000)
layout:setSize({width = 324.0000, height = 64.0000})
layout:setRightMargin(14.0000)
MainDiceBabyHintBg:setBlendFunc({src = 1, dst = 771})
Layer:addChild(MainDiceBabyHintBg)

--Create MainDiceBabyHintText_1_TT
local MainDiceBabyHintText_1_TT = ccui.Text:create()
MainDiceBabyHintText_1_TT:ignoreContentAdaptWithSize(true)
MainDiceBabyHintText_1_TT:setTextAreaSize({width = 0, height = 0})
MainDiceBabyHintText_1_TT:setFontName("font/Default.ttf")
MainDiceBabyHintText_1_TT:setFontSize(22)
MainDiceBabyHintText_1_TT:setString([[您在骰宝模式里的庄家被抢]])
MainDiceBabyHintText_1_TT:setLayoutComponentEnabled(true)
MainDiceBabyHintText_1_TT:setName("MainDiceBabyHintText_1_TT")
MainDiceBabyHintText_1_TT:setTag(1158)
MainDiceBabyHintText_1_TT:setCascadeColorEnabled(true)
MainDiceBabyHintText_1_TT:setCascadeOpacityEnabled(true)
MainDiceBabyHintText_1_TT:setAnchorPoint(0.0000, 0.5000)
MainDiceBabyHintText_1_TT:setPosition(7.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(MainDiceBabyHintText_1_TT)
layout:setPositionPercentX(0.0216)
layout:setPositionPercentY(0.4688)
layout:setPercentWidth(0.8241)
layout:setPercentHeight(0.4531)
layout:setSize({width = 267.0000, height = 29.0000})
layout:setLeftMargin(7.0000)
layout:setRightMargin(50.0000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(15.5000)
MainDiceBabyHintBg:addChild(MainDiceBabyHintText_1_TT)

--Create MainDiceBabyHintText_2_TT
local MainDiceBabyHintText_2_TT = ccui.Text:create()
MainDiceBabyHintText_2_TT:ignoreContentAdaptWithSize(true)
MainDiceBabyHintText_2_TT:setTextAreaSize({width = 0, height = 0})
MainDiceBabyHintText_2_TT:setFontName("font/Default.ttf")
MainDiceBabyHintText_2_TT:setFontSize(22)
MainDiceBabyHintText_2_TT:setString([[骰宝模式本金不足,已下庄]])
MainDiceBabyHintText_2_TT:setLayoutComponentEnabled(true)
MainDiceBabyHintText_2_TT:setName("MainDiceBabyHintText_2_TT")
MainDiceBabyHintText_2_TT:setTag(237)
MainDiceBabyHintText_2_TT:setCascadeColorEnabled(true)
MainDiceBabyHintText_2_TT:setCascadeOpacityEnabled(true)
MainDiceBabyHintText_2_TT:setAnchorPoint(0.0000, 0.5000)
MainDiceBabyHintText_2_TT:setPosition(7.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(MainDiceBabyHintText_2_TT)
layout:setPositionPercentX(0.0216)
layout:setPositionPercentY(0.4688)
layout:setPercentWidth(0.7716)
layout:setPercentHeight(0.4531)
layout:setSize({width = 250.0000, height = 29.0000})
layout:setLeftMargin(7.0000)
layout:setRightMargin(67.0000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(15.5000)
MainDiceBabyHintBg:addChild(MainDiceBabyHintText_2_TT)

--Create MainDiceBabyHintText_3_TT
local MainDiceBabyHintText_3_TT = ccui.Text:create()
MainDiceBabyHintText_3_TT:ignoreContentAdaptWithSize(true)
MainDiceBabyHintText_3_TT:setTextAreaSize({width = 0, height = 0})
MainDiceBabyHintText_3_TT:setFontName("font/Default.ttf")
MainDiceBabyHintText_3_TT:setFontSize(22)
MainDiceBabyHintText_3_TT:setString([[骰宝模式上庄时间结束,已下庄]])
MainDiceBabyHintText_3_TT:setLayoutComponentEnabled(true)
MainDiceBabyHintText_3_TT:setName("MainDiceBabyHintText_3_TT")
MainDiceBabyHintText_3_TT:setTag(238)
MainDiceBabyHintText_3_TT:setCascadeColorEnabled(true)
MainDiceBabyHintText_3_TT:setCascadeOpacityEnabled(true)
MainDiceBabyHintText_3_TT:setAnchorPoint(0.0000, 0.5000)
MainDiceBabyHintText_3_TT:setPosition(7.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(MainDiceBabyHintText_3_TT)
layout:setPositionPercentX(0.0216)
layout:setPositionPercentY(0.4688)
layout:setPercentWidth(0.9074)
layout:setPercentHeight(0.4531)
layout:setSize({width = 294.0000, height = 29.0000})
layout:setLeftMargin(7.0000)
layout:setRightMargin(23.0000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(15.5000)
MainDiceBabyHintBg:addChild(MainDiceBabyHintText_3_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

