--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
"ui/01_10_Mail/01_10_Mail_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 718.0000, height = 420.0000})

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(252)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(718.0000)
layout:setTopMargin(420.0000)
Layer:addChild(Middle)

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(261)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
Middle:addChild(Bg)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg_1:setScale9Enabled(true)
Bg_1:setCapInsets({x = 17, y = 88, width = 20, height = 194})
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(263)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setAnchorPoint(0.0000, 0.0000)
Bg_1:setPosition(0.0000, -0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 718.0000, height = 420.0000})
layout:setRightMargin(-718.0000)
layout:setTopMargin(-419.9999)
layout:setBottomMargin(-0.0001)
Bg:addChild(Bg_1)

--Create TitleText_TT
local TitleText_TT = ccui.Text:create()
TitleText_TT:ignoreContentAdaptWithSize(true)
TitleText_TT:setTextAreaSize({width = 0, height = 0})
TitleText_TT:setFontName("font/Font001.ttf")
TitleText_TT:setFontSize(32)
TitleText_TT:setString([[提示]])
TitleText_TT:setTextHorizontalAlignment(1)
TitleText_TT:setTextVerticalAlignment(1)
TitleText_TT:enableShadow({r = 34, g = 31, b = 86, a = 255}, {width = 0, height = -2}, 0)
TitleText_TT:setLayoutComponentEnabled(true)
TitleText_TT:setName("TitleText_TT")
TitleText_TT:setTag(105)
TitleText_TT:setCascadeColorEnabled(true)
TitleText_TT:setCascadeOpacityEnabled(true)
TitleText_TT:setPosition(359.0000, 379.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText_TT)
layout:setSize({width = 67.0000, height = 42.0000})
layout:setLeftMargin(325.5000)
layout:setRightMargin(-392.5000)
layout:setTopMargin(-400.0000)
layout:setBottomMargin(358.0000)
Middle:addChild(TitleText_TT)

--Create ContentText_1_TT
local ContentText_1_TT = ccui.Text:create()
ContentText_1_TT:ignoreContentAdaptWithSize(false)
ContentText_1_TT:setFontName("font/Default.ttf")
ContentText_1_TT:setFontSize(32)
ContentText_1_TT:setString([[请选择上庄金额]])
ContentText_1_TT:setTextHorizontalAlignment(1)
ContentText_1_TT:setTextVerticalAlignment(2)
ContentText_1_TT:setLayoutComponentEnabled(true)
ContentText_1_TT:setName("ContentText_1_TT")
ContentText_1_TT:setTag(254)
ContentText_1_TT:setCascadeColorEnabled(true)
ContentText_1_TT:setCascadeOpacityEnabled(true)
ContentText_1_TT:setPosition(359.0000, 295.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_1_TT)
layout:setSize({width = 600.0000, height = 84.0000})
layout:setLeftMargin(59.0000)
layout:setRightMargin(-659.0000)
layout:setTopMargin(-337.0000)
layout:setBottomMargin(253.0000)
Middle:addChild(ContentText_1_TT)

--Create ContentText_2
local ContentText_2 = ccui.Text:create()
ContentText_2:ignoreContentAdaptWithSize(false)
ContentText_2:setFontName("font/Default.ttf")
ContentText_2:setFontSize(27)
ContentText_2:setString([[您还需额外支付：100万抢庄费]])
ContentText_2:setTextHorizontalAlignment(1)
ContentText_2:setLayoutComponentEnabled(true)
ContentText_2:setName("ContentText_2")
ContentText_2:setTag(1178)
ContentText_2:setCascadeColorEnabled(true)
ContentText_2:setCascadeOpacityEnabled(true)
ContentText_2:setVisible(false)
ContentText_2:setPosition(359.0000, 194.0000)
ContentText_2:setTextColor({r = 216, g = 213, b = 250})
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_2)
layout:setSize({width = 600.0000, height = 84.0000})
layout:setLeftMargin(59.0000)
layout:setRightMargin(-659.0000)
layout:setTopMargin(-236.0000)
layout:setBottomMargin(152.0000)
Middle:addChild(ContentText_2)

--Create Confirm
local Confirm=cc.Node:create()
Confirm:setName("Confirm")
Confirm:setTag(1189)
Confirm:setCascadeColorEnabled(true)
Confirm:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Confirm)
Middle:addChild(Confirm)

--Create ConfirmButton_1

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton_1 = luaScript.CreateCustomNode()
ConfirmButton_1:ignoreContentAdaptWithSize(false)
ConfirmButton_1:loadTextureNormal("01_10_Mail/button_035.png", 1)
ConfirmButton_1:loadTexturePressed("01_10_Mail/button_035.png", 1)
ConfirmButton_1:loadTextureDisabled("01_10_Mail/button_035.png", 1)
ConfirmButton_1:setTitleFontSize(14)
ConfirmButton_1:setScale9Enabled(true)
ConfirmButton_1:setCapInsets({x = 15, y = 11, width = 178, height = 76})
ConfirmButton_1:setLayoutComponentEnabled(true)
ConfirmButton_1:setName("ConfirmButton_1")
ConfirmButton_1:setTag(526)
ConfirmButton_1:setCascadeColorEnabled(true)
ConfirmButton_1:setCascadeOpacityEnabled(true)
ConfirmButton_1:setPosition(139.0000, 111.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton_1)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(35.0000)
layout:setRightMargin(-243.0000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(62.0000)

luaScript.SetDownScele(ConfirmButton_1, "0.9800")
luaScript.SetClickEffect(ConfirmButton_1, "Sound004")
luaScript.SetDownColor(ConfirmButton_1, {r = 65, g = 65, b = 70})
Confirm:addChild(ConfirmButton_1)

--Create ConfirmText_1_TT
local ConfirmText_1_TT = ccui.Text:create()
ConfirmText_1_TT:ignoreContentAdaptWithSize(true)
ConfirmText_1_TT:setTextAreaSize({width = 0, height = 0})
ConfirmText_1_TT:setFontName("font/Font001.ttf")
ConfirmText_1_TT:setFontSize(28)
ConfirmText_1_TT:setString([[1000万]])
ConfirmText_1_TT:setTextHorizontalAlignment(1)
ConfirmText_1_TT:setTextVerticalAlignment(1)
ConfirmText_1_TT:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
ConfirmText_1_TT:setLayoutComponentEnabled(true)
ConfirmText_1_TT:setName("ConfirmText_1_TT")
ConfirmText_1_TT:setTag(527)
ConfirmText_1_TT:setCascadeColorEnabled(true)
ConfirmText_1_TT:setCascadeOpacityEnabled(true)
ConfirmText_1_TT:setPosition(104.0000, 51.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmText_1_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5204)
layout:setPercentWidth(0.4760)
layout:setPercentHeight(0.3776)
layout:setSize({width = 99.0000, height = 37.0000})
layout:setLeftMargin(54.5000)
layout:setRightMargin(54.5000)
layout:setTopMargin(28.5000)
layout:setBottomMargin(32.5000)
ConfirmButton_1:addChild(ConfirmText_1_TT)

--Create ConfirmButton_2

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton_2 = luaScript.CreateCustomNode()
ConfirmButton_2:ignoreContentAdaptWithSize(false)
ConfirmButton_2:loadTextureNormal("01_10_Mail/button_035.png", 1)
ConfirmButton_2:loadTexturePressed("01_10_Mail/button_035.png", 1)
ConfirmButton_2:loadTextureDisabled("01_10_Mail/button_035.png", 1)
ConfirmButton_2:setTitleFontSize(14)
ConfirmButton_2:setScale9Enabled(true)
ConfirmButton_2:setCapInsets({x = 15, y = 11, width = 178, height = 76})
ConfirmButton_2:setLayoutComponentEnabled(true)
ConfirmButton_2:setName("ConfirmButton_2")
ConfirmButton_2:setTag(528)
ConfirmButton_2:setCascadeColorEnabled(true)
ConfirmButton_2:setCascadeOpacityEnabled(true)
ConfirmButton_2:setPosition(359.0000, 111.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton_2)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(255.0000)
layout:setRightMargin(-463.0000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(62.0000)

luaScript.SetDownScele(ConfirmButton_2, "0.9800")
luaScript.SetClickEffect(ConfirmButton_2, "Sound004")
luaScript.SetDownColor(ConfirmButton_2, {r = 65, g = 65, b = 70})
Confirm:addChild(ConfirmButton_2)

--Create ConfirmText_2_TT
local ConfirmText_2_TT = ccui.Text:create()
ConfirmText_2_TT:ignoreContentAdaptWithSize(true)
ConfirmText_2_TT:setTextAreaSize({width = 0, height = 0})
ConfirmText_2_TT:setFontName("font/Font001.ttf")
ConfirmText_2_TT:setFontSize(28)
ConfirmText_2_TT:setString([[3000万]])
ConfirmText_2_TT:setTextHorizontalAlignment(1)
ConfirmText_2_TT:setTextVerticalAlignment(1)
ConfirmText_2_TT:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
ConfirmText_2_TT:setLayoutComponentEnabled(true)
ConfirmText_2_TT:setName("ConfirmText_2_TT")
ConfirmText_2_TT:setTag(529)
ConfirmText_2_TT:setCascadeColorEnabled(true)
ConfirmText_2_TT:setCascadeOpacityEnabled(true)
ConfirmText_2_TT:setPosition(104.0000, 51.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmText_2_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5204)
layout:setPercentWidth(0.4760)
layout:setPercentHeight(0.3776)
layout:setSize({width = 99.0000, height = 37.0000})
layout:setLeftMargin(54.5000)
layout:setRightMargin(54.5000)
layout:setTopMargin(28.5000)
layout:setBottomMargin(32.5000)
ConfirmButton_2:addChild(ConfirmText_2_TT)

--Create ConfirmButton_3

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton_3 = luaScript.CreateCustomNode()
ConfirmButton_3:ignoreContentAdaptWithSize(false)
ConfirmButton_3:loadTextureNormal("01_10_Mail/button_035.png", 1)
ConfirmButton_3:loadTexturePressed("01_10_Mail/button_035.png", 1)
ConfirmButton_3:loadTextureDisabled("01_10_Mail/button_035.png", 1)
ConfirmButton_3:setTitleFontSize(14)
ConfirmButton_3:setScale9Enabled(true)
ConfirmButton_3:setCapInsets({x = 15, y = 11, width = 178, height = 76})
ConfirmButton_3:setLayoutComponentEnabled(true)
ConfirmButton_3:setName("ConfirmButton_3")
ConfirmButton_3:setTag(1190)
ConfirmButton_3:setCascadeColorEnabled(true)
ConfirmButton_3:setCascadeOpacityEnabled(true)
ConfirmButton_3:setPosition(579.0000, 111.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton_3)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(475.0000)
layout:setRightMargin(-683.0000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(62.0000)

luaScript.SetDownScele(ConfirmButton_3, "0.9800")
luaScript.SetClickEffect(ConfirmButton_3, "Sound004")
luaScript.SetDownColor(ConfirmButton_3, {r = 65, g = 65, b = 70})
Confirm:addChild(ConfirmButton_3)

--Create ConfirmText_3_TT
local ConfirmText_3_TT = ccui.Text:create()
ConfirmText_3_TT:ignoreContentAdaptWithSize(true)
ConfirmText_3_TT:setTextAreaSize({width = 0, height = 0})
ConfirmText_3_TT:setFontName("font/Font001.ttf")
ConfirmText_3_TT:setFontSize(28)
ConfirmText_3_TT:setString([[5000万]])
ConfirmText_3_TT:setTextHorizontalAlignment(1)
ConfirmText_3_TT:setTextVerticalAlignment(1)
ConfirmText_3_TT:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
ConfirmText_3_TT:setLayoutComponentEnabled(true)
ConfirmText_3_TT:setName("ConfirmText_3_TT")
ConfirmText_3_TT:setTag(1191)
ConfirmText_3_TT:setCascadeColorEnabled(true)
ConfirmText_3_TT:setCascadeOpacityEnabled(true)
ConfirmText_3_TT:setPosition(104.0000, 51.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmText_3_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5204)
layout:setPercentWidth(0.4760)
layout:setPercentHeight(0.3776)
layout:setSize({width = 99.0000, height = 37.0000})
layout:setLeftMargin(54.5000)
layout:setRightMargin(54.5000)
layout:setTopMargin(28.5000)
layout:setBottomMargin(32.5000)
ConfirmButton_3:addChild(ConfirmText_3_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

