--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_10_Mail/01_10_Mail_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 135.0000, height = 135.0000})

--Create PropNode
local PropNode=cc.Node:create()
PropNode:setName("PropNode")
PropNode:setTag(356)
PropNode:setCascadeColorEnabled(true)
PropNode:setCascadeOpacityEnabled(true)
PropNode:setPosition(67.5000, 67.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropNode)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(67.5000)
layout:setRightMargin(67.5000)
layout:setTopMargin(67.5000)
layout:setBottomMargin(67.5000)
Layer:addChild(PropNode)

--Create PropFrame
local PropFrame = cc.Sprite:createWithSpriteFrameName("01_10_Mail/frame_050.png")
PropFrame:setName("PropFrame")
PropFrame:setTag(760)
PropFrame:setCascadeColorEnabled(true)
PropFrame:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PropFrame)
layout:setSize({width = 144.0000, height = 144.0000})
layout:setLeftMargin(-72.0000)
layout:setRightMargin(-72.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(-72.0000)
PropFrame:setBlendFunc({src = 1, dst = 771})
PropNode:addChild(PropFrame)

--Create PropIcon
local PropIcon = ccui.ImageView:create()
PropIcon:ignoreContentAdaptWithSize(false)
PropIcon:loadTexture("Default/ImageFile.png", 1)
PropIcon:setLayoutComponentEnabled(true)
PropIcon:setName("PropIcon")
PropIcon:setTag(70)
PropIcon:setCascadeColorEnabled(true)
PropIcon:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PropIcon)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
PropNode:addChild(PropIcon)

--Create PropNum
local PropNum = ccui.Text:create()
PropNum:ignoreContentAdaptWithSize(true)
PropNum:setTextAreaSize({width = 0, height = 0})
PropNum:setFontName("font/Font003.ttf")
PropNum:setFontSize(28)
PropNum:setString([[523.5万]])
PropNum:setTextHorizontalAlignment(2)
PropNum:setTextVerticalAlignment(1)
PropNum:setLayoutComponentEnabled(true)
PropNum:setName("PropNum")
PropNum:setTag(361)
PropNum:setCascadeColorEnabled(true)
PropNum:setCascadeOpacityEnabled(true)
PropNum:setAnchorPoint(0.9000, 0.5000)
PropNum:setPosition(42.0000, -37.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropNum)
layout:setSize({width = 90.0000, height = 33.0000})
layout:setLeftMargin(-39.0000)
layout:setRightMargin(-51.0000)
layout:setTopMargin(20.5000)
layout:setBottomMargin(-53.5000)
PropNode:addChild(PropNum)

--Create PropPanel
local PropPanel = ccui.Layout:create()
PropPanel:ignoreContentAdaptWithSize(false)
PropPanel:setClippingEnabled(false)
PropPanel:setTouchEnabled(true);
PropPanel:setLayoutComponentEnabled(true)
PropPanel:setName("PropPanel")
PropPanel:setTag(362)
PropPanel:setCascadeColorEnabled(true)
PropPanel:setCascadeOpacityEnabled(true)
PropPanel:setAnchorPoint(0.5000, 0.5000)
PropPanel:setPosition(0.0004, 0.0000)
PropPanel:setColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(PropPanel)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-49.9996)
layout:setRightMargin(-50.0004)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
PropNode:addChild(PropPanel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

