--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_03_Subscription/03_03_Subscription_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 536.0000, height = 400.0000})

--Create SilverBuyNode
local SilverBuyNode=cc.Node:create()
SilverBuyNode:setName("SilverBuyNode")
SilverBuyNode:setTag(153)
SilverBuyNode:setCascadeColorEnabled(true)
SilverBuyNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyNode)
layout:setRightMargin(536.0000)
layout:setTopMargin(400.0000)
Layer:addChild(SilverBuyNode)

--Create SilverBuyBg
local SilverBuyBg = ccui.ImageView:create()
SilverBuyBg:ignoreContentAdaptWithSize(false)
SilverBuyBg:loadTexture("03_03_Subscription/frame_221.png", 1)
SilverBuyBg:setLayoutComponentEnabled(true)
SilverBuyBg:setName("SilverBuyBg")
SilverBuyBg:setTag(154)
SilverBuyBg:setCascadeColorEnabled(true)
SilverBuyBg:setCascadeOpacityEnabled(true)
SilverBuyBg:setPosition(268.0000, 150.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyBg)
layout:setSize({width = 536.0000, height = 300.0000})
layout:setRightMargin(-536.0000)
layout:setTopMargin(-300.0000)
SilverBuyNode:addChild(SilverBuyBg)

--Create SilverBuyImage
local SilverBuyImage = ccui.ImageView:create()
SilverBuyImage:ignoreContentAdaptWithSize(false)
SilverBuyImage:loadTexture("03_03_Subscription/icon_142.png", 1)
SilverBuyImage:setLayoutComponentEnabled(true)
SilverBuyImage:setName("SilverBuyImage")
SilverBuyImage:setTag(155)
SilverBuyImage:setCascadeColorEnabled(true)
SilverBuyImage:setCascadeOpacityEnabled(true)
SilverBuyImage:setPosition(268.0000, 300.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyImage)
layout:setSize({width = 250.0000, height = 204.0000})
layout:setLeftMargin(143.0000)
layout:setRightMargin(-393.0000)
layout:setTopMargin(-402.0000)
layout:setBottomMargin(198.0000)
SilverBuyNode:addChild(SilverBuyImage)

--Create SilverBuyText_TT
local SilverBuyText_TT = ccui.Text:create()
SilverBuyText_TT:ignoreContentAdaptWithSize(true)
SilverBuyText_TT:setTextAreaSize({width = 0, height = 0})
SilverBuyText_TT:setFontName("font/Font001.ttf")
SilverBuyText_TT:setFontSize(45)
SilverBuyText_TT:setString([[恭喜您成为白银会员]])
SilverBuyText_TT:enableShadow({r = 77, g = 93, b = 116, a = 255}, {width = 0, height = -3}, 0)
SilverBuyText_TT:setLayoutComponentEnabled(true)
SilverBuyText_TT:setName("SilverBuyText_TT")
SilverBuyText_TT:setTag(156)
SilverBuyText_TT:setCascadeColorEnabled(true)
SilverBuyText_TT:setCascadeOpacityEnabled(true)
SilverBuyText_TT:setPosition(268.0000, 184.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyText_TT)
layout:setSize({width = 407.0000, height = 59.0000})
layout:setLeftMargin(64.5000)
layout:setRightMargin(-471.5000)
layout:setTopMargin(-213.5000)
layout:setBottomMargin(154.5000)
SilverBuyNode:addChild(SilverBuyText_TT)

--Create SilverBuyIndate
local SilverBuyIndate = ccui.Text:create()
SilverBuyIndate:ignoreContentAdaptWithSize(true)
SilverBuyIndate:setTextAreaSize({width = 0, height = 0})
SilverBuyIndate:setFontName("font/Default.ttf")
SilverBuyIndate:setFontSize(28)
SilverBuyIndate:setString([[会员有效期至 2099-12-30]])
SilverBuyIndate:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
SilverBuyIndate:setLayoutComponentEnabled(true)
SilverBuyIndate:setName("SilverBuyIndate")
SilverBuyIndate:setTag(157)
SilverBuyIndate:setCascadeColorEnabled(true)
SilverBuyIndate:setCascadeOpacityEnabled(true)
SilverBuyIndate:setPosition(268.0000, 102.0000)
SilverBuyIndate:setTextColor({r = 254, g = 250, b = 255})
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyIndate)
layout:setSize({width = 330.0000, height = 37.0000})
layout:setLeftMargin(103.0000)
layout:setRightMargin(-433.0000)
layout:setTopMargin(-120.5000)
layout:setBottomMargin(83.5000)
SilverBuyNode:addChild(SilverBuyIndate)

--Create SilverBuyButton

local luaScript = require("csd.LuaScript.newButton")
local SilverBuyButton = luaScript.CreateCustomNode()
SilverBuyButton:ignoreContentAdaptWithSize(false)
SilverBuyButton:loadTextureNormal("03_03_Subscription/button_107.png", 1)
SilverBuyButton:loadTexturePressed("03_03_Subscription/button_107.png", 1)
SilverBuyButton:loadTextureDisabled("03_03_Subscription/button_107.png", 1)
SilverBuyButton:setTitleFontSize(14)
SilverBuyButton:setLayoutComponentEnabled(true)
SilverBuyButton:setName("SilverBuyButton")
SilverBuyButton:setTag(158)
SilverBuyButton:setCascadeColorEnabled(true)
SilverBuyButton:setCascadeOpacityEnabled(true)
SilverBuyButton:setPosition(268.0000, 8.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyButton)
layout:setSize({width = 242.0000, height = 98.0000})
layout:setLeftMargin(147.0000)
layout:setRightMargin(-389.0000)
layout:setTopMargin(-57.0000)
layout:setBottomMargin(-41.0000)

luaScript.SetDownScele(SilverBuyButton, "0.9800")
luaScript.SetClickEffect(SilverBuyButton, "")
luaScript.SetDownColor(SilverBuyButton, {r = 65, g = 65, b = 70})
SilverBuyNode:addChild(SilverBuyButton)

--Create SilverBuyButtonText_TT
local SilverBuyButtonText_TT = ccui.Text:create()
SilverBuyButtonText_TT:ignoreContentAdaptWithSize(true)
SilverBuyButtonText_TT:setTextAreaSize({width = 0, height = 0})
SilverBuyButtonText_TT:setFontName("font/Font001.ttf")
SilverBuyButtonText_TT:setFontSize(33)
SilverBuyButtonText_TT:setString([[我知道了]])
SilverBuyButtonText_TT:enableShadow({r = 255, g = 255, b = 255, a = 255}, {width = 0, height = -1}, 0)
SilverBuyButtonText_TT:setLayoutComponentEnabled(true)
SilverBuyButtonText_TT:setName("SilverBuyButtonText_TT")
SilverBuyButtonText_TT:setTag(159)
SilverBuyButtonText_TT:setCascadeColorEnabled(true)
SilverBuyButtonText_TT:setCascadeOpacityEnabled(true)
SilverBuyButtonText_TT:setPosition(121.0000, 55.0000)
SilverBuyButtonText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(SilverBuyButtonText_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5612)
layout:setPercentWidth(0.5537)
layout:setPercentHeight(0.4490)
layout:setSize({width = 134.0000, height = 44.0000})
layout:setLeftMargin(54.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(21.0000)
layout:setBottomMargin(33.0000)
SilverBuyButton:addChild(SilverBuyButtonText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

