--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 120.0000, height = 120.0000})

--Create Node_15
local Node_15=cc.Node:create()
Node_15:setName("Node_15")
Node_15:setTag(79)
Node_15:setCascadeColorEnabled(true)
Node_15:setCascadeOpacityEnabled(true)
Node_15:setPosition(60.0000, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_15)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(60.0000)
layout:setRightMargin(60.0000)
layout:setTopMargin(60.0000)
layout:setBottomMargin(60.0000)
Layer:addChild(Node_15)

--Create NumberBottom
local NumberBottom = ccui.ImageView:create()
NumberBottom:ignoreContentAdaptWithSize(false)
NumberBottom:loadTexture("02_01_Boast/frame_016.png", 1)
NumberBottom:setLayoutComponentEnabled(true)
NumberBottom:setName("NumberBottom")
NumberBottom:setTag(75)
NumberBottom:setCascadeColorEnabled(true)
NumberBottom:setCascadeOpacityEnabled(true)
NumberBottom:setPosition(-0.0004, 0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(NumberBottom)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(-60.0004)
layout:setRightMargin(-59.9996)
layout:setTopMargin(-60.0001)
layout:setBottomMargin(-59.9999)
Node_15:addChild(NumberBottom)

--Create NumberCheckBox
local NumberCheckBox = cc.Sprite:createWithSpriteFrameName("02_01_Boast/frame_017.png")
NumberCheckBox:setName("NumberCheckBox")
NumberCheckBox:setTag(484)
NumberCheckBox:setCascadeColorEnabled(true)
NumberCheckBox:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(NumberCheckBox)
layout:setSize({width = 142.0000, height = 142.0000})
layout:setLeftMargin(-71.0000)
layout:setRightMargin(-71.0000)
layout:setTopMargin(-71.0000)
layout:setBottomMargin(-71.0000)
NumberCheckBox:setBlendFunc({src = 1, dst = 771})
Node_15:addChild(NumberCheckBox)

--Create NumberText_1
local NumberText_1 = ccui.Text:create()
NumberText_1:ignoreContentAdaptWithSize(true)
NumberText_1:setTextAreaSize({width = 0, height = 0})
NumberText_1:setFontName("font/Font003.ttf")
NumberText_1:setFontSize(54)
NumberText_1:setString([[18]])
NumberText_1:setTextHorizontalAlignment(1)
NumberText_1:setTextVerticalAlignment(1)
NumberText_1:setLayoutComponentEnabled(true)
NumberText_1:setName("NumberText_1")
NumberText_1:setTag(77)
NumberText_1:setCascadeColorEnabled(true)
NumberText_1:setCascadeOpacityEnabled(true)
NumberText_1:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(NumberText_1)
layout:setSize({width = 54.0000, height = 63.0000})
layout:setLeftMargin(-27.0000)
layout:setRightMargin(-27.0000)
layout:setTopMargin(-31.5000)
layout:setBottomMargin(-31.5000)
Node_15:addChild(NumberText_1)

--Create NumberPanel
local NumberPanel = ccui.Layout:create()
NumberPanel:ignoreContentAdaptWithSize(false)
NumberPanel:setClippingEnabled(false)
NumberPanel:setBackGroundColorOpacity(102)
NumberPanel:setTouchEnabled(true);
NumberPanel:setLayoutComponentEnabled(true)
NumberPanel:setName("NumberPanel")
NumberPanel:setTag(78)
NumberPanel:setCascadeColorEnabled(true)
NumberPanel:setCascadeOpacityEnabled(true)
NumberPanel:setAnchorPoint(0.5000, 0.5000)
NumberPanel:setPosition(-0.0003, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(NumberPanel)
layout:setSize({width = 92.0000, height = 92.0000})
layout:setLeftMargin(-46.0003)
layout:setRightMargin(-45.9997)
layout:setTopMargin(-46.0000)
layout:setBottomMargin(-46.0000)
Node_15:addChild(NumberPanel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

