--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
"ui/00_02_Default/00_02_Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(479)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(720.0000)
layout:setTopMargin(1280.0000)
Layer:addChild(Middle)

--Create BingoImage_IVT
local BingoImage_IVT = ccui.ImageView:create()
BingoImage_IVT:ignoreContentAdaptWithSize(false)
BingoImage_IVT:loadTexture("02_01_Boast/picture_070_zh_TW.png", 1)
BingoImage_IVT:setLayoutComponentEnabled(true)
BingoImage_IVT:setName("BingoImage_IVT")
BingoImage_IVT:setTag(480)
BingoImage_IVT:setCascadeColorEnabled(true)
BingoImage_IVT:setCascadeOpacityEnabled(true)
BingoImage_IVT:setPosition(375.9995, 903.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(BingoImage_IVT)
layout:setSize({width = 404.0000, height = 206.0000})
layout:setLeftMargin(173.9995)
layout:setRightMargin(-577.9995)
layout:setTopMargin(-1006.0010)
layout:setBottomMargin(800.0009)
Middle:addChild(BingoImage_IVT)

--Create VSImage
local VSImage = ccui.ImageView:create()
VSImage:ignoreContentAdaptWithSize(false)
VSImage:loadTexture("02_01_Boast/picture_065.png", 1)
VSImage:setLayoutComponentEnabled(true)
VSImage:setName("VSImage")
VSImage:setTag(288)
VSImage:setCascadeColorEnabled(true)
VSImage:setCascadeOpacityEnabled(true)
VSImage:setPosition(364.0000, 748.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(VSImage)
layout:setSize({width = 62.0000, height = 44.0000})
layout:setLeftMargin(333.0000)
layout:setRightMargin(-395.0000)
layout:setTopMargin(-770.0000)
layout:setBottomMargin(726.0000)
Middle:addChild(VSImage)

--Create Node_21
local Node_21=cc.Node:create()
Node_21:setName("Node_21")
Node_21:setTag(436)
Node_21:setCascadeColorEnabled(true)
Node_21:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_21)
Middle:addChild(Node_21)

--Create EnoughImage_IVT
local EnoughImage_IVT = ccui.ImageView:create()
EnoughImage_IVT:ignoreContentAdaptWithSize(false)
EnoughImage_IVT:loadTexture("02_01_Boast/picture_068_zh_TW.png", 1)
EnoughImage_IVT:setLayoutComponentEnabled(true)
EnoughImage_IVT:setName("EnoughImage_IVT")
EnoughImage_IVT:setTag(286)
EnoughImage_IVT:setCascadeColorEnabled(true)
EnoughImage_IVT:setCascadeOpacityEnabled(true)
EnoughImage_IVT:setPosition(237.3339, 764.6757)
layout = ccui.LayoutComponent:bindLayoutComponent(EnoughImage_IVT)
layout:setSize({width = 176.0000, height = 132.0000})
layout:setLeftMargin(149.3339)
layout:setRightMargin(-325.3339)
layout:setTopMargin(-830.6757)
layout:setBottomMargin(698.6757)
Node_21:addChild(EnoughImage_IVT)

--Create InsufficientImage_IVT
local InsufficientImage_IVT = ccui.ImageView:create()
InsufficientImage_IVT:ignoreContentAdaptWithSize(false)
InsufficientImage_IVT:loadTexture("02_01_Boast/picture_067_zh_TW.png", 1)
InsufficientImage_IVT:setLayoutComponentEnabled(true)
InsufficientImage_IVT:setName("InsufficientImage_IVT")
InsufficientImage_IVT:setTag(287)
InsufficientImage_IVT:setCascadeColorEnabled(true)
InsufficientImage_IVT:setCascadeOpacityEnabled(true)
InsufficientImage_IVT:setPosition(490.0000, 755.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(InsufficientImage_IVT)
layout:setSize({width = 156.0000, height = 92.0000})
layout:setLeftMargin(412.0000)
layout:setRightMargin(-568.0000)
layout:setTopMargin(-801.0000)
layout:setBottomMargin(709.0000)
Node_21:addChild(InsufficientImage_IVT)

--Create bg_1
local bg_1 = cc.Sprite:createWithSpriteFrameName("02_01_Boast/frame_145.png")
bg_1:setName("bg_1")
bg_1:setTag(285)
bg_1:setCascadeColorEnabled(true)
bg_1:setCascadeOpacityEnabled(true)
bg_1:setPosition(362.0000, 755.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_1)
layout:setSize({width = 630.0000, height = 154.0000})
layout:setLeftMargin(47.0000)
layout:setRightMargin(-677.0000)
layout:setTopMargin(-832.0000)
layout:setBottomMargin(678.0000)
bg_1:setBlendFunc({src = 1, dst = 771})
Node_21:addChild(bg_1)

--Create HeadNode
local HeadNode=cc.Node:create()
HeadNode:setName("HeadNode")
HeadNode:setTag(289)
HeadNode:setCascadeColorEnabled(true)
HeadNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(HeadNode)
Middle:addChild(HeadNode)

--Create LeftHeadPanel
local LeftHeadPanel = ccui.Layout:create()
LeftHeadPanel:ignoreContentAdaptWithSize(false)
LeftHeadPanel:setClippingEnabled(false)
LeftHeadPanel:setBackGroundColorOpacity(102)
LeftHeadPanel:setTouchEnabled(true);
LeftHeadPanel:setLayoutComponentEnabled(true)
LeftHeadPanel:setName("LeftHeadPanel")
LeftHeadPanel:setTag(290)
LeftHeadPanel:setCascadeColorEnabled(true)
LeftHeadPanel:setCascadeOpacityEnabled(true)
LeftHeadPanel:setPosition(-0.0010, 274.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(LeftHeadPanel)
layout:setSize({width = 300.0000, height = 400.0000})
layout:setLeftMargin(-0.0010)
layout:setRightMargin(-299.9990)
layout:setTopMargin(-674.9999)
layout:setBottomMargin(274.9998)
HeadNode:addChild(LeftHeadPanel)

--Create RightHeadPanel
local RightHeadPanel = ccui.Layout:create()
RightHeadPanel:ignoreContentAdaptWithSize(false)
RightHeadPanel:setClippingEnabled(false)
RightHeadPanel:setBackGroundColorOpacity(102)
RightHeadPanel:setTouchEnabled(true);
RightHeadPanel:setLayoutComponentEnabled(true)
RightHeadPanel:setName("RightHeadPanel")
RightHeadPanel:setTag(291)
RightHeadPanel:setCascadeColorEnabled(true)
RightHeadPanel:setCascadeOpacityEnabled(true)
RightHeadPanel:setAnchorPoint(1.0000, 0.0000)
RightHeadPanel:setPosition(720.0000, 275.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(RightHeadPanel)
layout:setSize({width = 300.0000, height = 400.0000})
layout:setLeftMargin(420.0000)
layout:setRightMargin(-720.0000)
layout:setTopMargin(-675.0000)
layout:setBottomMargin(275.0000)
HeadNode:addChild(RightHeadPanel)

--Create delete
local delete=cc.Node:create()
delete:setName("delete")
delete:setTag(284)
delete:setCascadeColorEnabled(true)
delete:setCascadeOpacityEnabled(true)
delete:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(delete)
layout:setRightMargin(720.0000)
layout:setTopMargin(1280.0000)
Layer:addChild(delete)

--Create LanguageNode_CN
local LanguageNode_CN=cc.Node:create()
LanguageNode_CN:setName("LanguageNode_CN")
LanguageNode_CN:setTag(485)
LanguageNode_CN:setCascadeColorEnabled(true)
LanguageNode_CN:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageNode_CN)
delete:addChild(LanguageNode_CN)

--Create AwardText_1
local AwardText_1 = ccui.Text:create()
AwardText_1:ignoreContentAdaptWithSize(true)
AwardText_1:setTextAreaSize({width = 0, height = 0})
AwardText_1:setFontName("font/Font001.ttf")
AwardText_1:setFontSize(32)
AwardText_1:setString([[奖励]])
AwardText_1:setLayoutComponentEnabled(true)
AwardText_1:setName("AwardText_1")
AwardText_1:setTag(482)
AwardText_1:setCascadeColorEnabled(true)
AwardText_1:setCascadeOpacityEnabled(true)
AwardText_1:setPosition(295.0000, 761.0000)
AwardText_1:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardText_1)
layout:setSize({width = 66.0000, height = 42.0000})
layout:setLeftMargin(262.0000)
layout:setRightMargin(-328.0000)
layout:setTopMargin(-782.0000)
layout:setBottomMargin(740.0000)
LanguageNode_CN:addChild(AwardText_1)

--Create BingoGoldIcon_1
local BingoGoldIcon_1 = ccui.ImageView:create()
BingoGoldIcon_1:ignoreContentAdaptWithSize(false)
BingoGoldIcon_1:loadTexture("00_02_Default/2.png", 1)
BingoGoldIcon_1:setLayoutComponentEnabled(true)
BingoGoldIcon_1:setName("BingoGoldIcon_1")
BingoGoldIcon_1:setTag(483)
BingoGoldIcon_1:setCascadeColorEnabled(true)
BingoGoldIcon_1:setCascadeOpacityEnabled(true)
BingoGoldIcon_1:setPosition(350.0000, 758.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(BingoGoldIcon_1)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(330.0000)
layout:setRightMargin(-370.0000)
layout:setTopMargin(-778.0000)
layout:setBottomMargin(738.0000)
LanguageNode_CN:addChild(BingoGoldIcon_1)

--Create AwardGainNum_1
local AwardGainNum_1 = ccui.Text:create()
AwardGainNum_1:ignoreContentAdaptWithSize(true)
AwardGainNum_1:setTextAreaSize({width = 0, height = 0})
AwardGainNum_1:setFontName("font/Font003.ttf")
AwardGainNum_1:setFontSize(40)
AwardGainNum_1:setString([[523.5万]])
AwardGainNum_1:setTextHorizontalAlignment(1)
AwardGainNum_1:setTextVerticalAlignment(1)
AwardGainNum_1:setLayoutComponentEnabled(true)
AwardGainNum_1:setName("AwardGainNum_1")
AwardGainNum_1:setTag(484)
AwardGainNum_1:setCascadeColorEnabled(true)
AwardGainNum_1:setCascadeOpacityEnabled(true)
AwardGainNum_1:setPosition(433.0000, 758.0000)
AwardGainNum_1:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardGainNum_1)
layout:setSize({width = 128.0000, height = 47.0000})
layout:setLeftMargin(369.0000)
layout:setRightMargin(-497.0000)
layout:setTopMargin(-781.5000)
layout:setBottomMargin(734.5000)
LanguageNode_CN:addChild(AwardGainNum_1)

--Create LanguageNode_en
local LanguageNode_en=cc.Node:create()
LanguageNode_en:setName("LanguageNode_en")
LanguageNode_en:setTag(486)
LanguageNode_en:setCascadeColorEnabled(true)
LanguageNode_en:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageNode_en)
delete:addChild(LanguageNode_en)

--Create AwardText_2
local AwardText_2 = ccui.Text:create()
AwardText_2:ignoreContentAdaptWithSize(true)
AwardText_2:setTextAreaSize({width = 0, height = 0})
AwardText_2:setFontName("font/Font003.ttf")
AwardText_2:setFontSize(28)
AwardText_2:setString([[You Win]])
AwardText_2:setLayoutComponentEnabled(true)
AwardText_2:setName("AwardText_2")
AwardText_2:setTag(487)
AwardText_2:setCascadeColorEnabled(true)
AwardText_2:setCascadeOpacityEnabled(true)
AwardText_2:setPosition(306.9988, 758.0015)
AwardText_2:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardText_2)
layout:setSize({width = 95.0000, height = 33.0000})
layout:setLeftMargin(259.4988)
layout:setRightMargin(-354.4988)
layout:setTopMargin(-774.5015)
layout:setBottomMargin(741.5015)
LanguageNode_en:addChild(AwardText_2)

--Create BingoGoldIcon_2
local BingoGoldIcon_2 = ccui.ImageView:create()
BingoGoldIcon_2:ignoreContentAdaptWithSize(false)
BingoGoldIcon_2:loadTexture("00_02_Default/2.png", 1)
BingoGoldIcon_2:setLayoutComponentEnabled(true)
BingoGoldIcon_2:setName("BingoGoldIcon_2")
BingoGoldIcon_2:setTag(488)
BingoGoldIcon_2:setCascadeColorEnabled(true)
BingoGoldIcon_2:setCascadeOpacityEnabled(true)
BingoGoldIcon_2:setPosition(381.9991, 758.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(BingoGoldIcon_2)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(361.9991)
layout:setRightMargin(-401.9991)
layout:setTopMargin(-778.0000)
layout:setBottomMargin(738.0000)
LanguageNode_en:addChild(BingoGoldIcon_2)

--Create AwardGainNum_2
local AwardGainNum_2 = ccui.Text:create()
AwardGainNum_2:ignoreContentAdaptWithSize(true)
AwardGainNum_2:setTextAreaSize({width = 0, height = 0})
AwardGainNum_2:setFontName("font/Font003.ttf")
AwardGainNum_2:setFontSize(32)
AwardGainNum_2:setString([[999k]])
AwardGainNum_2:setTextHorizontalAlignment(1)
AwardGainNum_2:setTextVerticalAlignment(1)
AwardGainNum_2:setLayoutComponentEnabled(true)
AwardGainNum_2:setName("AwardGainNum_2")
AwardGainNum_2:setTag(489)
AwardGainNum_2:setCascadeColorEnabled(true)
AwardGainNum_2:setCascadeOpacityEnabled(true)
AwardGainNum_2:setPosition(441.4966, 759.0010)
AwardGainNum_2:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardGainNum_2)
layout:setSize({width = 65.0000, height = 37.0000})
layout:setLeftMargin(408.9966)
layout:setRightMargin(-473.9966)
layout:setTopMargin(-777.5010)
layout:setBottomMargin(740.5010)
LanguageNode_en:addChild(AwardGainNum_2)

--Create LanguageNode_TW
local LanguageNode_TW=cc.Node:create()
LanguageNode_TW:setName("LanguageNode_TW")
LanguageNode_TW:setTag(653)
LanguageNode_TW:setCascadeColorEnabled(true)
LanguageNode_TW:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(LanguageNode_TW)
delete:addChild(LanguageNode_TW)

--Create AwardText_3
local AwardText_3 = ccui.Text:create()
AwardText_3:ignoreContentAdaptWithSize(true)
AwardText_3:setTextAreaSize({width = 0, height = 0})
AwardText_3:setFontName("font/Font001.ttf")
AwardText_3:setFontSize(32)
AwardText_3:setString([[獎勵]])
AwardText_3:setLayoutComponentEnabled(true)
AwardText_3:setName("AwardText_3")
AwardText_3:setTag(654)
AwardText_3:setCascadeColorEnabled(true)
AwardText_3:setCascadeOpacityEnabled(true)
AwardText_3:setPosition(295.0000, 761.0000)
AwardText_3:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardText_3)
layout:setSize({width = 66.0000, height = 42.0000})
layout:setLeftMargin(262.0000)
layout:setRightMargin(-328.0000)
layout:setTopMargin(-782.0000)
layout:setBottomMargin(740.0000)
LanguageNode_TW:addChild(AwardText_3)

--Create BingoGoldIcon_3
local BingoGoldIcon_3 = ccui.ImageView:create()
BingoGoldIcon_3:ignoreContentAdaptWithSize(false)
BingoGoldIcon_3:loadTexture("00_02_Default/2.png", 1)
BingoGoldIcon_3:setLayoutComponentEnabled(true)
BingoGoldIcon_3:setName("BingoGoldIcon_3")
BingoGoldIcon_3:setTag(655)
BingoGoldIcon_3:setCascadeColorEnabled(true)
BingoGoldIcon_3:setCascadeOpacityEnabled(true)
BingoGoldIcon_3:setPosition(350.0000, 758.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(BingoGoldIcon_3)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(330.0000)
layout:setRightMargin(-370.0000)
layout:setTopMargin(-778.0000)
layout:setBottomMargin(738.0000)
LanguageNode_TW:addChild(BingoGoldIcon_3)

--Create AwardGainNum_3
local AwardGainNum_3 = ccui.Text:create()
AwardGainNum_3:ignoreContentAdaptWithSize(true)
AwardGainNum_3:setTextAreaSize({width = 0, height = 0})
AwardGainNum_3:setFontName("font/Font003.ttf")
AwardGainNum_3:setFontSize(40)
AwardGainNum_3:setString([[523.5萬]])
AwardGainNum_3:setTextHorizontalAlignment(1)
AwardGainNum_3:setTextVerticalAlignment(1)
AwardGainNum_3:setLayoutComponentEnabled(true)
AwardGainNum_3:setName("AwardGainNum_3")
AwardGainNum_3:setTag(656)
AwardGainNum_3:setCascadeColorEnabled(true)
AwardGainNum_3:setCascadeOpacityEnabled(true)
AwardGainNum_3:setPosition(433.0000, 758.0000)
AwardGainNum_3:setTextColor({r = 255, g = 238, b = 104})
layout = ccui.LayoutComponent:bindLayoutComponent(AwardGainNum_3)
layout:setSize({width = 128.0000, height = 47.0000})
layout:setLeftMargin(369.0000)
layout:setRightMargin(-497.0000)
layout:setTopMargin(-781.5000)
layout:setBottomMargin(734.5000)
LanguageNode_TW:addChild(AwardGainNum_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

