--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
"ui/00_02_Default/00_02_Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create BoastEntranceNode
local BoastEntranceNode=cc.Node:create()
BoastEntranceNode:setName("BoastEntranceNode")
BoastEntranceNode:setTag(83)
BoastEntranceNode:setCascadeColorEnabled(true)
BoastEntranceNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(BoastEntranceNode)
layout:setRightMargin(720.0000)
layout:setTopMargin(1280.0000)
Layer:addChild(BoastEntranceNode)

--Create GradeOneInletNode
local GradeOneInletNode=cc.Node:create()
GradeOneInletNode:setName("GradeOneInletNode")
GradeOneInletNode:setTag(85)
GradeOneInletNode:setCascadeColorEnabled(true)
GradeOneInletNode:setCascadeOpacityEnabled(true)
GradeOneInletNode:setPosition(368.0000, 1007.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneInletNode)
layout:setLeftMargin(368.0000)
layout:setRightMargin(-368.0000)
layout:setTopMargin(-1007.0000)
layout:setBottomMargin(1007.0000)
BoastEntranceNode:addChild(GradeOneInletNode)

--Create GradeOneBg_1
local GradeOneBg_1 = ccui.ImageView:create()
GradeOneBg_1:ignoreContentAdaptWithSize(false)
GradeOneBg_1:loadTexture("02_01_Boast/frame_224.png", 1)
GradeOneBg_1:setLayoutComponentEnabled(true)
GradeOneBg_1:setName("GradeOneBg_1")
GradeOneBg_1:setTag(86)
GradeOneBg_1:setCascadeColorEnabled(true)
GradeOneBg_1:setCascadeOpacityEnabled(true)
GradeOneBg_1:setPosition(800.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneBg_1)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(500.0000)
layout:setRightMargin(-1100.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeOneInletNode:addChild(GradeOneBg_1)

--Create GradeOneBg_2
local GradeOneBg_2 = ccui.ImageView:create()
GradeOneBg_2:ignoreContentAdaptWithSize(false)
GradeOneBg_2:loadTexture("02_01_Boast/picture_136.png", 1)
GradeOneBg_2:setLayoutComponentEnabled(true)
GradeOneBg_2:setName("GradeOneBg_2")
GradeOneBg_2:setTag(87)
GradeOneBg_2:setCascadeColorEnabled(true)
GradeOneBg_2:setCascadeOpacityEnabled(true)
GradeOneBg_2:setPosition(96.0000, -1.0000)
GradeOneBg_2:setScaleX(0.0100)
GradeOneBg_2:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneBg_2)
layout:setSize({width = 500.0000, height = 400.0000})
layout:setLeftMargin(-154.0000)
layout:setRightMargin(-346.0000)
layout:setTopMargin(-199.0000)
layout:setBottomMargin(-201.0000)
GradeOneInletNode:addChild(GradeOneBg_2)

--Create GradeOneName_IVT
local GradeOneName_IVT = ccui.ImageView:create()
GradeOneName_IVT:ignoreContentAdaptWithSize(false)
GradeOneName_IVT:loadTexture("02_01_Boast/picture_133_zh_CN.png", 1)
GradeOneName_IVT:setLayoutComponentEnabled(true)
GradeOneName_IVT:setName("GradeOneName_IVT")
GradeOneName_IVT:setTag(88)
GradeOneName_IVT:setCascadeColorEnabled(true)
GradeOneName_IVT:setCascadeOpacityEnabled(true)
GradeOneName_IVT:setPosition(-170.0000, 45.0000)
GradeOneName_IVT:setScaleX(0.0100)
GradeOneName_IVT:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneName_IVT)
layout:setSize({width = 300.0000, height = 100.0000})
layout:setLeftMargin(-320.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(-95.0000)
layout:setBottomMargin(-5.0000)
GradeOneInletNode:addChild(GradeOneName_IVT)

--Create GradeOneAnte_IVT
local GradeOneAnte_IVT = ccui.ImageView:create()
GradeOneAnte_IVT:ignoreContentAdaptWithSize(false)
GradeOneAnte_IVT:loadTexture("02_01_Boast/picture_130_zh_CN.png", 1)
GradeOneAnte_IVT:setLayoutComponentEnabled(true)
GradeOneAnte_IVT:setName("GradeOneAnte_IVT")
GradeOneAnte_IVT:setTag(89)
GradeOneAnte_IVT:setCascadeColorEnabled(true)
GradeOneAnte_IVT:setCascadeOpacityEnabled(true)
GradeOneAnte_IVT:setPosition(827.0000, -36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneAnte_IVT)
layout:setSize({width = 330.0000, height = 84.0000})
layout:setLeftMargin(662.0000)
layout:setRightMargin(-992.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(-78.0000)
GradeOneInletNode:addChild(GradeOneAnte_IVT)

--Create GradeOnePeopleNumIcon
local GradeOnePeopleNumIcon = ccui.ImageView:create()
GradeOnePeopleNumIcon:ignoreContentAdaptWithSize(false)
GradeOnePeopleNumIcon:loadTexture("02_01_Boast/icon_155.png", 1)
GradeOnePeopleNumIcon:setLayoutComponentEnabled(true)
GradeOnePeopleNumIcon:setName("GradeOnePeopleNumIcon")
GradeOnePeopleNumIcon:setTag(90)
GradeOnePeopleNumIcon:setCascadeColorEnabled(true)
GradeOnePeopleNumIcon:setCascadeOpacityEnabled(true)
GradeOnePeopleNumIcon:setPosition(-230.0000, 88.0000)
GradeOnePeopleNumIcon:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOnePeopleNumIcon)
layout:setSize({width = 30.0000, height = 34.0000})
layout:setLeftMargin(-245.0000)
layout:setRightMargin(215.0000)
layout:setTopMargin(-105.0000)
layout:setBottomMargin(71.0000)
GradeOneInletNode:addChild(GradeOnePeopleNumIcon)

--Create GradeOnePeopleNum
local GradeOnePeopleNum = ccui.Text:create()
GradeOnePeopleNum:ignoreContentAdaptWithSize(true)
GradeOnePeopleNum:setTextAreaSize({width = 0, height = 0})
GradeOnePeopleNum:setFontName("font/Default.ttf")
GradeOnePeopleNum:setFontSize(20)
GradeOnePeopleNum:setString([[2000]])
GradeOnePeopleNum:setLayoutComponentEnabled(true)
GradeOnePeopleNum:setName("GradeOnePeopleNum")
GradeOnePeopleNum:setTag(91)
GradeOnePeopleNum:setCascadeColorEnabled(true)
GradeOnePeopleNum:setCascadeOpacityEnabled(true)
GradeOnePeopleNum:setAnchorPoint(0.0000, 0.5000)
GradeOnePeopleNum:setPosition(23.0000, 19.0000)
GradeOnePeopleNum:setTextColor({r = 201, g = 200, b = 200})
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOnePeopleNum)
layout:setPositionPercentX(0.7667)
layout:setPositionPercentY(0.5588)
layout:setPercentWidth(1.6667)
layout:setPercentHeight(0.7647)
layout:setSize({width = 50.0000, height = 26.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(-43.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(6.0000)
GradeOnePeopleNumIcon:addChild(GradeOnePeopleNum)

--Create GradeOneSpineATNode
local GradeOneSpineATNode=cc.Node:create()
GradeOneSpineATNode:setName("GradeOneSpineATNode")
GradeOneSpineATNode:setTag(92)
GradeOneSpineATNode:setCascadeColorEnabled(true)
GradeOneSpineATNode:setCascadeOpacityEnabled(true)
GradeOneSpineATNode:setPosition(1004.0000, -77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOneSpineATNode)
layout:setLeftMargin(1004.0000)
layout:setRightMargin(-1004.0000)
layout:setTopMargin(77.0000)
layout:setBottomMargin(-77.0000)
GradeOneInletNode:addChild(GradeOneSpineATNode)

--Create GradeOnePanel
local GradeOnePanel = ccui.Layout:create()
GradeOnePanel:ignoreContentAdaptWithSize(false)
GradeOnePanel:setClippingEnabled(false)
GradeOnePanel:setBackGroundColorOpacity(102)
GradeOnePanel:setLayoutComponentEnabled(true)
GradeOnePanel:setName("GradeOnePanel")
GradeOnePanel:setTag(136)
GradeOnePanel:setCascadeColorEnabled(true)
GradeOnePanel:setCascadeOpacityEnabled(true)
GradeOnePanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeOnePanel)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(-300.0000)
layout:setRightMargin(-300.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeOneInletNode:addChild(GradeOnePanel)

--Create GradeTwoInletNode
local GradeTwoInletNode=cc.Node:create()
GradeTwoInletNode:setName("GradeTwoInletNode")
GradeTwoInletNode:setTag(160)
GradeTwoInletNode:setCascadeColorEnabled(true)
GradeTwoInletNode:setCascadeOpacityEnabled(true)
GradeTwoInletNode:setPosition(368.0000, 670.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoInletNode)
layout:setLeftMargin(368.0000)
layout:setRightMargin(-368.0000)
layout:setTopMargin(-670.0000)
layout:setBottomMargin(670.0000)
BoastEntranceNode:addChild(GradeTwoInletNode)

--Create GradeTwoBg_1
local GradeTwoBg_1 = ccui.ImageView:create()
GradeTwoBg_1:ignoreContentAdaptWithSize(false)
GradeTwoBg_1:loadTexture("02_01_Boast/frame_225.png", 1)
GradeTwoBg_1:setLayoutComponentEnabled(true)
GradeTwoBg_1:setName("GradeTwoBg_1")
GradeTwoBg_1:setTag(161)
GradeTwoBg_1:setCascadeColorEnabled(true)
GradeTwoBg_1:setCascadeOpacityEnabled(true)
GradeTwoBg_1:setPosition(800.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoBg_1)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(500.0000)
layout:setRightMargin(-1100.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeTwoInletNode:addChild(GradeTwoBg_1)

--Create GradeTwoBg_2
local GradeTwoBg_2 = ccui.ImageView:create()
GradeTwoBg_2:ignoreContentAdaptWithSize(false)
GradeTwoBg_2:loadTexture("02_01_Boast/picture_137.png", 1)
GradeTwoBg_2:setLayoutComponentEnabled(true)
GradeTwoBg_2:setName("GradeTwoBg_2")
GradeTwoBg_2:setTag(162)
GradeTwoBg_2:setCascadeColorEnabled(true)
GradeTwoBg_2:setCascadeOpacityEnabled(true)
GradeTwoBg_2:setPosition(96.0000, -1.0000)
GradeTwoBg_2:setScaleX(0.0100)
GradeTwoBg_2:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoBg_2)
layout:setSize({width = 500.0000, height = 400.0000})
layout:setLeftMargin(-154.0000)
layout:setRightMargin(-346.0000)
layout:setTopMargin(-199.0000)
layout:setBottomMargin(-201.0000)
GradeTwoInletNode:addChild(GradeTwoBg_2)

--Create GradeTwoName_IVT
local GradeTwoName_IVT = ccui.ImageView:create()
GradeTwoName_IVT:ignoreContentAdaptWithSize(false)
GradeTwoName_IVT:loadTexture("02_01_Boast/picture_134_zh_CN.png", 1)
GradeTwoName_IVT:setLayoutComponentEnabled(true)
GradeTwoName_IVT:setName("GradeTwoName_IVT")
GradeTwoName_IVT:setTag(163)
GradeTwoName_IVT:setCascadeColorEnabled(true)
GradeTwoName_IVT:setCascadeOpacityEnabled(true)
GradeTwoName_IVT:setPosition(-170.0000, 45.0000)
GradeTwoName_IVT:setScaleX(0.0100)
GradeTwoName_IVT:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoName_IVT)
layout:setSize({width = 300.0000, height = 100.0000})
layout:setLeftMargin(-320.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(-95.0000)
layout:setBottomMargin(-5.0000)
GradeTwoInletNode:addChild(GradeTwoName_IVT)

--Create GradeTwoAnte_IVT
local GradeTwoAnte_IVT = ccui.ImageView:create()
GradeTwoAnte_IVT:ignoreContentAdaptWithSize(false)
GradeTwoAnte_IVT:loadTexture("02_01_Boast/picture_131_zh_CN.png", 1)
GradeTwoAnte_IVT:setLayoutComponentEnabled(true)
GradeTwoAnte_IVT:setName("GradeTwoAnte_IVT")
GradeTwoAnte_IVT:setTag(164)
GradeTwoAnte_IVT:setCascadeColorEnabled(true)
GradeTwoAnte_IVT:setCascadeOpacityEnabled(true)
GradeTwoAnte_IVT:setPosition(827.0000, -36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoAnte_IVT)
layout:setSize({width = 330.0000, height = 84.0000})
layout:setLeftMargin(662.0000)
layout:setRightMargin(-992.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(-78.0000)
GradeTwoInletNode:addChild(GradeTwoAnte_IVT)

--Create GradeTwoPeopleNumIcon
local GradeTwoPeopleNumIcon = ccui.ImageView:create()
GradeTwoPeopleNumIcon:ignoreContentAdaptWithSize(false)
GradeTwoPeopleNumIcon:loadTexture("02_01_Boast/icon_155.png", 1)
GradeTwoPeopleNumIcon:setLayoutComponentEnabled(true)
GradeTwoPeopleNumIcon:setName("GradeTwoPeopleNumIcon")
GradeTwoPeopleNumIcon:setTag(165)
GradeTwoPeopleNumIcon:setCascadeColorEnabled(true)
GradeTwoPeopleNumIcon:setCascadeOpacityEnabled(true)
GradeTwoPeopleNumIcon:setPosition(-230.0000, 88.0000)
GradeTwoPeopleNumIcon:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoPeopleNumIcon)
layout:setSize({width = 30.0000, height = 34.0000})
layout:setLeftMargin(-245.0000)
layout:setRightMargin(215.0000)
layout:setTopMargin(-105.0000)
layout:setBottomMargin(71.0000)
GradeTwoInletNode:addChild(GradeTwoPeopleNumIcon)

--Create GradeTwoPeopleNum
local GradeTwoPeopleNum = ccui.Text:create()
GradeTwoPeopleNum:ignoreContentAdaptWithSize(true)
GradeTwoPeopleNum:setTextAreaSize({width = 0, height = 0})
GradeTwoPeopleNum:setFontName("font/Default.ttf")
GradeTwoPeopleNum:setFontSize(20)
GradeTwoPeopleNum:setString([[2000]])
GradeTwoPeopleNum:setLayoutComponentEnabled(true)
GradeTwoPeopleNum:setName("GradeTwoPeopleNum")
GradeTwoPeopleNum:setTag(166)
GradeTwoPeopleNum:setCascadeColorEnabled(true)
GradeTwoPeopleNum:setCascadeOpacityEnabled(true)
GradeTwoPeopleNum:setAnchorPoint(0.0000, 0.5000)
GradeTwoPeopleNum:setPosition(23.0000, 19.0000)
GradeTwoPeopleNum:setTextColor({r = 201, g = 200, b = 200})
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoPeopleNum)
layout:setPositionPercentX(0.7667)
layout:setPositionPercentY(0.5588)
layout:setPercentWidth(1.6667)
layout:setPercentHeight(0.7647)
layout:setSize({width = 50.0000, height = 26.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(-43.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(6.0000)
GradeTwoPeopleNumIcon:addChild(GradeTwoPeopleNum)

--Create GradeTwoSpineATNode
local GradeTwoSpineATNode=cc.Node:create()
GradeTwoSpineATNode:setName("GradeTwoSpineATNode")
GradeTwoSpineATNode:setTag(167)
GradeTwoSpineATNode:setCascadeColorEnabled(true)
GradeTwoSpineATNode:setCascadeOpacityEnabled(true)
GradeTwoSpineATNode:setPosition(1004.0000, -77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoSpineATNode)
layout:setLeftMargin(1004.0000)
layout:setRightMargin(-1004.0000)
layout:setTopMargin(77.0000)
layout:setBottomMargin(-77.0000)
GradeTwoInletNode:addChild(GradeTwoSpineATNode)

--Create GradeTwoImage
local GradeTwoImage = ccui.ImageView:create()
GradeTwoImage:ignoreContentAdaptWithSize(false)
GradeTwoImage:loadTexture("00_02_Default/Temporary101.png", 1)
GradeTwoImage:setLayoutComponentEnabled(true)
GradeTwoImage:setName("GradeTwoImage")
GradeTwoImage:setTag(85)
GradeTwoImage:setCascadeColorEnabled(true)
GradeTwoImage:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoImage)
layout:setSize({width = 162.0000, height = 126.0000})
layout:setLeftMargin(-81.0000)
layout:setRightMargin(-81.0000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(-63.0000)
GradeTwoSpineATNode:addChild(GradeTwoImage)

--Create GradeTwoPanel
local GradeTwoPanel = ccui.Layout:create()
GradeTwoPanel:ignoreContentAdaptWithSize(false)
GradeTwoPanel:setClippingEnabled(false)
GradeTwoPanel:setBackGroundColorOpacity(102)
GradeTwoPanel:setTouchEnabled(true);
GradeTwoPanel:setLayoutComponentEnabled(true)
GradeTwoPanel:setName("GradeTwoPanel")
GradeTwoPanel:setTag(138)
GradeTwoPanel:setCascadeColorEnabled(true)
GradeTwoPanel:setCascadeOpacityEnabled(true)
GradeTwoPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeTwoPanel)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(-300.0000)
layout:setRightMargin(-300.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeTwoInletNode:addChild(GradeTwoPanel)

--Create GradeThreeInletNode
local GradeThreeInletNode=cc.Node:create()
GradeThreeInletNode:setName("GradeThreeInletNode")
GradeThreeInletNode:setTag(169)
GradeThreeInletNode:setCascadeColorEnabled(true)
GradeThreeInletNode:setCascadeOpacityEnabled(true)
GradeThreeInletNode:setPosition(368.0000, 332.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeInletNode)
layout:setLeftMargin(368.0000)
layout:setRightMargin(-368.0000)
layout:setTopMargin(-332.0000)
layout:setBottomMargin(332.0000)
BoastEntranceNode:addChild(GradeThreeInletNode)

--Create GradeThreeBg_1
local GradeThreeBg_1 = ccui.ImageView:create()
GradeThreeBg_1:ignoreContentAdaptWithSize(false)
GradeThreeBg_1:loadTexture("02_01_Boast/frame_226.png", 1)
GradeThreeBg_1:setLayoutComponentEnabled(true)
GradeThreeBg_1:setName("GradeThreeBg_1")
GradeThreeBg_1:setTag(170)
GradeThreeBg_1:setCascadeColorEnabled(true)
GradeThreeBg_1:setCascadeOpacityEnabled(true)
GradeThreeBg_1:setPosition(800.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeBg_1)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(500.0000)
layout:setRightMargin(-1100.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeThreeInletNode:addChild(GradeThreeBg_1)

--Create GradeThreeBg_2
local GradeThreeBg_2 = ccui.ImageView:create()
GradeThreeBg_2:ignoreContentAdaptWithSize(false)
GradeThreeBg_2:loadTexture("02_01_Boast/picture_138.png", 1)
GradeThreeBg_2:setLayoutComponentEnabled(true)
GradeThreeBg_2:setName("GradeThreeBg_2")
GradeThreeBg_2:setTag(171)
GradeThreeBg_2:setCascadeColorEnabled(true)
GradeThreeBg_2:setCascadeOpacityEnabled(true)
GradeThreeBg_2:setPosition(96.0000, -1.0000)
GradeThreeBg_2:setScaleX(0.0100)
GradeThreeBg_2:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeBg_2)
layout:setSize({width = 500.0000, height = 400.0000})
layout:setLeftMargin(-154.0000)
layout:setRightMargin(-346.0000)
layout:setTopMargin(-199.0000)
layout:setBottomMargin(-201.0000)
GradeThreeInletNode:addChild(GradeThreeBg_2)

--Create GradeThreeName_IVT
local GradeThreeName_IVT = ccui.ImageView:create()
GradeThreeName_IVT:ignoreContentAdaptWithSize(false)
GradeThreeName_IVT:loadTexture("02_01_Boast/picture_135_zh_CN.png", 1)
GradeThreeName_IVT:setLayoutComponentEnabled(true)
GradeThreeName_IVT:setName("GradeThreeName_IVT")
GradeThreeName_IVT:setTag(172)
GradeThreeName_IVT:setCascadeColorEnabled(true)
GradeThreeName_IVT:setCascadeOpacityEnabled(true)
GradeThreeName_IVT:setPosition(-170.0000, 45.0000)
GradeThreeName_IVT:setScaleX(0.0100)
GradeThreeName_IVT:setScaleY(0.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeName_IVT)
layout:setSize({width = 300.0000, height = 100.0000})
layout:setLeftMargin(-320.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(-95.0000)
layout:setBottomMargin(-5.0000)
GradeThreeInletNode:addChild(GradeThreeName_IVT)

--Create GradeThreeAnte_IVT
local GradeThreeAnte_IVT = ccui.ImageView:create()
GradeThreeAnte_IVT:ignoreContentAdaptWithSize(false)
GradeThreeAnte_IVT:loadTexture("02_01_Boast/picture_132_zh_CN.png", 1)
GradeThreeAnte_IVT:setLayoutComponentEnabled(true)
GradeThreeAnte_IVT:setName("GradeThreeAnte_IVT")
GradeThreeAnte_IVT:setTag(173)
GradeThreeAnte_IVT:setCascadeColorEnabled(true)
GradeThreeAnte_IVT:setCascadeOpacityEnabled(true)
GradeThreeAnte_IVT:setPosition(827.0000, -36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeAnte_IVT)
layout:setSize({width = 330.0000, height = 84.0000})
layout:setLeftMargin(662.0000)
layout:setRightMargin(-992.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(-78.0000)
GradeThreeInletNode:addChild(GradeThreeAnte_IVT)

--Create GradeThreePeopleNumIcon
local GradeThreePeopleNumIcon = ccui.ImageView:create()
GradeThreePeopleNumIcon:ignoreContentAdaptWithSize(false)
GradeThreePeopleNumIcon:loadTexture("02_01_Boast/icon_155.png", 1)
GradeThreePeopleNumIcon:setLayoutComponentEnabled(true)
GradeThreePeopleNumIcon:setName("GradeThreePeopleNumIcon")
GradeThreePeopleNumIcon:setTag(174)
GradeThreePeopleNumIcon:setCascadeColorEnabled(true)
GradeThreePeopleNumIcon:setCascadeOpacityEnabled(true)
GradeThreePeopleNumIcon:setPosition(-230.0000, 88.0000)
GradeThreePeopleNumIcon:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreePeopleNumIcon)
layout:setSize({width = 30.0000, height = 34.0000})
layout:setLeftMargin(-245.0000)
layout:setRightMargin(215.0000)
layout:setTopMargin(-105.0000)
layout:setBottomMargin(71.0000)
GradeThreeInletNode:addChild(GradeThreePeopleNumIcon)

--Create GradeThreePeopleNum
local GradeThreePeopleNum = ccui.Text:create()
GradeThreePeopleNum:ignoreContentAdaptWithSize(true)
GradeThreePeopleNum:setTextAreaSize({width = 0, height = 0})
GradeThreePeopleNum:setFontName("font/Default.ttf")
GradeThreePeopleNum:setFontSize(20)
GradeThreePeopleNum:setString([[2000]])
GradeThreePeopleNum:setLayoutComponentEnabled(true)
GradeThreePeopleNum:setName("GradeThreePeopleNum")
GradeThreePeopleNum:setTag(175)
GradeThreePeopleNum:setCascadeColorEnabled(true)
GradeThreePeopleNum:setCascadeOpacityEnabled(true)
GradeThreePeopleNum:setAnchorPoint(0.0000, 0.5000)
GradeThreePeopleNum:setPosition(23.0000, 19.0000)
GradeThreePeopleNum:setTextColor({r = 201, g = 200, b = 200})
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreePeopleNum)
layout:setPositionPercentX(0.7667)
layout:setPositionPercentY(0.5588)
layout:setPercentWidth(1.6667)
layout:setPercentHeight(0.7647)
layout:setSize({width = 50.0000, height = 26.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(-43.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(6.0000)
GradeThreePeopleNumIcon:addChild(GradeThreePeopleNum)

--Create GradeThreeSpineATNode
local GradeThreeSpineATNode=cc.Node:create()
GradeThreeSpineATNode:setName("GradeThreeSpineATNode")
GradeThreeSpineATNode:setTag(176)
GradeThreeSpineATNode:setCascadeColorEnabled(true)
GradeThreeSpineATNode:setCascadeOpacityEnabled(true)
GradeThreeSpineATNode:setPosition(800.0000, -43.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeSpineATNode)
layout:setLeftMargin(800.0000)
layout:setRightMargin(-800.0000)
layout:setTopMargin(43.0000)
layout:setBottomMargin(-43.0000)
GradeThreeInletNode:addChild(GradeThreeSpineATNode)

--Create GradeThreeSpineATNode_2
local GradeThreeSpineATNode_2=cc.Node:create()
GradeThreeSpineATNode_2:setName("GradeThreeSpineATNode_2")
GradeThreeSpineATNode_2:setTag(134)
GradeThreeSpineATNode_2:setCascadeColorEnabled(true)
GradeThreeSpineATNode_2:setCascadeOpacityEnabled(true)
GradeThreeSpineATNode_2:setVisible(false)
GradeThreeSpineATNode_2:setPosition(116.0000, 43.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreeSpineATNode_2)
layout:setLeftMargin(116.0000)
layout:setRightMargin(-116.0000)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(43.0000)
GradeThreeInletNode:addChild(GradeThreeSpineATNode_2)

--Create GradeThreePanel
local GradeThreePanel = ccui.Layout:create()
GradeThreePanel:ignoreContentAdaptWithSize(false)
GradeThreePanel:setClippingEnabled(false)
GradeThreePanel:setBackGroundColorOpacity(102)
GradeThreePanel:setTouchEnabled(true);
GradeThreePanel:setLayoutComponentEnabled(true)
GradeThreePanel:setName("GradeThreePanel")
GradeThreePanel:setTag(137)
GradeThreePanel:setCascadeColorEnabled(true)
GradeThreePanel:setCascadeOpacityEnabled(true)
GradeThreePanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(GradeThreePanel)
layout:setSize({width = 600.0000, height = 300.0000})
layout:setLeftMargin(-300.0000)
layout:setRightMargin(-300.0000)
layout:setTopMargin(-150.0000)
layout:setBottomMargin(-150.0000)
GradeThreeInletNode:addChild(GradeThreePanel)

--Create PrivateRoomNode
local PrivateRoomNode=cc.Node:create()
PrivateRoomNode:setName("PrivateRoomNode")
PrivateRoomNode:setTag(178)
PrivateRoomNode:setCascadeColorEnabled(true)
PrivateRoomNode:setCascadeOpacityEnabled(true)
PrivateRoomNode:setPosition(1008.0000, 104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PrivateRoomNode)
layout:setLeftMargin(1008.0000)
layout:setRightMargin(-1008.0000)
layout:setTopMargin(-104.0000)
layout:setBottomMargin(104.0000)
BoastEntranceNode:addChild(PrivateRoomNode)

--Create PrivateRoom_IVT
local PrivateRoom_IVT = ccui.ImageView:create()
PrivateRoom_IVT:ignoreContentAdaptWithSize(false)
PrivateRoom_IVT:loadTexture("02_01_Boast/button_111_zh_CN.png", 1)
PrivateRoom_IVT:setLayoutComponentEnabled(true)
PrivateRoom_IVT:setName("PrivateRoom_IVT")
PrivateRoom_IVT:setTag(179)
PrivateRoom_IVT:setCascadeColorEnabled(true)
PrivateRoom_IVT:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PrivateRoom_IVT)
layout:setSize({width = 280.0000, height = 96.0000})
layout:setLeftMargin(-140.0000)
layout:setRightMargin(-140.0000)
layout:setTopMargin(-48.0000)
layout:setBottomMargin(-48.0000)
PrivateRoomNode:addChild(PrivateRoom_IVT)

--Create PrivateRoomPanel
local PrivateRoomPanel = ccui.Layout:create()
PrivateRoomPanel:ignoreContentAdaptWithSize(false)
PrivateRoomPanel:setClippingEnabled(false)
PrivateRoomPanel:setBackGroundColorOpacity(102)
PrivateRoomPanel:setTouchEnabled(true);
PrivateRoomPanel:setLayoutComponentEnabled(true)
PrivateRoomPanel:setName("PrivateRoomPanel")
PrivateRoomPanel:setTag(180)
PrivateRoomPanel:setCascadeColorEnabled(true)
PrivateRoomPanel:setCascadeOpacityEnabled(true)
PrivateRoomPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(PrivateRoomPanel)
layout:setSize({width = 280.0000, height = 100.0000})
layout:setLeftMargin(-140.0000)
layout:setRightMargin(-140.0000)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
PrivateRoomNode:addChild(PrivateRoomPanel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(170)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(800.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(-43.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneBg_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(96.0000)
localFrame:setY(-1.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneBg_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(34)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.1200)
localFrame:setScaleY(1.1200)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(46)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeOneBg_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(20)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeOneBg_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-170.0000)
localFrame:setY(45.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneName_IVT)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(44)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeOneName_IVT)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeOneName_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(31)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(36)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-127.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneAnte_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(33)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-230.0000)
localFrame:setY(88.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOnePeopleNumIcon)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(33)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeOnePeopleNumIcon)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(33)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeOnePeopleNumIcon)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(33)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(GradeOnePeopleNumIcon)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(1004.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(161.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(204.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneSpineATNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeOneSpineATNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeOneSpineATNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(368.0000)
localFrame:setY(1007.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(1007.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(977.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(7)
localFrame:setX(368.0000)
localFrame:setY(2957.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeOneInletNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeOneInletNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeOneInletNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(800.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(-43.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(66)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoBg_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(34)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(96.0000)
localFrame:setY(-1.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoBg_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(34)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.1200)
localFrame:setScaleY(1.1200)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoBg_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(34)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoBg_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-170.0000)
localFrame:setY(45.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoName_IVT)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoName_IVT)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoName_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(42)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-127.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoAnte_IVT)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoAnte_IVT)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoAnte_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(39)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-230.0000)
localFrame:setY(88.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoPeopleNumIcon)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(39)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoPeopleNumIcon)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(39)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoPeopleNumIcon)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(39)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(GradeTwoPeopleNumIcon)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(16)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(1004.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(161.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(66)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(204.0000)
localFrame:setY(-77.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoSpineATNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoSpineATNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(41)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoSpineATNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(368.0000)
localFrame:setY(670.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(670.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(640.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(7)
localFrame:setX(368.0000)
localFrame:setY(2620.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeTwoInletNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeTwoInletNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeTwoInletNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(800.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(-43.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(72)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeBg_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(96.0000)
localFrame:setY(-1.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeBg_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(54)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.1200)
localFrame:setScaleY(1.1200)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(66)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeBg_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeBg_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-170.0000)
localFrame:setY(45.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeName_IVT)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0100)
localFrame:setScaleY(0.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(56)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeName_IVT)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeName_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(43)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(827.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-127.0000)
localFrame:setY(-36.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeAnte_IVT)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(43)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeAnte_IVT)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(43)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeAnte_IVT)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-230.0000)
localFrame:setY(88.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreePeopleNumIcon)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreePeopleNumIcon)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreePeopleNumIcon)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(45)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(GradeThreePeopleNumIcon)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(800.0000)
localFrame:setY(-43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(-43.0000)
localFrame:setY(-43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(72)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(-43.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeSpineATNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeSpineATNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(47)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeSpineATNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(116.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(116.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(100)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(116.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(116.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(116.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeSpineATNode_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(100)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeSpineATNode_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(100)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeSpineATNode_2)

--Create VisibleForFrameTimeline
local VisibleForFrameTimeline = ccs.Timeline:create()

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(100)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

result['animation']:addTimeline(VisibleForFrameTimeline)
VisibleForFrameTimeline:setNode(GradeThreeSpineATNode_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(368.0000)
localFrame:setY(332.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(332.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(368.0000)
localFrame:setY(302.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(7)
localFrame:setX(368.0000)
localFrame:setY(2282.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(GradeThreeInletNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(GradeThreeInletNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(GradeThreeInletNode)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(1008.0000)
localFrame:setY(104.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(53)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setX(165.0000)
localFrame:setY(104.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(78)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(208.0000)
localFrame:setY(104.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(208.0000)
localFrame:setY(104.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(130)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setX(208.0000)
localFrame:setY(74.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(170)
localFrame:setTween(true)
localFrame:setTweenType(7)
localFrame:setX(208.0000)
localFrame:setY(2054.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(PrivateRoomNode)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(53)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(78)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(PrivateRoomNode)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(28)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(53)
localFrame:setTween(true)
localFrame:setTweenType(8)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(78)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(11)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(PrivateRoomNode)
--Create Animation List
local EnterIntoAnimation = {name="EnterIntoAnimation", startIndex=10, endIndex=90}
result['animation']:addAnimationInfo(EnterIntoAnimation)
local StandbyAnimation = {name="StandbyAnimation", startIndex=100, endIndex=100}
result['animation']:addAnimationInfo(StandbyAnimation)
local ExitAnimation = {name="ExitAnimation", startIndex=120, endIndex=150}
result['animation']:addAnimationInfo(ExitAnimation)

result['root'] = Layer
return result;
end

return Result

