--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 668.0000, height = 326.0000})

--Create HangUp
local HangUp=cc.Node:create()
HangUp:setName("HangUp")
HangUp:setTag(200)
HangUp:setCascadeColorEnabled(true)
HangUp:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(HangUp)
layout:setRightMargin(668.0000)
layout:setTopMargin(326.0000)
Layer:addChild(HangUp)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(234)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 668.0000, height = 326.0000})
layout:setRightMargin(-668.0000)
layout:setTopMargin(-326.0000)
HangUp:addChild(InteractionPopups)

--Create Bg
local Bg = ccui.ImageView:create()
Bg:ignoreContentAdaptWithSize(false)
Bg:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg:setScale9Enabled(true)
Bg:setCapInsets({x = 17, y = 138, width = 20, height = 144})
Bg:setLayoutComponentEnabled(true)
Bg:setName("Bg")
Bg:setTag(233)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
Bg:setAnchorPoint(0.0000, 0.0000)
Bg:setPosition(-0.0001, -0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setSize({width = 668.0000, height = 326.0000})
layout:setLeftMargin(-0.0001)
layout:setRightMargin(-667.9999)
layout:setTopMargin(-325.9999)
layout:setBottomMargin(-0.0001)
HangUp:addChild(Bg)

--Create TitleText_TT
local TitleText_TT = ccui.Text:create()
TitleText_TT:ignoreContentAdaptWithSize(true)
TitleText_TT:setTextAreaSize({width = 0, height = 0})
TitleText_TT:setFontName("font/Font001.ttf")
TitleText_TT:setFontSize(32)
TitleText_TT:setString([[提示]])
TitleText_TT:setTextHorizontalAlignment(1)
TitleText_TT:setTextVerticalAlignment(1)
TitleText_TT:setLayoutComponentEnabled(true)
TitleText_TT:setName("TitleText_TT")
TitleText_TT:setTag(232)
TitleText_TT:setCascadeColorEnabled(true)
TitleText_TT:setCascadeOpacityEnabled(true)
TitleText_TT:setPosition(334.0002, 288.4662)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText_TT)
layout:setSize({width = 67.0000, height = 42.0000})
layout:setLeftMargin(300.5002)
layout:setRightMargin(-367.5002)
layout:setTopMargin(-309.4662)
layout:setBottomMargin(267.4662)
HangUp:addChild(TitleText_TT)

--Create ContentText_1_TT
local ContentText_1_TT = ccui.Text:create()
ContentText_1_TT:ignoreContentAdaptWithSize(false)
ContentText_1_TT:setFontName("font/Default.ttf")
ContentText_1_TT:setFontSize(32)
ContentText_1_TT:setString([[睡着了么？你在床上也这样么?]])
ContentText_1_TT:setTextHorizontalAlignment(1)
ContentText_1_TT:setTextVerticalAlignment(1)
ContentText_1_TT:setLayoutComponentEnabled(true)
ContentText_1_TT:setName("ContentText_1_TT")
ContentText_1_TT:setTag(231)
ContentText_1_TT:setCascadeColorEnabled(true)
ContentText_1_TT:setCascadeOpacityEnabled(true)
ContentText_1_TT:setPosition(334.0000, 138.9984)
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText_1_TT)
layout:setSize({width = 600.0000, height = 126.0000})
layout:setLeftMargin(34.0000)
layout:setRightMargin(-634.0000)
layout:setTopMargin(-201.9984)
layout:setBottomMargin(75.9984)
HangUp:addChild(ContentText_1_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

