--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
"ui/01_10_Mail/01_10_Mail_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(1002)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
Middle:setPosition(26.0000, 306.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setPositionPercentX(0.0361)
layout:setPositionPercentY(0.2391)
layout:setLeftMargin(26.0000)
layout:setRightMargin(694.0000)
layout:setTopMargin(974.0000)
layout:setBottomMargin(306.0000)
Layer:addChild(Middle)

--Create Bg
local Bg = ccui.ImageView:create()
Bg:ignoreContentAdaptWithSize(false)
Bg:loadTexture("01_06_PersonalCenter/frame_034.png", 1)
Bg:setScale9Enabled(true)
Bg:setCapInsets({x = 17, y = 138, width = 20, height = 144})
Bg:setLayoutComponentEnabled(true)
Bg:setName("Bg")
Bg:setTag(1003)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
Bg:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setSize({width = 668.0000, height = 668.0000})
layout:setRightMargin(-668.0000)
layout:setTopMargin(-668.0000)
Middle:addChild(Bg)

--Create TitleText_TT
local TitleText_TT = ccui.Text:create()
TitleText_TT:ignoreContentAdaptWithSize(true)
TitleText_TT:setTextAreaSize({width = 0, height = 0})
TitleText_TT:setFontName("font/Font001.ttf")
TitleText_TT:setFontSize(32)
TitleText_TT:setString([[提示]])
TitleText_TT:setTextHorizontalAlignment(1)
TitleText_TT:setTextVerticalAlignment(1)
TitleText_TT:enableShadow({r = 34, g = 31, b = 86, a = 255}, {width = 0, height = -2}, 0)
TitleText_TT:setLayoutComponentEnabled(true)
TitleText_TT:setName("TitleText_TT")
TitleText_TT:setTag(1004)
TitleText_TT:setCascadeColorEnabled(true)
TitleText_TT:setCascadeOpacityEnabled(true)
TitleText_TT:setPosition(334.0003, 631.0012)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText_TT)
layout:setSize({width = 67.0000, height = 42.0000})
layout:setLeftMargin(300.5003)
layout:setRightMargin(-367.5003)
layout:setTopMargin(-652.0012)
layout:setBottomMargin(610.0012)
Middle:addChild(TitleText_TT)

--Create ContenText_TT
local ContenText_TT = ccui.Text:create()
ContenText_TT:ignoreContentAdaptWithSize(false)
ContenText_TT:setFontName("font/Default.ttf")
ContenText_TT:setFontSize(32)
ContenText_TT:setString([[此应用为旧版本，因此可能无法正常运行。请点击下方跳转安装新应用，如有问题请与开发者联系]])
ContenText_TT:setTextHorizontalAlignment(1)
ContenText_TT:setTextVerticalAlignment(1)
ContenText_TT:setLayoutComponentEnabled(true)
ContenText_TT:setName("ContenText_TT")
ContenText_TT:setTag(1005)
ContenText_TT:setCascadeColorEnabled(true)
ContenText_TT:setCascadeOpacityEnabled(true)
ContenText_TT:setPosition(334.0000, 375.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(ContenText_TT)
layout:setSize({width = 600.0000, height = 378.0000})
layout:setLeftMargin(34.0000)
layout:setRightMargin(-634.0000)
layout:setTopMargin(-564.0002)
layout:setBottomMargin(186.0002)
Middle:addChild(ContenText_TT)

--Create Jump
local Jump=cc.Node:create()
Jump:setName("Jump")
Jump:setTag(1013)
Jump:setCascadeColorEnabled(true)
Jump:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Jump)
Middle:addChild(Jump)

--Create JumpButton

local luaScript = require("csd.LuaScript.newButton")
local JumpButton = luaScript.CreateCustomNode()
JumpButton:ignoreContentAdaptWithSize(false)
JumpButton:loadTextureNormal("01_10_Mail/button_034.png", 1)
JumpButton:loadTexturePressed("01_10_Mail/button_034.png", 1)
JumpButton:loadTextureDisabled("01_10_Mail/button_034.png", 1)
JumpButton:setTitleFontSize(14)
JumpButton:setScale9Enabled(true)
JumpButton:setCapInsets({x = 15, y = 11, width = 178, height = 76})
JumpButton:setLayoutComponentEnabled(true)
JumpButton:setName("JumpButton")
JumpButton:setTag(1014)
JumpButton:setCascadeColorEnabled(true)
JumpButton:setCascadeOpacityEnabled(true)
JumpButton:setPosition(334.0000, 111.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(JumpButton)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(230.0000)
layout:setRightMargin(-438.0000)
layout:setTopMargin(-160.0000)
layout:setBottomMargin(62.0000)

luaScript.SetDownScele(JumpButton, "0.9800")
luaScript.SetClickEffect(JumpButton, "Sound004")
luaScript.SetDownColor(JumpButton, {r = 65, g = 65, b = 70})
Jump:addChild(JumpButton)

--Create JumpText_TT
local JumpText_TT = ccui.Text:create()
JumpText_TT:ignoreContentAdaptWithSize(true)
JumpText_TT:setTextAreaSize({width = 0, height = 0})
JumpText_TT:setFontName("font/Font001.ttf")
JumpText_TT:setFontSize(28)
JumpText_TT:setString([[跳转]])
JumpText_TT:setTextHorizontalAlignment(1)
JumpText_TT:setTextVerticalAlignment(1)
JumpText_TT:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 0, height = -1}, 0)
JumpText_TT:setLayoutComponentEnabled(true)
JumpText_TT:setName("JumpText_TT")
JumpText_TT:setTag(1015)
JumpText_TT:setCascadeColorEnabled(true)
JumpText_TT:setCascadeOpacityEnabled(true)
JumpText_TT:setPosition(104.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(JumpText_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2837)
layout:setPercentHeight(0.3776)
layout:setSize({width = 59.0000, height = 37.0000})
layout:setLeftMargin(74.5000)
layout:setRightMargin(74.5000)
layout:setTopMargin(30.5000)
layout:setBottomMargin(30.5000)
JumpButton:addChild(JumpText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

