--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 556.0000, height = 145.0000})

--Create PropKnapsackNode_1
local PropKnapsackNode_1=cc.Node:create()
PropKnapsackNode_1:setName("PropKnapsackNode_1")
PropKnapsackNode_1:setTag(843)
PropKnapsackNode_1:setCascadeColorEnabled(true)
PropKnapsackNode_1:setCascadeOpacityEnabled(true)
PropKnapsackNode_1:setPosition(63.0003, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropKnapsackNode_1)
layout:setPositionPercentX(0.1133)
layout:setPositionPercentY(0.4966)
layout:setLeftMargin(63.0003)
layout:setRightMargin(492.9997)
layout:setTopMargin(73.0000)
layout:setBottomMargin(72.0000)
Layer:addChild(PropKnapsackNode_1)

--Create PropKnapsackNode_2
local PropKnapsackNode_2=cc.Node:create()
PropKnapsackNode_2:setName("PropKnapsackNode_2")
PropKnapsackNode_2:setTag(901)
PropKnapsackNode_2:setCascadeColorEnabled(true)
PropKnapsackNode_2:setCascadeOpacityEnabled(true)
PropKnapsackNode_2:setPosition(201.0000, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropKnapsackNode_2)
layout:setPositionPercentX(0.3615)
layout:setPositionPercentY(0.4966)
layout:setLeftMargin(201.0000)
layout:setRightMargin(355.0000)
layout:setTopMargin(73.0000)
layout:setBottomMargin(72.0000)
Layer:addChild(PropKnapsackNode_2)

--Create PropKnapsackNode_3
local PropKnapsackNode_3=cc.Node:create()
PropKnapsackNode_3:setName("PropKnapsackNode_3")
PropKnapsackNode_3:setTag(902)
PropKnapsackNode_3:setCascadeColorEnabled(true)
PropKnapsackNode_3:setCascadeOpacityEnabled(true)
PropKnapsackNode_3:setPosition(339.0001, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropKnapsackNode_3)
layout:setPositionPercentX(0.6097)
layout:setPositionPercentY(0.4966)
layout:setLeftMargin(339.0001)
layout:setRightMargin(216.9999)
layout:setTopMargin(73.0000)
layout:setBottomMargin(72.0000)
Layer:addChild(PropKnapsackNode_3)

--Create PropKnapsackNode_4
local PropKnapsackNode_4=cc.Node:create()
PropKnapsackNode_4:setName("PropKnapsackNode_4")
PropKnapsackNode_4:setTag(903)
PropKnapsackNode_4:setCascadeColorEnabled(true)
PropKnapsackNode_4:setCascadeOpacityEnabled(true)
PropKnapsackNode_4:setPosition(477.0002, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropKnapsackNode_4)
layout:setPositionPercentX(0.8579)
layout:setPositionPercentY(0.4966)
layout:setLeftMargin(477.0002)
layout:setRightMargin(78.9998)
layout:setTopMargin(73.0000)
layout:setBottomMargin(72.0000)
Layer:addChild(PropKnapsackNode_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

