--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_01_Shop/03_01_Shop_1.plist",	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
"ui/01_03_PropKnapsack/01_03_PropKnapsack_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 580.0000, height = 646.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(64)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(580.0000)
layout:setTopMargin(646.0000)
Layer:addChild(Bg)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(65)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 580.0000, height = 646.0000})
layout:setRightMargin(-580.0000)
layout:setTopMargin(-646.0000)
Bg:addChild(InteractionPopups)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("03_01_Shop/frame_122.png", 1)
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(66)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setPosition(290.0000, 324.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 580.0000, height = 646.0000})
layout:setRightMargin(-580.0000)
layout:setTopMargin(-647.9998)
layout:setBottomMargin(1.9998)
Bg:addChild(Bg_1)

--Create boxnode
local boxnode=cc.Node:create()
boxnode:setName("boxnode")
boxnode:setTag(67)
boxnode:setCascadeColorEnabled(true)
boxnode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(boxnode)
layout:setRightMargin(580.0000)
layout:setTopMargin(646.0000)
Layer:addChild(boxnode)

--Create Bg_2
local Bg_2 = ccui.ImageView:create()
Bg_2:ignoreContentAdaptWithSize(false)
Bg_2:loadTexture("03_01_Shop/picture_058.png", 1)
Bg_2:setLayoutComponentEnabled(true)
Bg_2:setName("Bg_2")
Bg_2:setTag(206)
Bg_2:setCascadeColorEnabled(true)
Bg_2:setCascadeOpacityEnabled(true)
Bg_2:setPosition(363.0000, 353.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_2)
layout:setSize({width = 338.0000, height = 196.0000})
layout:setLeftMargin(194.0000)
layout:setRightMargin(-532.0000)
layout:setTopMargin(-451.0000)
layout:setBottomMargin(255.0000)
boxnode:addChild(Bg_2)

--Create PropIcon
local PropIcon = ccui.ImageView:create()
PropIcon:ignoreContentAdaptWithSize(false)
PropIcon:loadTexture("Default/ImageFile.png", 1)
PropIcon:setLayoutComponentEnabled(true)
PropIcon:setName("PropIcon")
PropIcon:setTag(69)
PropIcon:setCascadeColorEnabled(true)
PropIcon:setCascadeOpacityEnabled(true)
PropIcon:setPosition(290.0000, 410.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropIcon)
layout:setSize({width = 200.0000, height = 300.0000})
layout:setLeftMargin(190.0000)
layout:setRightMargin(-390.0000)
layout:setTopMargin(-560.0000)
layout:setBottomMargin(260.0000)
boxnode:addChild(PropIcon)

--Create TitleText
local TitleText = ccui.Text:create()
TitleText:ignoreContentAdaptWithSize(true)
TitleText:setTextAreaSize({width = 0, height = 0})
TitleText:setFontName("font/Font001.ttf")
TitleText:setFontSize(32)
TitleText:setString([[骰盅名称]])
TitleText:setTextHorizontalAlignment(1)
TitleText:setTextVerticalAlignment(1)
TitleText:setLayoutComponentEnabled(true)
TitleText:setName("TitleText")
TitleText:setTag(68)
TitleText:setCascadeColorEnabled(true)
TitleText:setCascadeOpacityEnabled(true)
TitleText:setPosition(290.0000, 193.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText)
layout:setSize({width = 131.0000, height = 42.0000})
layout:setLeftMargin(224.5000)
layout:setRightMargin(-355.5000)
layout:setTopMargin(-214.0000)
layout:setBottomMargin(172.0000)
boxnode:addChild(TitleText)

--Create TitleDepictText
local TitleDepictText = ccui.Text:create()
TitleDepictText:ignoreContentAdaptWithSize(true)
TitleDepictText:setTextAreaSize({width = 0, height = 0})
TitleDepictText:setFontName("font/Default.ttf")
TitleDepictText:setFontSize(28)
TitleDepictText:setString([[古典皇室风格筛盅]])
TitleDepictText:setTextHorizontalAlignment(1)
TitleDepictText:setTextVerticalAlignment(1)
TitleDepictText:setLayoutComponentEnabled(true)
TitleDepictText:setName("TitleDepictText")
TitleDepictText:setTag(211)
TitleDepictText:setCascadeColorEnabled(true)
TitleDepictText:setCascadeOpacityEnabled(true)
TitleDepictText:setPosition(290.0000, 145.0000)
TitleDepictText:setTextColor({r = 193, g = 189, b = 237})
layout = ccui.LayoutComponent:bindLayoutComponent(TitleDepictText)
layout:setSize({width = 227.0000, height = 37.0000})
layout:setLeftMargin(176.5000)
layout:setRightMargin(-403.5000)
layout:setTopMargin(-163.5000)
layout:setBottomMargin(126.5000)
boxnode:addChild(TitleDepictText)

--Create UseButton

local luaScript = require("csd.LuaScript.newButton")
local UseButton = luaScript.CreateCustomNode()
UseButton:ignoreContentAdaptWithSize(false)
UseButton:loadTextureNormal("02_01_Boast/button_013.png", 1)
UseButton:loadTexturePressed("02_01_Boast/button_013.png", 1)
UseButton:loadTextureDisabled("02_01_Boast/button_013.png", 1)
UseButton:setTitleFontSize(14)
UseButton:setScale9Enabled(true)
UseButton:setCapInsets({x = 47, y = 14, width = 49, height = 47})
UseButton:setLayoutComponentEnabled(true)
UseButton:setName("UseButton")
UseButton:setTag(87)
UseButton:setCascadeColorEnabled(true)
UseButton:setCascadeOpacityEnabled(true)
UseButton:setPosition(290.0000, 74.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(UseButton)
layout:setSize({width = 254.0000, height = 86.0000})
layout:setLeftMargin(163.0000)
layout:setRightMargin(-417.0000)
layout:setTopMargin(-117.0000)
layout:setBottomMargin(31.0000)

luaScript.SetDownScele(UseButton, "0.9800")
luaScript.SetClickEffect(UseButton, "Sound004")
luaScript.SetDownColor(UseButton, {r = 65, g = 65, b = 70})
boxnode:addChild(UseButton)

--Create UseText_TT
local UseText_TT = ccui.Text:create()
UseText_TT:ignoreContentAdaptWithSize(true)
UseText_TT:setTextAreaSize({width = 0, height = 0})
UseText_TT:setFontName("font/Font001.ttf")
UseText_TT:setFontSize(30)
UseText_TT:setString([[使用]])
UseText_TT:setTextHorizontalAlignment(1)
UseText_TT:setTextVerticalAlignment(1)
UseText_TT:enableShadow({r = 243, g = 228, b = 181, a = 255}, {width = 0, height = -1}, 0)
UseText_TT:setLayoutComponentEnabled(true)
UseText_TT:setName("UseText_TT")
UseText_TT:setTag(88)
UseText_TT:setCascadeColorEnabled(true)
UseText_TT:setCascadeOpacityEnabled(true)
UseText_TT:setPosition(127.0000, 52.5000)
UseText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(UseText_TT)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6105)
layout:setPercentWidth(0.2402)
layout:setPercentHeight(0.4651)
layout:setSize({width = 61.0000, height = 40.0000})
layout:setLeftMargin(96.5000)
layout:setRightMargin(96.5000)
layout:setTopMargin(13.5000)
layout:setBottomMargin(32.5000)
UseButton:addChild(UseText_TT)

--Create UsingNode
local UsingNode=cc.Node:create()
UsingNode:setName("UsingNode")
UsingNode:setTag(107)
UsingNode:setCascadeColorEnabled(true)
UsingNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(UsingNode)
boxnode:addChild(UsingNode)

--Create UsingBg
local UsingBg = cc.Sprite:createWithSpriteFrameName("01_03_PropKnapsack/frame_131.png")
UsingBg:setName("UsingBg")
UsingBg:setTag(109)
UsingBg:setCascadeColorEnabled(true)
UsingBg:setCascadeOpacityEnabled(true)
UsingBg:setPosition(290.0000, 78.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(UsingBg)
layout:setSize({width = 240.0000, height = 62.0000})
layout:setLeftMargin(170.0000)
layout:setRightMargin(-410.0000)
layout:setTopMargin(-109.0000)
layout:setBottomMargin(47.0000)
UsingBg:setBlendFunc({src = 1, dst = 771})
UsingNode:addChild(UsingBg)

--Create UsingIcon
local UsingIcon = ccui.ImageView:create()
UsingIcon:ignoreContentAdaptWithSize(false)
UsingIcon:loadTexture("01_03_PropKnapsack/icon_079.png", 1)
UsingIcon:setScale9Enabled(true)
UsingIcon:setCapInsets({x = 15, y = 15, width = 10, height = 10})
UsingIcon:setLayoutComponentEnabled(true)
UsingIcon:setName("UsingIcon")
UsingIcon:setTag(86)
UsingIcon:setCascadeColorEnabled(true)
UsingIcon:setCascadeOpacityEnabled(true)
UsingIcon:setPosition(243.0000, 78.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(UsingIcon)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(223.0000)
layout:setRightMargin(-263.0000)
layout:setTopMargin(-98.0000)
layout:setBottomMargin(58.0000)
UsingNode:addChild(UsingIcon)

--Create UsingText_TT
local UsingText_TT = ccui.Text:create()
UsingText_TT:ignoreContentAdaptWithSize(true)
UsingText_TT:setTextAreaSize({width = 0, height = 0})
UsingText_TT:setFontName("font/Default.ttf")
UsingText_TT:setFontSize(26)
UsingText_TT:setString([[使用中]])
UsingText_TT:setLayoutComponentEnabled(true)
UsingText_TT:setName("UsingText_TT")
UsingText_TT:setTag(110)
UsingText_TT:setCascadeColorEnabled(true)
UsingText_TT:setCascadeOpacityEnabled(true)
UsingText_TT:setAnchorPoint(0.0000, 0.5000)
UsingText_TT:setPosition(266.5000, 80.0000)
UsingText_TT:setTextColor({r = 216, g = 213, b = 244})
layout = ccui.LayoutComponent:bindLayoutComponent(UsingText_TT)
layout:setSize({width = 79.0000, height = 34.0000})
layout:setLeftMargin(266.5000)
layout:setRightMargin(-345.5000)
layout:setTopMargin(-97.0000)
layout:setBottomMargin(63.0000)
UsingNode:addChild(UsingText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

