--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_11_ActivitiesBulletin/01_11_ActivitiesBulletin_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 52.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(174)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(720.0000)
layout:setTopMargin(52.0000)
Layer:addChild(Bg)

--Create Bg_1
local Bg_1 = cc.Sprite:createWithSpriteFrameName("01_11_ActivitiesBulletin/strip_011.png")
Bg_1:setName("Bg_1")
Bg_1:setTag(940)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setPosition(360.0000, 26.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 702.0000, height = 44.0000})
layout:setLeftMargin(9.0000)
layout:setRightMargin(-711.0000)
layout:setTopMargin(-48.0000)
layout:setBottomMargin(4.0000)
Bg_1:setBlendFunc({src = 1, dst = 771})
Bg:addChild(Bg_1)

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(179)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(720.0000)
layout:setTopMargin(52.0000)
Layer:addChild(Middle)

--Create WalkingLanternIcon
local WalkingLanternIcon = ccui.ImageView:create()
WalkingLanternIcon:ignoreContentAdaptWithSize(false)
WalkingLanternIcon:loadTexture("01_11_ActivitiesBulletin/icon_039.png", 1)
WalkingLanternIcon:setLayoutComponentEnabled(true)
WalkingLanternIcon:setName("WalkingLanternIcon")
WalkingLanternIcon:setTag(180)
WalkingLanternIcon:setCascadeColorEnabled(true)
WalkingLanternIcon:setCascadeOpacityEnabled(true)
WalkingLanternIcon:setPosition(36.0000, 25.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(WalkingLanternIcon)
layout:setSize({width = 42.0000, height = 38.0000})
layout:setLeftMargin(15.0000)
layout:setRightMargin(-57.0000)
layout:setTopMargin(-44.0000)
layout:setBottomMargin(6.0000)
Middle:addChild(WalkingLanternIcon)

--Create WalkingLanternPanel
local WalkingLanternPanel = ccui.Layout:create()
WalkingLanternPanel:ignoreContentAdaptWithSize(false)
WalkingLanternPanel:setClippingEnabled(true)
WalkingLanternPanel:setBackGroundColorOpacity(102)
WalkingLanternPanel:setLayoutComponentEnabled(true)
WalkingLanternPanel:setName("WalkingLanternPanel")
WalkingLanternPanel:setTag(65)
WalkingLanternPanel:setCascadeColorEnabled(true)
WalkingLanternPanel:setCascadeOpacityEnabled(true)
WalkingLanternPanel:setAnchorPoint(0.0000, 0.5000)
WalkingLanternPanel:setPosition(60.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(WalkingLanternPanel)
layout:setSize({width = 642.0000, height = 52.0000})
layout:setLeftMargin(60.0000)
layout:setRightMargin(-702.0000)
layout:setTopMargin(-53.0000)
layout:setBottomMargin(1.0000)
Middle:addChild(WalkingLanternPanel)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("font/Default.ttf")
Text_1:setFontSize(22)
Text_1:setString([[為建設綠色將康的遊戲環境，使用戶更好地平衡遊戲與生活,合]])
Text_1:setTextVerticalAlignment(1)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(55)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 0.5000)
Text_1:setPosition(0.0000, 26.0000)
Text_1:setTextColor({r = 188, g = 192, b = 239})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9377)
layout:setPercentHeight(0.5577)
layout:setSize({width = 602.0000, height = 29.0000})
layout:setRightMargin(40.0000)
layout:setTopMargin(11.5000)
layout:setBottomMargin(11.5000)
WalkingLanternPanel:addChild(Text_1)

--Create ConnectLanternPanel
local ConnectLanternPanel = ccui.Layout:create()
ConnectLanternPanel:ignoreContentAdaptWithSize(false)
ConnectLanternPanel:setClippingEnabled(true)
ConnectLanternPanel:setBackGroundColorOpacity(102)
ConnectLanternPanel:setTouchEnabled(true);
ConnectLanternPanel:setLayoutComponentEnabled(true)
ConnectLanternPanel:setName("ConnectLanternPanel")
ConnectLanternPanel:setTag(1638)
ConnectLanternPanel:setCascadeColorEnabled(true)
ConnectLanternPanel:setCascadeOpacityEnabled(true)
ConnectLanternPanel:setVisible(false)
ConnectLanternPanel:setAnchorPoint(0.0000, 0.5000)
ConnectLanternPanel:setPosition(60.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConnectLanternPanel)
layout:setSize({width = 642.0000, height = 52.0000})
layout:setLeftMargin(60.0000)
layout:setRightMargin(-702.0000)
layout:setTopMargin(-53.0000)
layout:setBottomMargin(1.0000)
Middle:addChild(ConnectLanternPanel)

--Create ConnectText_1
local ConnectText_1 = ccui.Text:create()
ConnectText_1:ignoreContentAdaptWithSize(true)
ConnectText_1:setTextAreaSize({width = 0, height = 0})
ConnectText_1:setFontName("font/Default.ttf")
ConnectText_1:setFontSize(22)
ConnectText_1:setString([[為建設綠色將康的遊戲環境]])
ConnectText_1:setTextVerticalAlignment(1)
ConnectText_1:setLayoutComponentEnabled(true)
ConnectText_1:setName("ConnectText_1")
ConnectText_1:setTag(1639)
ConnectText_1:setCascadeColorEnabled(true)
ConnectText_1:setCascadeOpacityEnabled(true)
ConnectText_1:setAnchorPoint(0.0000, 0.5000)
ConnectText_1:setPosition(0.0000, 26.0000)
ConnectText_1:setTextColor({r = 188, g = 192, b = 239})
layout = ccui.LayoutComponent:bindLayoutComponent(ConnectText_1)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4159)
layout:setPercentHeight(0.5577)
layout:setSize({width = 267.0000, height = 29.0000})
layout:setRightMargin(375.0000)
layout:setTopMargin(11.5000)
layout:setBottomMargin(11.5000)
ConnectLanternPanel:addChild(ConnectText_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

