--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_11_ActivitiesBulletin/01_11_ActivitiesBulletin_1.plist",	
"ui/00_01_Common/00_01_Common_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 712.0000, height = 248.0000})

--Create ActivitiesCell
local ActivitiesCell=cc.Node:create()
ActivitiesCell:setName("ActivitiesCell")
ActivitiesCell:setTag(113)
ActivitiesCell:setCascadeColorEnabled(true)
ActivitiesCell:setCascadeOpacityEnabled(true)
ActivitiesCell:setPosition(356.0000, 124.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivitiesCell)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(356.0000)
layout:setRightMargin(356.0000)
layout:setTopMargin(124.0000)
layout:setBottomMargin(124.0000)
Layer:addChild(ActivitiesCell)

--Create ActivitiesPanel
local ActivitiesPanel = ccui.Layout:create()
ActivitiesPanel:ignoreContentAdaptWithSize(false)
ActivitiesPanel:setClippingEnabled(false)
ActivitiesPanel:setBackGroundColorOpacity(102)
ActivitiesPanel:setTouchEnabled(true);
ActivitiesPanel:setLayoutComponentEnabled(true)
ActivitiesPanel:setName("ActivitiesPanel")
ActivitiesPanel:setTag(115)
ActivitiesPanel:setCascadeColorEnabled(true)
ActivitiesPanel:setCascadeOpacityEnabled(true)
ActivitiesPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivitiesPanel)
layout:setSize({width = 712.0000, height = 248.0000})
layout:setLeftMargin(-356.0000)
layout:setRightMargin(-356.0000)
layout:setTopMargin(-124.0000)
layout:setBottomMargin(-124.0000)
ActivitiesCell:addChild(ActivitiesPanel)

--Create ActivityBg
local ActivityBg = ccui.ImageView:create()
ActivityBg:ignoreContentAdaptWithSize(false)
ActivityBg:loadTexture("01_11_ActivitiesBulletin/frame_117.png", 1)
ActivityBg:setScale9Enabled(true)
ActivityBg:setCapInsets({x = 234, y = 81, width = 244, height = 86})
ActivityBg:setLayoutComponentEnabled(true)
ActivityBg:setName("ActivityBg")
ActivityBg:setTag(133)
ActivityBg:setCascadeColorEnabled(true)
ActivityBg:setCascadeOpacityEnabled(true)
ActivityBg:setPosition(356.0006, 124.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivityBg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 712.0000, height = 248.0000})
layout:setLeftMargin(0.0006)
layout:setRightMargin(-0.0006)
ActivitiesPanel:addChild(ActivityBg)

--Create ActivitiesImage
local ActivitiesImage = ccui.ImageView:create()
ActivitiesImage:ignoreContentAdaptWithSize(false)
ActivitiesImage:loadTexture("01_11_ActivitiesBulletin/frame_120.png", 1)
ActivitiesImage:setLayoutComponentEnabled(true)
ActivitiesImage:setName("ActivitiesImage")
ActivitiesImage:setTag(114)
ActivitiesImage:setCascadeColorEnabled(true)
ActivitiesImage:setCascadeOpacityEnabled(true)
ActivitiesImage:setPosition(356.0012, 124.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivitiesImage)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9635)
layout:setPercentHeight(0.8468)
layout:setSize({width = 686.0000, height = 210.0000})
layout:setLeftMargin(13.0012)
layout:setRightMargin(12.9988)
layout:setTopMargin(19.0000)
layout:setBottomMargin(19.0000)
ActivitiesPanel:addChild(ActivitiesImage)

--Create ActivitiesTipDotIcon
local ActivitiesTipDotIcon = ccui.ImageView:create()
ActivitiesTipDotIcon:ignoreContentAdaptWithSize(false)
ActivitiesTipDotIcon:loadTexture("00_01_Common/icon_045.png", 1)
ActivitiesTipDotIcon:setLayoutComponentEnabled(true)
ActivitiesTipDotIcon:setName("ActivitiesTipDotIcon")
ActivitiesTipDotIcon:setTag(684)
ActivitiesTipDotIcon:setCascadeColorEnabled(true)
ActivitiesTipDotIcon:setCascadeOpacityEnabled(true)
ActivitiesTipDotIcon:setPosition(694.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivitiesTipDotIcon)
layout:setPositionPercentX(0.9747)
layout:setPositionPercentY(0.9274)
layout:setPercentWidth(0.0758)
layout:setPercentHeight(0.2177)
layout:setSize({width = 54.0000, height = 54.0000})
layout:setLeftMargin(667.0000)
layout:setRightMargin(-9.0000)
layout:setTopMargin(-9.0000)
layout:setBottomMargin(203.0000)
ActivitiesPanel:addChild(ActivitiesTipDotIcon)

--Create ActivitiesTitleImage_IVT
local ActivitiesTitleImage_IVT = ccui.ImageView:create()
ActivitiesTitleImage_IVT:ignoreContentAdaptWithSize(false)
ActivitiesTitleImage_IVT:loadTexture("01_11_ActivitiesBulletin/picture_055_zh_CN.png", 1)
ActivitiesTitleImage_IVT:setLayoutComponentEnabled(true)
ActivitiesTitleImage_IVT:setName("ActivitiesTitleImage_IVT")
ActivitiesTitleImage_IVT:setTag(105)
ActivitiesTitleImage_IVT:setCascadeColorEnabled(true)
ActivitiesTitleImage_IVT:setCascadeOpacityEnabled(true)
ActivitiesTitleImage_IVT:setAnchorPoint(1.0000, 1.0000)
ActivitiesTitleImage_IVT:setPosition(704.0016, 251.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(ActivitiesTitleImage_IVT)
layout:setPositionPercentX(0.9888)
layout:setPositionPercentY(1.0121)
layout:setPercentWidth(0.5758)
layout:setPercentHeight(0.6048)
layout:setSize({width = 410.0000, height = 150.0000})
layout:setLeftMargin(294.0016)
layout:setRightMargin(7.9984)
layout:setTopMargin(-3.0002)
layout:setBottomMargin(101.0002)
ActivitiesPanel:addChild(ActivitiesTitleImage_IVT)

--Create TimeText_TT
local TimeText_TT = ccui.Text:create()
TimeText_TT:ignoreContentAdaptWithSize(true)
TimeText_TT:setTextAreaSize({width = 0, height = 0})
TimeText_TT:setFontName("font/Default.ttf")
TimeText_TT:setFontSize(24)
TimeText_TT:setString([[7天24小时后结束]])
TimeText_TT:setTextHorizontalAlignment(2)
TimeText_TT:setTextVerticalAlignment(1)
TimeText_TT:enableShadow({r = 30, g = 24, b = 134, a = 255}, {width = 2, height = -2}, 0)
TimeText_TT:enableOutline({r = 142, g = 50, b = 173, a = 255}, 2)
TimeText_TT:setLayoutComponentEnabled(true)
TimeText_TT:setName("TimeText_TT")
TimeText_TT:setTag(106)
TimeText_TT:setCascadeColorEnabled(true)
TimeText_TT:setCascadeOpacityEnabled(true)
TimeText_TT:setAnchorPoint(1.0000, 0.5000)
TimeText_TT:setPosition(684.5029, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TimeText_TT)
layout:setPositionPercentX(0.9614)
layout:setPositionPercentY(0.1976)
layout:setPercentWidth(0.2683)
layout:setPercentHeight(0.1452)
layout:setSize({width = 191.0000, height = 36.0000})
layout:setLeftMargin(493.5029)
layout:setRightMargin(27.4971)
layout:setTopMargin(181.0000)
layout:setBottomMargin(31.0000)
ActivitiesPanel:addChild(TimeText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

