--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_11_ActivitiesBulletin/01_11_ActivitiesBulletin_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 708.0000, height = 164.0000})

--Create Notice
local Notice=cc.Node:create()
Notice:setName("Notice")
Notice:setTag(102)
Notice:setCascadeColorEnabled(true)
Notice:setCascadeOpacityEnabled(true)
Notice:setPosition(354.0000, 82.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Notice)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(354.0000)
layout:setRightMargin(354.0000)
layout:setTopMargin(82.0000)
layout:setBottomMargin(82.0000)
Layer:addChild(Notice)

--Create NoticePanel
local NoticePanel = ccui.Layout:create()
NoticePanel:ignoreContentAdaptWithSize(false)
NoticePanel:setClippingEnabled(false)
NoticePanel:setBackGroundColorOpacity(102)
NoticePanel:setTouchEnabled(true);
NoticePanel:setLayoutComponentEnabled(true)
NoticePanel:setName("NoticePanel")
NoticePanel:setTag(33)
NoticePanel:setCascadeColorEnabled(true)
NoticePanel:setCascadeOpacityEnabled(true)
NoticePanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(NoticePanel)
layout:setSize({width = 708.0000, height = 164.0000})
layout:setLeftMargin(-354.0000)
layout:setRightMargin(-354.0000)
layout:setTopMargin(-82.0000)
layout:setBottomMargin(-82.0000)
Notice:addChild(NoticePanel)

--Create NoticeBg
local NoticeBg = ccui.ImageView:create()
NoticeBg:ignoreContentAdaptWithSize(false)
NoticeBg:loadTexture("01_11_ActivitiesBulletin/frame_104.png", 1)
NoticeBg:setScale9Enabled(true)
NoticeBg:setCapInsets({x = 32, y = 54, width = 34, height = 56})
NoticeBg:setLayoutComponentEnabled(true)
NoticeBg:setName("NoticeBg")
NoticeBg:setTag(22)
NoticeBg:setCascadeColorEnabled(true)
NoticeBg:setCascadeOpacityEnabled(true)
NoticeBg:setPosition(354.0000, 82.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(NoticeBg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 708.0000, height = 164.0000})
NoticePanel:addChild(NoticeBg)

--Create TitleText
local TitleText = ccui.Text:create()
TitleText:ignoreContentAdaptWithSize(true)
TitleText:setTextAreaSize({width = 0, height = 0})
TitleText:setFontName("font/Font001.ttf")
TitleText:setFontSize(26)
TitleText:setString([[公告标题XXXXXX]])
TitleText:setTextVerticalAlignment(1)
TitleText:setLayoutComponentEnabled(true)
TitleText:setName("TitleText")
TitleText:setTag(32)
TitleText:setCascadeColorEnabled(true)
TitleText:setCascadeOpacityEnabled(true)
TitleText:setAnchorPoint(0.0000, 0.5000)
TitleText:setPosition(29.0027, 121.0002)
TitleText:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText)
layout:setPositionPercentX(0.0410)
layout:setPositionPercentY(0.7378)
layout:setPercentWidth(0.3037)
layout:setPercentHeight(0.2073)
layout:setSize({width = 215.0000, height = 34.0000})
layout:setLeftMargin(29.0027)
layout:setRightMargin(463.9973)
layout:setTopMargin(25.9998)
layout:setBottomMargin(104.0002)
NoticePanel:addChild(TitleText)

--Create ContentText
local ContentText = ccui.Text:create()
ContentText:ignoreContentAdaptWithSize(true)
ContentText:setTextAreaSize({width = 0, height = 0})
ContentText:setFontName("font/Default.ttf")
ContentText:setFontSize(24)
ContentText:setString([[【BUG修复和优化】Facebook登录BUG]])
ContentText:setLayoutComponentEnabled(true)
ContentText:setName("ContentText")
ContentText:setTag(34)
ContentText:setCascadeColorEnabled(true)
ContentText:setCascadeOpacityEnabled(true)
ContentText:setAnchorPoint(0.0000, 0.5000)
ContentText:setPosition(18.5005, 45.0003)
ContentText:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(ContentText)
layout:setPositionPercentX(0.0261)
layout:setPositionPercentY(0.2744)
layout:setPercentWidth(0.6045)
layout:setPercentHeight(0.1951)
layout:setSize({width = 428.0000, height = 32.0000})
layout:setLeftMargin(18.5005)
layout:setRightMargin(261.4995)
layout:setTopMargin(102.9997)
layout:setBottomMargin(29.0003)
NoticePanel:addChild(ContentText)

--Create TimeNum
local TimeNum = ccui.Text:create()
TimeNum:ignoreContentAdaptWithSize(true)
TimeNum:setTextAreaSize({width = 0, height = 0})
TimeNum:setFontName("font/Default.ttf")
TimeNum:setFontSize(22)
TimeNum:setString([[2202-02-04]])
TimeNum:setLayoutComponentEnabled(true)
TimeNum:setName("TimeNum")
TimeNum:setTag(35)
TimeNum:setCascadeColorEnabled(true)
TimeNum:setCascadeOpacityEnabled(true)
TimeNum:setAnchorPoint(1.0000, 0.5000)
TimeNum:setPosition(678.5006, 115.9997)
TimeNum:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(TimeNum)
layout:setPositionPercentX(0.9583)
layout:setPositionPercentY(0.7073)
layout:setPercentWidth(0.1780)
layout:setPercentHeight(0.1768)
layout:setSize({width = 126.0000, height = 29.0000})
layout:setLeftMargin(552.5006)
layout:setRightMargin(29.4994)
layout:setTopMargin(33.5003)
layout:setBottomMargin(101.4997)
NoticePanel:addChild(TimeNum)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

