--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_06_PersonalCenter/01_06_PersonalCenter_1.plist",	
"ui/01_10_Mail/01_10_Mail_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 378.0000})

--Create Bg
local Bg=cc.Node:create()
Bg:setName("Bg")
Bg:setTag(44)
Bg:setCascadeColorEnabled(true)
Bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg)
layout:setRightMargin(720.0000)
layout:setTopMargin(378.0000)
Layer:addChild(Bg)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("01_06_PersonalCenter/frame_038.png", 1)
Bg_1:setScale9Enabled(true)
Bg_1:setCapInsets({x = 16, y = 124, width = 18, height = 130})
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(47)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setAnchorPoint(0.0000, 0.0000)
Bg_1:setPosition(86.0020, 0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 558.0000, height = 378.0000})
layout:setLeftMargin(86.0020)
layout:setRightMargin(-644.0020)
layout:setTopMargin(-378.0001)
layout:setBottomMargin(0.0001)
Bg:addChild(Bg_1)

--Create Middle
local Middle=cc.Node:create()
Middle:setName("Middle")
Middle:setTag(46)
Middle:setCascadeColorEnabled(true)
Middle:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Middle)
layout:setRightMargin(720.0000)
layout:setTopMargin(378.0000)
Layer:addChild(Middle)

--Create TitleText_TT
local TitleText_TT = ccui.Text:create()
TitleText_TT:ignoreContentAdaptWithSize(true)
TitleText_TT:setTextAreaSize({width = 0, height = 0})
TitleText_TT:setFontName("font/Font001.ttf")
TitleText_TT:setFontSize(32)
TitleText_TT:setString([[修改性别]])
TitleText_TT:setTextHorizontalAlignment(1)
TitleText_TT:setTextVerticalAlignment(1)
TitleText_TT:setLayoutComponentEnabled(true)
TitleText_TT:setName("TitleText_TT")
TitleText_TT:setTag(52)
TitleText_TT:setCascadeColorEnabled(true)
TitleText_TT:setCascadeOpacityEnabled(true)
TitleText_TT:setPosition(364.0000, 340.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TitleText_TT)
layout:setSize({width = 129.0000, height = 42.0000})
layout:setLeftMargin(299.5000)
layout:setRightMargin(-428.5000)
layout:setTopMargin(-361.0000)
layout:setBottomMargin(319.0000)
Middle:addChild(TitleText_TT)

--Create Male
local Male=cc.Node:create()
Male:setName("Male")
Male:setTag(61)
Male:setCascadeColorEnabled(true)
Male:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Male)
Middle:addChild(Male)

--Create MaleIcon
local MaleIcon = ccui.ImageView:create()
MaleIcon:ignoreContentAdaptWithSize(false)
MaleIcon:loadTexture("01_06_PersonalCenter/icon_030.png", 1)
MaleIcon:setLayoutComponentEnabled(true)
MaleIcon:setName("MaleIcon")
MaleIcon:setTag(425)
MaleIcon:setCascadeColorEnabled(true)
MaleIcon:setCascadeOpacityEnabled(true)
MaleIcon:setPosition(217.0000, 224.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(MaleIcon)
layout:setSize({width = 34.0000, height = 38.0000})
layout:setLeftMargin(200.0000)
layout:setRightMargin(-234.0000)
layout:setTopMargin(-243.0000)
layout:setBottomMargin(205.0000)
Male:addChild(MaleIcon)

--Create MaleCheckBox
local MaleCheckBox = ccui.CheckBox:create()
MaleCheckBox:ignoreContentAdaptWithSize(false)
MaleCheckBox:loadTextureBackGround("01_06_PersonalCenter/frame_039.png", 1)
MaleCheckBox:loadTextureBackGroundSelected("01_06_PersonalCenter/frame_039.png", 1)
MaleCheckBox:loadTextureBackGroundDisabled("01_06_PersonalCenter/frame_039.png", 1)
MaleCheckBox:loadTextureFrontCross("01_06_PersonalCenter/icon_033.png", 1)
MaleCheckBox:loadTextureFrontCrossDisabled("01_06_PersonalCenter/icon_033.png", 1)
MaleCheckBox:setSelected(true)
MaleCheckBox:setLayoutComponentEnabled(true)
MaleCheckBox:setName("MaleCheckBox")
MaleCheckBox:setTag(83)
MaleCheckBox:setCascadeColorEnabled(true)
MaleCheckBox:setCascadeOpacityEnabled(true)
MaleCheckBox:setPosition(167.0001, 224.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(MaleCheckBox)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(143.0001)
layout:setRightMargin(-191.0001)
layout:setTopMargin(-248.0002)
layout:setBottomMargin(200.0002)
Male:addChild(MaleCheckBox)

--Create Female
local Female=cc.Node:create()
Female:setName("Female")
Female:setTag(62)
Female:setCascadeColorEnabled(true)
Female:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Female)
Middle:addChild(Female)

--Create FemaleIcon
local FemaleIcon = ccui.ImageView:create()
FemaleIcon:ignoreContentAdaptWithSize(false)
FemaleIcon:loadTexture("01_06_PersonalCenter/icon_031.png", 1)
FemaleIcon:setLayoutComponentEnabled(true)
FemaleIcon:setName("FemaleIcon")
FemaleIcon:setTag(426)
FemaleIcon:setCascadeColorEnabled(true)
FemaleIcon:setCascadeOpacityEnabled(true)
FemaleIcon:setPosition(347.0000, 221.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FemaleIcon)
layout:setSize({width = 34.0000, height = 38.0000})
layout:setLeftMargin(330.0000)
layout:setRightMargin(-364.0000)
layout:setTopMargin(-240.0000)
layout:setBottomMargin(202.0000)
Female:addChild(FemaleIcon)

--Create FemaleCheckBox
local FemaleCheckBox = ccui.CheckBox:create()
FemaleCheckBox:ignoreContentAdaptWithSize(false)
FemaleCheckBox:loadTextureBackGround("01_06_PersonalCenter/frame_039.png", 1)
FemaleCheckBox:loadTextureBackGroundSelected("01_06_PersonalCenter/frame_039.png", 1)
FemaleCheckBox:loadTextureBackGroundDisabled("01_06_PersonalCenter/frame_039.png", 1)
FemaleCheckBox:loadTextureFrontCross("01_06_PersonalCenter/icon_033.png", 1)
FemaleCheckBox:loadTextureFrontCrossDisabled("01_06_PersonalCenter/icon_033.png", 1)
FemaleCheckBox:setLayoutComponentEnabled(true)
FemaleCheckBox:setName("FemaleCheckBox")
FemaleCheckBox:setTag(84)
FemaleCheckBox:setCascadeColorEnabled(true)
FemaleCheckBox:setCascadeOpacityEnabled(true)
FemaleCheckBox:setPosition(296.9994, 224.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FemaleCheckBox)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(272.9994)
layout:setRightMargin(-320.9994)
layout:setTopMargin(-248.0000)
layout:setBottomMargin(200.0000)
Female:addChild(FemaleCheckBox)

--Create NoDisplayed
local NoDisplayed=cc.Node:create()
NoDisplayed:setName("NoDisplayed")
NoDisplayed:setTag(63)
NoDisplayed:setCascadeColorEnabled(true)
NoDisplayed:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(NoDisplayed)
Middle:addChild(NoDisplayed)

--Create NoDisplayedText_TT
local NoDisplayedText_TT = ccui.Text:create()
NoDisplayedText_TT:ignoreContentAdaptWithSize(true)
NoDisplayedText_TT:setTextAreaSize({width = 0, height = 0})
NoDisplayedText_TT:setFontName("font/Default.ttf")
NoDisplayedText_TT:setFontSize(28)
NoDisplayedText_TT:setString([[不显示]])
NoDisplayedText_TT:setTextVerticalAlignment(1)
NoDisplayedText_TT:setLayoutComponentEnabled(true)
NoDisplayedText_TT:setName("NoDisplayedText_TT")
NoDisplayedText_TT:setTag(66)
NoDisplayedText_TT:setCascadeColorEnabled(true)
NoDisplayedText_TT:setCascadeOpacityEnabled(true)
NoDisplayedText_TT:setAnchorPoint(0.0000, 0.5000)
NoDisplayedText_TT:setPosition(461.5000, 227.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(NoDisplayedText_TT)
layout:setSize({width = 87.0000, height = 37.0000})
layout:setLeftMargin(461.5000)
layout:setRightMargin(-548.5000)
layout:setTopMargin(-245.5000)
layout:setBottomMargin(208.5000)
NoDisplayed:addChild(NoDisplayedText_TT)

--Create NoDisplayedCheckBox
local NoDisplayedCheckBox = ccui.CheckBox:create()
NoDisplayedCheckBox:ignoreContentAdaptWithSize(false)
NoDisplayedCheckBox:loadTextureBackGround("01_06_PersonalCenter/frame_039.png", 1)
NoDisplayedCheckBox:loadTextureBackGroundSelected("01_06_PersonalCenter/frame_039.png", 1)
NoDisplayedCheckBox:loadTextureBackGroundDisabled("01_06_PersonalCenter/frame_039.png", 1)
NoDisplayedCheckBox:loadTextureFrontCross("01_06_PersonalCenter/icon_033.png", 1)
NoDisplayedCheckBox:loadTextureFrontCrossDisabled("01_06_PersonalCenter/icon_033.png", 1)
NoDisplayedCheckBox:setLayoutComponentEnabled(true)
NoDisplayedCheckBox:setName("NoDisplayedCheckBox")
NoDisplayedCheckBox:setTag(85)
NoDisplayedCheckBox:setCascadeColorEnabled(true)
NoDisplayedCheckBox:setCascadeOpacityEnabled(true)
NoDisplayedCheckBox:setPosition(422.0016, 224.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(NoDisplayedCheckBox)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(398.0016)
layout:setRightMargin(-446.0016)
layout:setTopMargin(-248.0002)
layout:setBottomMargin(200.0002)
NoDisplayed:addChild(NoDisplayedCheckBox)

--Create Diamond
local Diamond=cc.Node:create()
Diamond:setName("Diamond")
Diamond:setTag(57)
Diamond:setCascadeColorEnabled(true)
Diamond:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Diamond)
Middle:addChild(Diamond)

--Create DiamondIcon
local DiamondIcon = ccui.ImageView:create()
DiamondIcon:ignoreContentAdaptWithSize(false)
DiamondIcon:loadTexture("01_06_PersonalCenter/icon_032.png", 1)
DiamondIcon:setLayoutComponentEnabled(true)
DiamondIcon:setName("DiamondIcon")
DiamondIcon:setTag(58)
DiamondIcon:setCascadeColorEnabled(true)
DiamondIcon:setCascadeOpacityEnabled(true)
DiamondIcon:setPosition(163.0001, 159.0023)
layout = ccui.LayoutComponent:bindLayoutComponent(DiamondIcon)
layout:setSize({width = 48.0000, height = 42.0000})
layout:setLeftMargin(139.0001)
layout:setRightMargin(-187.0001)
layout:setTopMargin(-180.0023)
layout:setBottomMargin(138.0023)
Diamond:addChild(DiamondIcon)

--Create DiamondNum
local DiamondNum = ccui.Text:create()
DiamondNum:ignoreContentAdaptWithSize(true)
DiamondNum:setTextAreaSize({width = 0, height = 0})
DiamondNum:setFontName("font/Font003.ttf")
DiamondNum:setFontSize(24)
DiamondNum:setString([[500]])
DiamondNum:setTextHorizontalAlignment(1)
DiamondNum:setTextVerticalAlignment(1)
DiamondNum:setLayoutComponentEnabled(true)
DiamondNum:setName("DiamondNum")
DiamondNum:setTag(59)
DiamondNum:setCascadeColorEnabled(true)
DiamondNum:setCascadeOpacityEnabled(true)
DiamondNum:setPosition(204.0002, 162.9994)
DiamondNum:setTextColor({r = 193, g = 189, b = 237})
layout = ccui.LayoutComponent:bindLayoutComponent(DiamondNum)
layout:setSize({width = 38.0000, height = 28.0000})
layout:setLeftMargin(185.0002)
layout:setRightMargin(-223.0002)
layout:setTopMargin(-176.9994)
layout:setBottomMargin(148.9994)
Diamond:addChild(DiamondNum)

--Create DiamondText_TT
local DiamondText_TT = ccui.Text:create()
DiamondText_TT:ignoreContentAdaptWithSize(true)
DiamondText_TT:setTextAreaSize({width = 0, height = 0})
DiamondText_TT:setFontName("font/Default.ttf")
DiamondText_TT:setFontSize(24)
DiamondText_TT:setString([[/次]])
DiamondText_TT:setTextVerticalAlignment(1)
DiamondText_TT:setLayoutComponentEnabled(true)
DiamondText_TT:setName("DiamondText_TT")
DiamondText_TT:setTag(60)
DiamondText_TT:setCascadeColorEnabled(true)
DiamondText_TT:setCascadeOpacityEnabled(true)
DiamondText_TT:setAnchorPoint(0.0000, 0.5000)
DiamondText_TT:setPosition(222.5000, 164.0000)
DiamondText_TT:setTextColor({r = 177, g = 174, b = 218})
layout = ccui.LayoutComponent:bindLayoutComponent(DiamondText_TT)
layout:setSize({width = 37.0000, height = 32.0000})
layout:setLeftMargin(222.5000)
layout:setRightMargin(-259.5000)
layout:setTopMargin(-180.0000)
layout:setBottomMargin(148.0000)
Diamond:addChild(DiamondText_TT)

--Create FirstText_TT
local FirstText_TT = ccui.Text:create()
FirstText_TT:ignoreContentAdaptWithSize(true)
FirstText_TT:setTextAreaSize({width = 0, height = 0})
FirstText_TT:setFontName("font/Default.ttf")
FirstText_TT:setFontSize(24)
FirstText_TT:setString([[首次修改免费]])
FirstText_TT:setTextHorizontalAlignment(1)
FirstText_TT:setTextVerticalAlignment(1)
FirstText_TT:setLayoutComponentEnabled(true)
FirstText_TT:setName("FirstText_TT")
FirstText_TT:setTag(107)
FirstText_TT:setCascadeColorEnabled(true)
FirstText_TT:setCascadeOpacityEnabled(true)
FirstText_TT:setAnchorPoint(0.0000, 0.5000)
FirstText_TT:setPosition(140.0000, 162.0000)
FirstText_TT:setTextColor({r = 193, g = 189, b = 237})
layout = ccui.LayoutComponent:bindLayoutComponent(FirstText_TT)
layout:setSize({width = 146.0000, height = 32.0000})
layout:setLeftMargin(140.0000)
layout:setRightMargin(-286.0000)
layout:setTopMargin(-178.0000)
layout:setBottomMargin(146.0000)
Middle:addChild(FirstText_TT)

--Create Confirm
local Confirm=cc.Node:create()
Confirm:setName("Confirm")
Confirm:setTag(49)
Confirm:setCascadeColorEnabled(true)
Confirm:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Confirm)
Middle:addChild(Confirm)

--Create ConfirmButton

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton = luaScript.CreateCustomNode()
ConfirmButton:ignoreContentAdaptWithSize(false)
ConfirmButton:loadTextureNormal("01_10_Mail/button_034.png", 1)
ConfirmButton:loadTexturePressed("01_10_Mail/button_034.png", 1)
ConfirmButton:loadTextureDisabled("01_10_Mail/button_034.png", 1)
ConfirmButton:setTitleFontSize(14)
ConfirmButton:setLayoutComponentEnabled(true)
ConfirmButton:setName("ConfirmButton")
ConfirmButton:setTag(50)
ConfirmButton:setCascadeColorEnabled(true)
ConfirmButton:setCascadeOpacityEnabled(true)
ConfirmButton:setPosition(240.8213, 84.0041)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(136.8213)
layout:setRightMargin(-344.8213)
layout:setTopMargin(-133.0041)
layout:setBottomMargin(35.0041)

luaScript.SetDownScele(ConfirmButton, "0.9800")
luaScript.SetClickEffect(ConfirmButton, "Sound004")
luaScript.SetDownColor(ConfirmButton, {r = 65, g = 65, b = 70})
Confirm:addChild(ConfirmButton)

--Create ConfirmText_TT
local ConfirmText_TT = ccui.Text:create()
ConfirmText_TT:ignoreContentAdaptWithSize(true)
ConfirmText_TT:setTextAreaSize({width = 0, height = 0})
ConfirmText_TT:setFontName("font/Font001.ttf")
ConfirmText_TT:setFontSize(28)
ConfirmText_TT:setString([[确认]])
ConfirmText_TT:setTextHorizontalAlignment(1)
ConfirmText_TT:setTextVerticalAlignment(1)
ConfirmText_TT:setLayoutComponentEnabled(true)
ConfirmText_TT:setName("ConfirmText_TT")
ConfirmText_TT:setTag(51)
ConfirmText_TT:setCascadeColorEnabled(true)
ConfirmText_TT:setCascadeOpacityEnabled(true)
ConfirmText_TT:setPosition(239.0000, 84.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmText_TT)
layout:setSize({width = 59.0000, height = 37.0000})
layout:setLeftMargin(209.5000)
layout:setRightMargin(-268.5000)
layout:setTopMargin(-102.5000)
layout:setBottomMargin(65.5000)
Confirm:addChild(ConfirmText_TT)

--Create Cancel
local Cancel=cc.Node:create()
Cancel:setName("Cancel")
Cancel:setTag(54)
Cancel:setCascadeColorEnabled(true)
Cancel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Cancel)
Middle:addChild(Cancel)

--Create CancelButton

local luaScript = require("csd.LuaScript.newButton")
local CancelButton = luaScript.CreateCustomNode()
CancelButton:ignoreContentAdaptWithSize(false)
CancelButton:loadTextureNormal("01_10_Mail/button_035.png", 1)
CancelButton:loadTexturePressed("01_10_Mail/button_035.png", 1)
CancelButton:loadTextureDisabled("01_10_Mail/button_035.png", 1)
CancelButton:setTitleFontSize(14)
CancelButton:setLayoutComponentEnabled(true)
CancelButton:setName("CancelButton")
CancelButton:setTag(53)
CancelButton:setCascadeColorEnabled(true)
CancelButton:setCascadeOpacityEnabled(true)
CancelButton:setPosition(490.9996, 84.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(CancelButton)
layout:setSize({width = 208.0000, height = 98.0000})
layout:setLeftMargin(386.9996)
layout:setRightMargin(-594.9996)
layout:setTopMargin(-133.0009)
layout:setBottomMargin(35.0009)

luaScript.SetDownScele(CancelButton, "0.9800")
luaScript.SetClickEffect(CancelButton, "Sound004")
luaScript.SetDownColor(CancelButton, {r = 65, g = 65, b = 70})
Cancel:addChild(CancelButton)

--Create CancelText_TT
local CancelText_TT = ccui.Text:create()
CancelText_TT:ignoreContentAdaptWithSize(true)
CancelText_TT:setTextAreaSize({width = 0, height = 0})
CancelText_TT:setFontName("font/Font001.ttf")
CancelText_TT:setFontSize(28)
CancelText_TT:setString([[取消]])
CancelText_TT:setTextHorizontalAlignment(1)
CancelText_TT:setTextVerticalAlignment(1)
CancelText_TT:setLayoutComponentEnabled(true)
CancelText_TT:setName("CancelText_TT")
CancelText_TT:setTag(56)
CancelText_TT:setCascadeColorEnabled(true)
CancelText_TT:setCascadeOpacityEnabled(true)
CancelText_TT:setPosition(490.0000, 84.0000)
CancelText_TT:setScaleX(0.9549)
layout = ccui.LayoutComponent:bindLayoutComponent(CancelText_TT)
layout:setSize({width = 59.0000, height = 37.0000})
layout:setLeftMargin(460.5000)
layout:setRightMargin(-519.5000)
layout:setTopMargin(-102.5000)
layout:setBottomMargin(65.5000)
Cancel:addChild(CancelText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

