--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/03_01_Shop/03_01_Shop_1.plist",	
"ui/00_02_Default/00_02_Default_1.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 580.0000, height = 646.0000})

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setTag(198)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setRightMargin(580.0000)
layout:setTopMargin(646.0000)
Layer:addChild(Node)

--Create InteractionPopups
local InteractionPopups = ccui.Layout:create()
InteractionPopups:ignoreContentAdaptWithSize(false)
InteractionPopups:setClippingEnabled(false)
InteractionPopups:setBackGroundColorOpacity(102)
InteractionPopups:setTouchEnabled(true);
InteractionPopups:setLayoutComponentEnabled(true)
InteractionPopups:setName("InteractionPopups")
InteractionPopups:setTag(175)
InteractionPopups:setCascadeColorEnabled(true)
InteractionPopups:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(InteractionPopups)
layout:setSize({width = 580.0000, height = 646.0000})
layout:setRightMargin(-580.0000)
layout:setTopMargin(-646.0000)
Node:addChild(InteractionPopups)

--Create Bg_1
local Bg_1 = ccui.ImageView:create()
Bg_1:ignoreContentAdaptWithSize(false)
Bg_1:loadTexture("03_01_Shop/frame_122.png", 1)
Bg_1:setLayoutComponentEnabled(true)
Bg_1:setName("Bg_1")
Bg_1:setTag(199)
Bg_1:setCascadeColorEnabled(true)
Bg_1:setCascadeOpacityEnabled(true)
Bg_1:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_1)
layout:setSize({width = 580.0000, height = 646.0000})
layout:setRightMargin(-580.0000)
layout:setTopMargin(-646.0000)
Node:addChild(Bg_1)

--Create DiceBoxNode
local DiceBoxNode=cc.Node:create()
DiceBoxNode:setName("DiceBoxNode")
DiceBoxNode:setTag(207)
DiceBoxNode:setCascadeColorEnabled(true)
DiceBoxNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(DiceBoxNode)
Node:addChild(DiceBoxNode)

--Create Bg_2
local Bg_2 = ccui.ImageView:create()
Bg_2:ignoreContentAdaptWithSize(false)
Bg_2:loadTexture("03_01_Shop/picture_058.png", 1)
Bg_2:setLayoutComponentEnabled(true)
Bg_2:setName("Bg_2")
Bg_2:setTag(422)
Bg_2:setCascadeColorEnabled(true)
Bg_2:setCascadeOpacityEnabled(true)
Bg_2:setPosition(363.0000, 353.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Bg_2)
layout:setSize({width = 304.0000, height = 176.0000})
layout:setLeftMargin(211.0000)
layout:setRightMargin(-515.0000)
layout:setTopMargin(-441.0000)
layout:setBottomMargin(265.0000)
DiceBoxNode:addChild(Bg_2)

--Create DiceBoxImage
local DiceBoxImage = ccui.ImageView:create()
DiceBoxImage:ignoreContentAdaptWithSize(false)
DiceBoxImage:loadTexture("00_02_Default/103001.png", 1)
DiceBoxImage:setLayoutComponentEnabled(true)
DiceBoxImage:setName("DiceBoxImage")
DiceBoxImage:setTag(421)
DiceBoxImage:setCascadeColorEnabled(true)
DiceBoxImage:setCascadeOpacityEnabled(true)
DiceBoxImage:setPosition(290.0000, 410.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(DiceBoxImage)
layout:setSize({width = 200.0000, height = 300.0000})
layout:setLeftMargin(190.0000)
layout:setRightMargin(-390.0000)
layout:setTopMargin(-560.0001)
layout:setBottomMargin(260.0001)
DiceBoxNode:addChild(DiceBoxImage)

--Create DiceBoxDepictText
local DiceBoxDepictText = ccui.Text:create()
DiceBoxDepictText:ignoreContentAdaptWithSize(true)
DiceBoxDepictText:setTextAreaSize({width = 0, height = 0})
DiceBoxDepictText:setFontName("font/Default.ttf")
DiceBoxDepictText:setFontSize(28)
DiceBoxDepictText:setString([[古典皇室风格筛盅]])
DiceBoxDepictText:setTextHorizontalAlignment(1)
DiceBoxDepictText:setTextVerticalAlignment(1)
DiceBoxDepictText:setLayoutComponentEnabled(true)
DiceBoxDepictText:setName("DiceBoxDepictText")
DiceBoxDepictText:setTag(424)
DiceBoxDepictText:setCascadeColorEnabled(true)
DiceBoxDepictText:setCascadeOpacityEnabled(true)
DiceBoxDepictText:setPosition(290.0000, 145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DiceBoxDepictText)
layout:setSize({width = 227.0000, height = 37.0000})
layout:setLeftMargin(176.5000)
layout:setRightMargin(-403.5000)
layout:setTopMargin(-163.5000)
layout:setBottomMargin(126.5000)
DiceBoxNode:addChild(DiceBoxDepictText)

--Create DiceBoxNameText
local DiceBoxNameText = ccui.Text:create()
DiceBoxNameText:ignoreContentAdaptWithSize(true)
DiceBoxNameText:setTextAreaSize({width = 0, height = 0})
DiceBoxNameText:setFontName("font/Font001.ttf")
DiceBoxNameText:setFontSize(32)
DiceBoxNameText:setString([[皇室筛盅]])
DiceBoxNameText:setLayoutComponentEnabled(true)
DiceBoxNameText:setName("DiceBoxNameText")
DiceBoxNameText:setTag(423)
DiceBoxNameText:setCascadeColorEnabled(true)
DiceBoxNameText:setCascadeOpacityEnabled(true)
DiceBoxNameText:setPosition(290.0000, 193.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(DiceBoxNameText)
layout:setSize({width = 131.0000, height = 42.0000})
layout:setLeftMargin(224.5000)
layout:setRightMargin(-355.5000)
layout:setTopMargin(-214.0000)
layout:setBottomMargin(172.0000)
DiceBoxNode:addChild(DiceBoxNameText)

--Create PropNode
local PropNode=cc.Node:create()
PropNode:setName("PropNode")
PropNode:setTag(208)
PropNode:setCascadeColorEnabled(true)
PropNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PropNode)
Node:addChild(PropNode)

--Create PropImage
local PropImage = ccui.ImageView:create()
PropImage:ignoreContentAdaptWithSize(false)
PropImage:loadTexture("Default/ImageFile.png", 1)
PropImage:setLayoutComponentEnabled(true)
PropImage:setName("PropImage")
PropImage:setTag(206)
PropImage:setCascadeColorEnabled(true)
PropImage:setCascadeOpacityEnabled(true)
PropImage:setPosition(290.0000, 350.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropImage)
layout:setSize({width = 200.0000, height = 120.0000})
layout:setLeftMargin(190.0000)
layout:setRightMargin(-390.0000)
layout:setTopMargin(-410.0000)
layout:setBottomMargin(290.0000)
PropNode:addChild(PropImage)

--Create PropDepictText
local PropDepictText = ccui.Text:create()
PropDepictText:ignoreContentAdaptWithSize(true)
PropDepictText:setTextAreaSize({width = 0, height = 0})
PropDepictText:setFontName("font/Default.ttf")
PropDepictText:setFontSize(28)
PropDepictText:setString([[购买可获得10000000金币]])
PropDepictText:setTextHorizontalAlignment(1)
PropDepictText:setTextVerticalAlignment(1)
PropDepictText:setLayoutComponentEnabled(true)
PropDepictText:setName("PropDepictText")
PropDepictText:setTag(209)
PropDepictText:setCascadeColorEnabled(true)
PropDepictText:setCascadeOpacityEnabled(true)
PropDepictText:setPosition(290.0000, 145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropDepictText)
layout:setSize({width = 326.0000, height = 37.0000})
layout:setLeftMargin(127.0000)
layout:setRightMargin(-453.0000)
layout:setTopMargin(-163.5000)
layout:setBottomMargin(126.5000)
PropNode:addChild(PropDepictText)

--Create PropNameText
local PropNameText = ccui.Text:create()
PropNameText:ignoreContentAdaptWithSize(true)
PropNameText:setTextAreaSize({width = 0, height = 0})
PropNameText:setFontName("font/Font001.ttf")
PropNameText:setFontSize(32)
PropNameText:setString([[一袋金币]])
PropNameText:setLayoutComponentEnabled(true)
PropNameText:setName("PropNameText")
PropNameText:setTag(210)
PropNameText:setCascadeColorEnabled(true)
PropNameText:setCascadeOpacityEnabled(true)
PropNameText:setPosition(290.0000, 193.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PropNameText)
layout:setSize({width = 130.0000, height = 42.0000})
layout:setLeftMargin(225.0000)
layout:setRightMargin(-355.0000)
layout:setTopMargin(-214.0000)
layout:setBottomMargin(172.0000)
PropNode:addChild(PropNameText)

--Create ConfirmButton

local luaScript = require("csd.LuaScript.newButton")
local ConfirmButton = luaScript.CreateCustomNode()
ConfirmButton:ignoreContentAdaptWithSize(false)
ConfirmButton:loadTextureNormal("03_01_Shop/button_007.png", 1)
ConfirmButton:loadTexturePressed("03_01_Shop/button_007.png", 1)
ConfirmButton:loadTextureDisabled("03_01_Shop/button_007.png", 1)
ConfirmButton:setTitleFontSize(14)
ConfirmButton:setScale9Enabled(true)
ConfirmButton:setCapInsets({x = 15, y = 11, width = 180, height = 66})
ConfirmButton:setLayoutComponentEnabled(true)
ConfirmButton:setName("ConfirmButton")
ConfirmButton:setTag(427)
ConfirmButton:setCascadeColorEnabled(true)
ConfirmButton:setCascadeOpacityEnabled(true)
ConfirmButton:setPosition(290.0000, 74.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmButton)
layout:setSize({width = 254.0000, height = 86.0000})
layout:setLeftMargin(163.0000)
layout:setRightMargin(-417.0000)
layout:setTopMargin(-117.0000)
layout:setBottomMargin(31.0000)

luaScript.SetDownScele(ConfirmButton, "0.9800")
luaScript.SetClickEffect(ConfirmButton, "Sound004")
luaScript.SetDownColor(ConfirmButton, {r = 65, g = 65, b = 70})
Node:addChild(ConfirmButton)

--Create ConfirmNum
local ConfirmNum = ccui.Text:create()
ConfirmNum:ignoreContentAdaptWithSize(true)
ConfirmNum:setTextAreaSize({width = 0, height = 0})
ConfirmNum:setFontName("font/Font003.ttf")
ConfirmNum:setFontSize(32)
ConfirmNum:setString([[2000]])
ConfirmNum:setLayoutComponentEnabled(true)
ConfirmNum:setName("ConfirmNum")
ConfirmNum:setTag(426)
ConfirmNum:setCascadeColorEnabled(true)
ConfirmNum:setCascadeOpacityEnabled(true)
ConfirmNum:setPosition(143.0000, 46.0000)
ConfirmNum:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmNum)
layout:setPositionPercentX(0.5630)
layout:setPositionPercentY(0.5349)
layout:setPercentWidth(0.2480)
layout:setPercentHeight(0.4302)
layout:setSize({width = 63.0000, height = 37.0000})
layout:setLeftMargin(111.5000)
layout:setRightMargin(79.5000)
layout:setTopMargin(21.5000)
layout:setBottomMargin(27.5000)
ConfirmButton:addChild(ConfirmNum)

--Create ConfirmIcon
local ConfirmIcon = ccui.ImageView:create()
ConfirmIcon:ignoreContentAdaptWithSize(false)
ConfirmIcon:loadTexture("03_01_Shop/icon_029.png", 1)
ConfirmIcon:setLayoutComponentEnabled(true)
ConfirmIcon:setName("ConfirmIcon")
ConfirmIcon:setTag(425)
ConfirmIcon:setCascadeColorEnabled(true)
ConfirmIcon:setCascadeOpacityEnabled(true)
ConfirmIcon:setPosition(-22.0000, 17.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ConfirmIcon)
layout:setPositionPercentX(-0.3492)
layout:setPositionPercentY(0.4595)
layout:setPercentWidth(0.6032)
layout:setPercentHeight(0.8649)
layout:setSize({width = 38.0000, height = 32.0000})
layout:setLeftMargin(-41.0000)
layout:setRightMargin(66.0000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(1.0000)
ConfirmNum:addChild(ConfirmIcon)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

