# Uncomment the next line to define a global platform for your project

use_frameworks!
use_modular_headers!
#inhibit_all_warnings!
platform :ios, '10.0'

target 'letsroll-mobile' do

  pod 'FBSDKLoginKit', '~> 12.3.0'
  pod 'FBSDKShareKit', '~> 12.3.0'
  pod 'LineSDKSwift/ObjC', '~>5.0'

  # Pods for letsroll-mobile

end

target 'letsroll-desktop' do


  

  # Pods for letsroll-desktop

end


