--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require("csd.LuaScript.LuaExtend")

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}	
Result["MPLISTLISTDATA"] = { 	
"ui/01_07_Sitting/01_07_Sitting_1.plist",	
"ui/00_01_Common/00_01_Common_1.plist",	
"ui/02_01_Boast/02_01_Boast_1.plist",	
"ui/02_01_Boast/02_01_Boast_2.plist",	
"ui/Default/Default_1.plist",	
}	

------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 420.0000})

--Create UserDetailsNode
local UserDetailsNode=cc.Node:create()
UserDetailsNode:setName("UserDetailsNode")
UserDetailsNode:setTag(669)
UserDetailsNode:setCascadeColorEnabled(true)
UserDetailsNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(UserDetailsNode)
layout:setRightMargin(720.0000)
layout:setTopMargin(420.0000)
Layer:addChild(UserDetailsNode)

--Create bg_1
local bg_1 = ccui.ImageView:create()
bg_1:ignoreContentAdaptWithSize(false)
bg_1:loadTexture("01_07_Sitting/bg_004.png", 1)
bg_1:setLayoutComponentEnabled(true)
bg_1:setName("bg_1")
bg_1:setTag(670)
bg_1:setCascadeColorEnabled(true)
bg_1:setCascadeOpacityEnabled(true)
bg_1:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_1)
layout:setSize({width = 720.0000, height = 420.0000})
layout:setRightMargin(-720.0000)
layout:setTopMargin(-420.0000)
UserDetailsNode:addChild(bg_1)

--Create CollectNode
local CollectNode=cc.Node:create()
CollectNode:setName("CollectNode")
CollectNode:setTag(1872)
CollectNode:setCascadeColorEnabled(true)
CollectNode:setCascadeOpacityEnabled(true)
CollectNode:setPosition(655.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CollectNode)
layout:setLeftMargin(655.0000)
layout:setRightMargin(-655.0000)
layout:setTopMargin(-360.0000)
layout:setBottomMargin(360.0000)
UserDetailsNode:addChild(CollectNode)

--Create CollectIcon
local CollectIcon = ccui.ImageView:create()
CollectIcon:ignoreContentAdaptWithSize(false)
CollectIcon:loadTexture("00_01_Common/icon_127.png", 1)
CollectIcon:setLayoutComponentEnabled(true)
CollectIcon:setName("CollectIcon")
CollectIcon:setTag(1870)
CollectIcon:setCascadeColorEnabled(true)
CollectIcon:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(CollectIcon)
layout:setSize({width = 64.0000, height = 64.0000})
layout:setLeftMargin(-32.0000)
layout:setRightMargin(-32.0000)
layout:setTopMargin(-32.0000)
layout:setBottomMargin(-32.0000)
CollectNode:addChild(CollectIcon)

--Create CollectPanel
local CollectPanel = ccui.Layout:create()
CollectPanel:ignoreContentAdaptWithSize(false)
CollectPanel:setClippingEnabled(false)
CollectPanel:setBackGroundColorOpacity(102)
CollectPanel:setTouchEnabled(true);
CollectPanel:setLayoutComponentEnabled(true)
CollectPanel:setName("CollectPanel")
CollectPanel:setTag(1871)
CollectPanel:setCascadeColorEnabled(true)
CollectPanel:setCascadeOpacityEnabled(true)
CollectPanel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(CollectPanel)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(-40.0000)
layout:setRightMargin(-40.0000)
layout:setTopMargin(-40.0000)
layout:setBottomMargin(-40.0000)
CollectNode:addChild(CollectPanel)

--Create ID
local ID=cc.Node:create()
ID:setName("ID")
ID:setTag(1862)
ID:setCascadeColorEnabled(true)
ID:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(ID)
UserDetailsNode:addChild(ID)

--Create IDText
local IDText = ccui.Text:create()
IDText:ignoreContentAdaptWithSize(true)
IDText:setTextAreaSize({width = 0, height = 0})
IDText:setFontName("font/Font003.ttf")
IDText:setFontSize(28)
IDText:setString([[ID]])
IDText:setTextVerticalAlignment(1)
IDText:setLayoutComponentEnabled(true)
IDText:setName("IDText")
IDText:setTag(1863)
IDText:setCascadeColorEnabled(true)
IDText:setCascadeOpacityEnabled(true)
IDText:setAnchorPoint(0.0000, 0.5000)
IDText:setPosition(306.1819, 380.6620)
IDText:setOpacity(153)
IDText:setTextColor({r = 234, g = 234, b = 234})
layout = ccui.LayoutComponent:bindLayoutComponent(IDText)
layout:setSize({width = 27.0000, height = 33.0000})
layout:setLeftMargin(306.1819)
layout:setRightMargin(-333.1819)
layout:setTopMargin(-397.1620)
layout:setBottomMargin(364.1620)
ID:addChild(IDText)

--Create IDNum
local IDNum = ccui.Text:create()
IDNum:ignoreContentAdaptWithSize(true)
IDNum:setTextAreaSize({width = 0, height = 0})
IDNum:setFontName("font/Font003.ttf")
IDNum:setFontSize(28)
IDNum:setString([[321011]])
IDNum:setTextVerticalAlignment(1)
IDNum:setLayoutComponentEnabled(true)
IDNum:setName("IDNum")
IDNum:setTag(1864)
IDNum:setCascadeColorEnabled(true)
IDNum:setCascadeOpacityEnabled(true)
IDNum:setAnchorPoint(0.0000, 0.5000)
IDNum:setPosition(336.1837, 380.6620)
IDNum:setOpacity(153)
IDNum:setTextColor({r = 234, g = 234, b = 234})
layout = ccui.LayoutComponent:bindLayoutComponent(IDNum)
layout:setSize({width = 77.0000, height = 33.0000})
layout:setLeftMargin(336.1837)
layout:setRightMargin(-413.1837)
layout:setTopMargin(-397.1620)
layout:setBottomMargin(364.1620)
ID:addChild(IDNum)

--Create PlayerLanguageNode
local PlayerLanguageNode=cc.Node:create()
PlayerLanguageNode:setName("PlayerLanguageNode")
PlayerLanguageNode:setTag(133)
PlayerLanguageNode:setCascadeColorEnabled(true)
PlayerLanguageNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerLanguageNode)
UserDetailsNode:addChild(PlayerLanguageNode)

--Create PlayerLanguageText_1_TT
local PlayerLanguageText_1_TT = ccui.Text:create()
PlayerLanguageText_1_TT:ignoreContentAdaptWithSize(true)
PlayerLanguageText_1_TT:setTextAreaSize({width = 0, height = 0})
PlayerLanguageText_1_TT:setFontName("font/Default.ttf")
PlayerLanguageText_1_TT:setFontSize(28)
PlayerLanguageText_1_TT:setString([[语言：简体]])
PlayerLanguageText_1_TT:setLayoutComponentEnabled(true)
PlayerLanguageText_1_TT:setName("PlayerLanguageText_1_TT")
PlayerLanguageText_1_TT:setTag(1865)
PlayerLanguageText_1_TT:setCascadeColorEnabled(true)
PlayerLanguageText_1_TT:setCascadeOpacityEnabled(true)
PlayerLanguageText_1_TT:setPosition(359.9996, 336.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerLanguageText_1_TT)
layout:setSize({width = 143.0000, height = 37.0000})
layout:setLeftMargin(288.4996)
layout:setRightMargin(-431.4996)
layout:setTopMargin(-354.5001)
layout:setBottomMargin(317.5001)
PlayerLanguageNode:addChild(PlayerLanguageText_1_TT)

--Create PlayerLanguageText_2_TT
local PlayerLanguageText_2_TT = ccui.Text:create()
PlayerLanguageText_2_TT:ignoreContentAdaptWithSize(true)
PlayerLanguageText_2_TT:setTextAreaSize({width = 0, height = 0})
PlayerLanguageText_2_TT:setFontName("font/Default.ttf")
PlayerLanguageText_2_TT:setFontSize(28)
PlayerLanguageText_2_TT:setString([[语言：繁体]])
PlayerLanguageText_2_TT:setLayoutComponentEnabled(true)
PlayerLanguageText_2_TT:setName("PlayerLanguageText_2_TT")
PlayerLanguageText_2_TT:setTag(134)
PlayerLanguageText_2_TT:setCascadeColorEnabled(true)
PlayerLanguageText_2_TT:setCascadeOpacityEnabled(true)
PlayerLanguageText_2_TT:setPosition(360.0000, 336.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerLanguageText_2_TT)
layout:setSize({width = 143.0000, height = 37.0000})
layout:setLeftMargin(288.5000)
layout:setRightMargin(-431.5000)
layout:setTopMargin(-354.5000)
layout:setBottomMargin(317.5000)
PlayerLanguageNode:addChild(PlayerLanguageText_2_TT)

--Create PlayerLanguageText_3_TT
local PlayerLanguageText_3_TT = ccui.Text:create()
PlayerLanguageText_3_TT:ignoreContentAdaptWithSize(true)
PlayerLanguageText_3_TT:setTextAreaSize({width = 0, height = 0})
PlayerLanguageText_3_TT:setFontName("font/Default.ttf")
PlayerLanguageText_3_TT:setFontSize(28)
PlayerLanguageText_3_TT:setString([[语言：英文]])
PlayerLanguageText_3_TT:setLayoutComponentEnabled(true)
PlayerLanguageText_3_TT:setName("PlayerLanguageText_3_TT")
PlayerLanguageText_3_TT:setTag(135)
PlayerLanguageText_3_TT:setCascadeColorEnabled(true)
PlayerLanguageText_3_TT:setCascadeOpacityEnabled(true)
PlayerLanguageText_3_TT:setPosition(360.0000, 336.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerLanguageText_3_TT)
layout:setSize({width = 143.0000, height = 37.0000})
layout:setLeftMargin(288.5000)
layout:setRightMargin(-431.5000)
layout:setTopMargin(-354.5000)
layout:setBottomMargin(317.5000)
PlayerLanguageNode:addChild(PlayerLanguageText_3_TT)

--Create PlayerRegisterText
local PlayerRegisterText = ccui.Text:create()
PlayerRegisterText:ignoreContentAdaptWithSize(true)
PlayerRegisterText:setTextAreaSize({width = 0, height = 0})
PlayerRegisterText:setFontName("font/Default.ttf")
PlayerRegisterText:setFontSize(28)
PlayerRegisterText:setString([[注册：{0}天]])
PlayerRegisterText:setLayoutComponentEnabled(true)
PlayerRegisterText:setName("PlayerRegisterText")
PlayerRegisterText:setTag(1866)
PlayerRegisterText:setCascadeColorEnabled(true)
PlayerRegisterText:setCascadeOpacityEnabled(true)
PlayerRegisterText:setPosition(360.0001, 287.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerRegisterText)
layout:setSize({width = 149.0000, height = 37.0000})
layout:setLeftMargin(285.5001)
layout:setRightMargin(-434.5001)
layout:setTopMargin(-305.5000)
layout:setBottomMargin(268.5000)
UserDetailsNode:addChild(PlayerRegisterText)

--Create PlayerTopUpText
local PlayerTopUpText = ccui.Text:create()
PlayerTopUpText:ignoreContentAdaptWithSize(true)
PlayerTopUpText:setTextAreaSize({width = 0, height = 0})
PlayerTopUpText:setFontName("font/Default.ttf")
PlayerTopUpText:setFontSize(28)
PlayerTopUpText:setString([[充值：{0}$]])
PlayerTopUpText:setLayoutComponentEnabled(true)
PlayerTopUpText:setName("PlayerTopUpText")
PlayerTopUpText:setTag(1867)
PlayerTopUpText:setCascadeColorEnabled(true)
PlayerTopUpText:setCascadeOpacityEnabled(true)
PlayerTopUpText:setPosition(360.0001, 237.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(PlayerTopUpText)
layout:setSize({width = 136.0000, height = 37.0000})
layout:setLeftMargin(292.0001)
layout:setRightMargin(-428.0001)
layout:setTopMargin(-256.4999)
layout:setBottomMargin(219.4999)
UserDetailsNode:addChild(PlayerTopUpText)

--Create CurrentServiceText_TT
local CurrentServiceText_TT = ccui.Text:create()
CurrentServiceText_TT:ignoreContentAdaptWithSize(true)
CurrentServiceText_TT:setTextAreaSize({width = 0, height = 0})
CurrentServiceText_TT:setFontName("font/Default.ttf")
CurrentServiceText_TT:setFontSize(28)
CurrentServiceText_TT:setString([[当前客服]])
CurrentServiceText_TT:setLayoutComponentEnabled(true)
CurrentServiceText_TT:setName("CurrentServiceText_TT")
CurrentServiceText_TT:setTag(1869)
CurrentServiceText_TT:setCascadeColorEnabled(true)
CurrentServiceText_TT:setCascadeOpacityEnabled(true)
CurrentServiceText_TT:setPosition(359.9999, 183.9997)
layout = ccui.LayoutComponent:bindLayoutComponent(CurrentServiceText_TT)
layout:setSize({width = 115.0000, height = 37.0000})
layout:setLeftMargin(302.4999)
layout:setRightMargin(-417.4999)
layout:setTopMargin(-202.4997)
layout:setBottomMargin(165.4997)
UserDetailsNode:addChild(CurrentServiceText_TT)

--Create CurrentServicePanel
local CurrentServicePanel = ccui.Layout:create()
CurrentServicePanel:ignoreContentAdaptWithSize(false)
CurrentServicePanel:setClippingEnabled(false)
CurrentServicePanel:setBackGroundColorOpacity(102)
CurrentServicePanel:setTouchEnabled(true);
CurrentServicePanel:setLayoutComponentEnabled(true)
CurrentServicePanel:setName("CurrentServicePanel")
CurrentServicePanel:setTag(1895)
CurrentServicePanel:setCascadeColorEnabled(true)
CurrentServicePanel:setCascadeOpacityEnabled(true)
CurrentServicePanel:setAnchorPoint(0.5000, 0.5000)
CurrentServicePanel:setPosition(359.9999, 113.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(CurrentServicePanel)
layout:setSize({width = 500.0000, height = 80.0000})
layout:setLeftMargin(109.9999)
layout:setRightMargin(-609.9999)
layout:setTopMargin(-153.9998)
layout:setBottomMargin(73.9998)
UserDetailsNode:addChild(CurrentServicePanel)

--Create EnterNode
local EnterNode=cc.Node:create()
EnterNode:setName("EnterNode")
EnterNode:setTag(1896)
EnterNode:setCascadeColorEnabled(true)
EnterNode:setCascadeOpacityEnabled(true)
EnterNode:setPosition(644.0000, 38.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(EnterNode)
layout:setLeftMargin(644.0000)
layout:setRightMargin(-644.0000)
layout:setTopMargin(-38.0000)
layout:setBottomMargin(38.0000)
UserDetailsNode:addChild(EnterNode)

--Create EnterButton

local luaScript = require("csd.LuaScript.newButton")
local EnterButton = luaScript.CreateCustomNode()
EnterButton:ignoreContentAdaptWithSize(false)
EnterButton:loadTextureNormal("02_01_Boast/button_013.png", 1)
EnterButton:loadTexturePressed("02_01_Boast/button_013.png", 1)
EnterButton:loadTextureDisabled("02_01_Boast/button_013_1.png", 1)
EnterButton:setTitleFontSize(14)
EnterButton:setScale9Enabled(true)
EnterButton:setCapInsets({x = 18, y = 15, width = 126, height = 74})
EnterButton:setLayoutComponentEnabled(true)
EnterButton:setName("EnterButton")
EnterButton:setTag(1897)
EnterButton:setCascadeColorEnabled(true)
EnterButton:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(EnterButton)
layout:setSize({width = 120.0000, height = 60.0000})
layout:setLeftMargin(-60.0000)
layout:setRightMargin(-60.0000)
layout:setTopMargin(-30.0000)
layout:setBottomMargin(-30.0000)

luaScript.SetDownScele(EnterButton, "0.9500")
luaScript.SetClickEffect(EnterButton, "")
luaScript.SetDownColor(EnterButton, {r = 65, g = 65, b = 70})
EnterNode:addChild(EnterButton)

--Create EnterText_TT
local EnterText_TT = ccui.Text:create()
EnterText_TT:ignoreContentAdaptWithSize(true)
EnterText_TT:setTextAreaSize({width = 0, height = 0})
EnterText_TT:setFontName("font/Default.ttf")
EnterText_TT:setFontSize(22)
EnterText_TT:setString([[进对局]])
EnterText_TT:setTextHorizontalAlignment(1)
EnterText_TT:setTextVerticalAlignment(1)
EnterText_TT:setLayoutComponentEnabled(true)
EnterText_TT:setName("EnterText_TT")
EnterText_TT:setTag(1898)
EnterText_TT:setCascadeColorEnabled(true)
EnterText_TT:setCascadeOpacityEnabled(true)
EnterText_TT:setPosition(0.0000, 2.0000)
EnterText_TT:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(EnterText_TT)
layout:setSize({width = 68.0000, height = 29.0000})
layout:setLeftMargin(-34.0000)
layout:setRightMargin(-34.0000)
layout:setTopMargin(-16.5000)
layout:setBottomMargin(-12.5000)
EnterNode:addChild(EnterText_TT)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

